### ISSUE TITLE
Crash after posting on arisuchan

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#105]
Happens every time after posting:
```
D/AndroidRuntime: Shutting down VM
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.github.adamantcheese.chan, PID: 10737
E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
E/AndroidRuntime: 	at com.github.adamantcheese.chan.b.d.r.a(Unknown Source:13)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.b.d.r.b(Unknown Source:1)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.b.d.a.run(Unknown Source:4)
E/AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6696)
E/AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.d.r.a(Unknown Source:13)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.d.r.b(Unknown Source:1)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.d.a.run(Unknown Source:4)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:789)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:164)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6696)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
I/zygote64: System.exit called, status: 999
I/AndroidRuntime: VM exiting with result code 999, cleanup skipped.
```

**Comment by Adamantcheese** [comment]
I've cleaned up your crash log, but I'll also add those things I deleted to the ignore list so that they won't show up again.

**Comment by Adamantcheese** [comment]
There was only one case where I was doing that boxed to primitive cast for Long, so it was an easy thing to find. Because of your log I've also disabled minification, to help out with the logs being sorta uninformative, but it does make the APK a megabyte or so bigger, which isn't that bad.
