### ISSUE TITLE
Crash report "org.codejargon.feather.FeatherException: Can't inject field presenter in com.github.adamantcheese.chan.ui.controller.SiteSetupController"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1088]
UUID: 9b674145354e527b5ab11a4f21c0f5be
Build flavor: dev
Version name: v4.13.6-df202a2
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:
```
=== LOGS(September 2, 2020 4:15:51 AM UTC) ===
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/vg/1599019985XXX.jpg
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=true
D/Kuroba-dev | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/vg/1599019985XXX.jpg
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | FileCacheV2: [FileCacheV2Thread-1]: Success (downloaded = 93.4 KiB (95670 B), total = 93.4 KiB (95670 B), took 192ms, network class = 4G, downloads = 1) for request [FileDownloadRequest: url = https://i.4cdn.org/vg/1599019985XXX.jpg, outputFileName = 36dad08f03606cdc043a0c415b8a0681.cache]
D/Kuroba-dev | CustomScaleImageView: onReady
D/Kuroba-dev | CustomScaleImageView: onImageLoaded
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 15s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/vg/1599019985XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/vg/1599019985XXX.jpg
D/Kuroba-dev | CustomScaleImageView: onReady
D/Kuroba-dev | CustomScaleImageView: onImageLoaded
D/Kuroba-dev | ChanThreadLoader: Cleared runnable
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 15s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | ChanThreadLoader: Cleared runnable
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=false
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 10s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=true
D/Kuroba-dev | ChanThreadLoader: Cleared runnable
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=false
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 15s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=true
D/Kuroba-dev | ChanThreadLoader: Cleared runnable
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=false
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 15s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=true
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 10s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 15s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | WatchManager: updateState watchEnabled=false backgroundEnabled=false foreground=true
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | CaptchaNoJsPresenterV2: Got new challenge
D/Kuroba-dev | CaptchaNoJsPresenterV2: Verify called
D/Kuroba-dev | CaptchaNoJsPresenterV2: Got the verification token
D/Kuroba-dev | CaptchaHolder: New token added, validCount = 1, token = validUntil = 2020-09-02 12:17:43, token = 03AGdBqâ€¦rqzVEl6L
D/Kuroba-dev | CaptchaHolder: Timer started
D/Kuroba-dev | CaptchaHolder: Got token validUntil = 2020-09-02 12:17:43, token = 03AGdBqâ€¦rqzVEl6L
D/Kuroba-dev | ReplyLayout: Switching to page LOADING
D/Kuroba-dev | ReplyLayout: Switching to page INPUT
D/Kuroba-dev | ChanThreadLoader: Cleared runnable
D/Kuroba-dev | ChanThreadLoader: Requested /vg/, 305664XXX
D/Kuroba-dev | CaptchaHolder: Timer stopped
D/Kuroba-dev | ChanThreadLoader: Scheduled reload in 15s
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: org.codejargon.feather.FeatherException: Can't inject field presenter in com.github.adamantcheese.chan.ui.controller.SiteSetupController
E/Kuroba-dev | UNCAUGHT: 	at org.codejargon.feather.Feather.injectFields(Feather.java:87)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.Chan.inject(Chan.java:85)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.Controller.<init>(Controller.java:78)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.settings.SettingsController.<init>(SettingsController.java:70)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.SiteSetupController.<init>(SiteSetupController.java:54)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BrowseController.loadSiteSetup(BrowseController.java:418)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.BrowsePresenter.onBoardsFloatingMenuSiteClicked(BrowsePresenter.java:78)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BrowseController.onSiteClicked(BrowseController.java:279)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu.itemClicked(BrowseBoardsFloatingMenu.java:174)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu.access$400(BrowseBoardsFloatingMenu.java:79)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu$SiteViewHolder.lambda$bind$0$BrowseBoardsFloatingMenu$SiteViewHolder(BrowseBoardsFloatingMenu.java:438)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.-$$Lambda$BrowseBoardsFloatingMenu$SiteViewHolder$0x9nAfxTARnTL2Q9SlP15-nH15M.onClick(Unknown Source:4)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.performClick(View.java:6300)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:24995)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:790)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:164)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6894)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 27
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-df202a2
E/Kuroba-dev | UNCAUGHT: Phone Model: TP-Link Neffos_Y7


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Youtube titles parsing enabled: true
Youtube durations parsing enabled: true
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba-dev/saved_threads, SAF location: , active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by hockeymikey** [comment]
Having this same issue only with ImagePickDelegate
