### ISSUE TITLE
Crash report " java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.github.adamantcheese.chan.core.site.Site.siteFeature(com.github.adamantcheese.chan.core.site.Site$SiteFeature)' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1121]
Crash report
UUID: 07a81179f8606b79b783d666b038c5ea
Build flavor: dev
Version name: v4.13.6-1cbd79b
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(October 16, 2020 10:02:53 AM UTC) ===
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.github.adamantcheese.chan.core.site.Site.siteFeature(com.github.adamantcheese.chan.core.site.Site$SiteFeature)' on a null object reference
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell.bindPost(PostCell.java:521)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell.setPost(PostCell.java:301)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.onBindViewHolder(PostAdapter.java:145)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
E/Kuroba-dev | UNCAUGHT: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1156)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.DrawerWidthAdjustingLayout.onMeasure(DrawerWidthAdjustingLayout.java:54)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Kuroba-dev | UNCAUGHT: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.measure(View.java:24716)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.m
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-1cbd79b
E/Kuroba-dev | UNCAUGHT: Phone Model: KONROW SKY55_EEA


=== SETTINGS ===
Prefetching enabled: false
Media title parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by Dashinginthe90s** [comment]
I'm getting a crash with the same exception in dev v4.13.6-1cbd79b3 when tapping settings > appearance > theme. 
I would attach a a copy of my crashlog but I'm not sure how. I sent a crash log using the option built into the app but it doesn't give me the option to create a github issue or add more details.
