### ISSUE TITLE
Crash while searching + other stuff I don't remember

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#119]
```--------- beginning of main
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/art     : Do partial code cache collection, code=20KB, data=30KB
I/art     : After code cache collection, code=20KB, data=30KB
I/art     : Increasing code cache capacity to 128KB
I/art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/art     :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
I/art     :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
I/art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatDelegateImpl.findViewById(int) (AppCompatDelegateImpl.java:403)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatActivity.findViewById(int) (AppCompatActivity.java:191)
I/art     :   at void com.github.adamantcheese.chan.StartActivity.onCreate(android.os.Bundle) (StartActivity.java:119)
I/art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
I/art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
I/art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
I/art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
I/art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
I/art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     :   at void android.os.Looper.loop() (Looper.java:154)
I/art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
I/art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
I/art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
I/art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.github.adamantcheese.chan-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.adamantcheese.chan-1/lib/arm, /data/app/com.github.adamantcheese.chan-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
I/art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
I/art     :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
I/art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatDelegateImpl.findViewById(int) (AppCompatDelegateImpl.java:403)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatActivity.findViewById(int) (AppCompatActivity.java:191)
I/art     :   at void com.github.adamantcheese.chan.StartActivity.onCreate(android.os.Bundle) (StartActivity.java:119)
I/art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
I/art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
I/art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
I/art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
I/art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
I/art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     :   at void android.os.Looper.loop() (Looper.java:154)
I/art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
I/art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
I/art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
I/art     : 
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
V/NFC     : this device does not have NFC support
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
I/art     : Do partial code cache collection, code=53KB, data=62KB
I/art     : After code cache collection, code=53KB, data=62KB
I/art     : Increasing code cache capacity to 256KB
I/art     : Background sticky concurrent mark sweep GC freed 19486(2MB) AllocSpace objects, 66(4MB) LOS objects, 29% free, 7MB/10MB, paused 9.588ms total 114.782ms
I/art     : Background partial concurrent mark sweep GC freed 34477(2MB) AllocSpace objects, 31(2MB) LOS objects, 40% free, 5MB/9MB, paused 5.338ms total 44.481ms
I/art     : Do full code cache collection, code=110KB, data=125KB
I/art     : Starting a blocking GC JitCodeCache
I/art     : After code cache collection, code=66KB, data=67KB
I/art     : Background partial concurrent mark sweep GC freed 25714(3MB) AllocSpace objects, 108(7MB) LOS objects, 39% free, 11MB/19MB, paused 2.127ms total 138.357ms
I/art     : Do partial code cache collection, code=112KB, data=123KB
I/art     : After code cache collection, code=111KB, data=122KB
I/art     : Increasing code cache capacity to 512KB
W/art     : Before Android 4.1, method int androidx.appcompat.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
D/OpenGLRenderer: endAllActiveAnimators on 0x9730d800 (DropDownListView) with handle 0x99adceb0
I/art     : Do full code cache collection, code=230KB, data=251KB
I/art     : Starting a blocking GC JitCodeCache
I/art     : After code cache collection, code=210KB, data=215KB
I/art     : Do partial code cache collection, code=234KB, data=249KB
I/art     : After code cache collection, code=233KB, data=248KB
I/art     : Increasing code cache capacity to 1024KB
E/Kuroba | ReplyPresenter: onPostComplete error
I/art     : Background sticky concurrent mark sweep GC freed 139047(4MB) AllocSpace objects, 5(488KB) LOS objects, 28% free, 13MB/19MB, paused 1.179ms total 105.849ms
I/art     : Background sticky concurrent mark sweep GC freed 60213(6MB) AllocSpace objects, 85(6MB) LOS objects, 11% free, 23MB/27MB, paused 8.007ms total 129.170ms
D/AndroidRuntime: Shutting down VM
E/Kuroba | UNCAUGHT: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.github.adamantcheese.chan.ui.layout.SearchLayout
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.lambda$onSearchVisibilityChanged$0$Toolbar(Toolbar.java:317)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.-$$Lambda$Toolbar$VVcH5UJcbDJ6my7V4xXJhw9RNUM.run(lambda)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.Toolbar$2.onAnimationEnd(Toolbar.java:178)
E/Kuroba | UNCAUGHT: 	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
E/Kuroba | UNCAUGHT: 	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
E/Kuroba | UNCAUGHT: 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1313)
E/Kuroba | UNCAUGHT: 	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
E/Kuroba | UNCAUGHT: 	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
E/Kuroba | UNCAUGHT: 	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer.doFrame(Choreographer.java:618)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
I/art     : System.exit called, status: 999
I/AndroidRuntime: VM exiting with result code 999, cleanup skipped.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/art     : Do partial code cache collection, code=20KB, data=30KB
I/art     : After code cache collection, code=20KB, data=30KB
I/art     : Increasing code cache capacity to 128KB
I/art     : Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
I/art     :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
I/art     :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
I/art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatDelegateImpl.findViewById(int) (AppCompatDelegateImpl.java:403)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatActivity.findViewById(int) (AppCompatActivity.java:191)
I/art     :   at void com.github.adamantcheese.chan.StartActivity.onCreate(android.os.Bundle) (StartActivity.java:119)
I/art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
I/art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
I/art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
I/art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
I/art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
I/art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     :   at void android.os.Looper.loop() (Looper.java:154)
I/art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
I/art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
I/art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
I/art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.github.adamantcheese.chan-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.adamantcheese.chan-1/lib/arm, /data/app/com.github.adamantcheese.chan-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
I/art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
I/art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
I/art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/art     :   at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
I/art     :   at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
I/art     :   at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatDelegateImpl.findViewById(int) (AppCompatDelegateImpl.java:403)
I/art     :   at android.view.View androidx.appcompat.app.AppCompatActivity.findViewById(int) (AppCompatActivity.java:191)
I/art     :   at void com.github.adamantcheese.chan.StartActivity.onCreate(android.os.Bundle) (StartActivity.java:119)
I/art     :   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
I/art     :   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
I/art     :   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
I/art     :   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
I/art     :   at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
I/art     :   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
I/art     :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
I/art     :   at void android.os.Looper.loop() (Looper.java:154)
I/art     :   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
I/art     :   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art     :   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
I/art     :   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
I/art     : 
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
V/NFC     : this device does not have NFC support
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
I/art     : Do partial code cache collection, code=52KB, data=62KB
I/art     : After code cache collection, code=52KB, data=62KB
I/art     : Increasing code cache capacity to 256KB
I/art     : Do full code cache collection, code=109KB, data=125KB
I/art     : Starting a blocking GC JitCodeCache
I/art     : After code cache collection, code=65KB, data=65KB
I/art     : Do partial code cache collection, code=106KB, data=125KB
I/art     : After code cache collection, code=100KB, data=120KB
I/art     : Increasing code cache capacity to 512KB
```

**Comment by ownBard** [comment]
@floppyD (See also #98)

**Comment by Adamantcheese** [comment]
Please check if this still occurs on the most recent version. The log format has changed a little bit and it'll be more clear now what the issue is.

**Comment by floppyD** [comment]
Well, I don't remember what I was doing while searching that caused the crash, so I can't really check. It was something related to that bookmarks menu, but it wasn't entering a thread.

**Comment by Adamantcheese** [comment]
Since the cause of the bug can't be determined and the only uncaught exception here has been resolved, I'll close this. If it happens again, submit a new issue.
