### ISSUE TITLE
Crash report "java.lang.IllegalStateException: closed"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1204]
Crash report
UUID: 046991ab2aa08b3ccd44a8abbc3ded61
Build flavor: dev
Version name: v4.13.6-b44786f
OS info: Android 11, sdk version: 30
Report description: No title
Logs:
```
=== LOGS(December 22, 2020 10:00:37 PM UTC) ===
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=14s
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
I/Kuroba-dev | WakeManager: Stopped background alarm
D/Kuroba-dev | WatchManager: Setting interval type from BACKGROUND to FOREGROUND
E/Kuroba-dev | CaptchaNoJsLayoutV2: CaptchaV2 error
E/Kuroba-dev | CaptchaNoJsLayoutV2: java.io.IOException: Bad status code for captcha request = 404
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.handleGetRecaptchaResponse(CaptchaNoJsPresenterV2.java:263)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.getCaptchaInfo(CaptchaNoJsPresenterV2.java:226)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.lambda$requestCaptchaInfo$1(CaptchaNoJsPresenterV2.java:178)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.lambda$requestCaptchaInfo$1$CaptchaNoJsPresenterV2(Unknown Source:0)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.-$$Lambda$CaptchaNoJsPresenterV2$IatK49r-Hfa2rjokF-3mEraOOoQ.run(Unknown Source:2)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.utils.BackgroundUtils.lambda$runWithExecutor$4(BackgroundUtils.java:130)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.utils.-$$Lambda$BackgroundUtils$9rYhI88R5umxXjUeRlJcaj1Psyk.run(Unknown Source:6)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.lang.Thread.run(Thread.java:923)
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.IllegalStateException: closed
E/Kuroba-dev | UNCAUGHT: 	at okio.RealBufferedSource.select(RealBufferedSource.kt:81)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.Util.readBomAsCharset(Util.kt:258)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.captcha.v1.CaptchaNojsLayoutV1$3.onResponse(CaptchaNojsLayoutV1.java:180)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:923)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 30
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-b44786f
E/Kuroba-dev | UNCAUGHT: Phone Model: OnePlus OnePlus 7T
D/Kuroba-dev | ReportManager: Stored new crash log, path = /storage/emulated/0/Android/data/com.github.adamantcheese.chan.dev/cache/crashlogs/crashlog_1608674379133.txt
D/Kuroba-dev | Dependency Injection: Database helper
D/Kuroba-dev | Dependency Injection: Database board manager
D/Kuroba-dev | Dependency Injection: Database site manager
D/Kuroba-dev | Dependency Injection: Gson module
D/Kuroba-dev | Dependency Injection: Site repository
D/Kuroba-dev | Dependency Injection: Board repository
D/Kuroba-dev | Dependency Injection: Board manager
D/Kuroba-dev | Dependency Injection: Proxied OkHTTP client
D/Kuroba-dev | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/Kuroba-dev | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/Kuroba-dev | Dependency Injection: Report manager
D/Kuroba-dev | SiteModel: Config: {"internal_site_id":0,"external":false}, Settings: {"settings":{"preference_captcha_type":{"type":"string","value":"v2js"}}}
D/Kuroba-dev | SiteModel: Config: {"internal_site_id":8,"external":false}, Settings: {"settings":{}}
D/Kuroba-dev | Dependency Injection: Database loadable manager
D/Kuroba-dev | Dependency Injection: Site resolver
D/Kuroba-dev | Dependency Injection: Database pin manager
D/Kuroba-dev | Dependency Injection: Wake manager
I/Kuroba-dev | WakeManager: Started background alarm with an interval of 15 minutes
D/Kuroba-dev | Dependency Injection: Watch manager
D/Kuroba-dev | Dependency Injection: Cache handler
D/Kuroba-dev | Dependency Injection: File cache V2
D/Kuroba-dev | Dependency Injection: Android10GesturesExclusionZonesHolder
D/Kuroba-dev | Android10GesturesExclusionZonesHolder: Json setting string is empty, reset.
D/Kuroba-dev | Dependency Injection: Database hide manager
D/Kuroba-dev | Dependency Injection: Captcha holder
D/Kuroba-dev | Dependency Injection: Database saved reply manager
D/Kuroba-dev | Dependency Injection: Database filter manager
D/Kuroba-dev | Dependency Injection: Filter engine
D/Kuroba-dev | Dependency Injection: Filter watch manager
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='vp', no=45746XXX', listViewIndex=48, listViewTop=-515, lastViewed=45746XXX, lastLoaded=45747XXX, markedNo=-1}
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='trash', no=34867XXX', listViewIndex=190, listViewTop=-337, lastViewed=34923XXX, lastLoaded=34923XXX, markedNo=-1}
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='trash', no=34777XXX', listViewIndex=195, listViewTop=-255, lastViewed=34928XXX, lastLoaded=34928XXX, markedNo=-1}
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='mlp', no=36285XXX', listViewIndex=189, listViewTop=-244, lastViewed=36308XXX, lastLoaded=36308XXX, markedNo=-1}
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='mlp', no=36251XXX', listViewIndex=306, listViewTop=-602, lastViewed=36310XXX, lastLoaded=36310XXX, markedNo=-1}
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='mlp', no=36240XXX', listViewIndex=273, listViewTop=-360, lastViewed=36310XXX, lastLoaded=36310XXX, markedNo=-1}
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
D/Kuroba-dev | FilterEngine: Resulting pattern: 95372ccdd2ef1a5dfd919c5ff0c23c9c
D/Kuroba-dev | WakeUpdateReceiver: Alarm trigger at Dec 22, 2020 3:59:46 PM
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | ReportManager: Collected 1 crash logs
D/Kuroba-dev | ReportManager: Crash log /storage/emulated/0/Android/data/com.github.adamantcheese.chan.dev/cache/crashlogs/crashlog_1608674379133.txt sent!
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=9s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=7s
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=14s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=false
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to BACKGROUND
D/Kuroba-dev | WakeManager: Registered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | PinWatcher: postlast=314 postnew=321 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=9s
D/Kuroba-dev | PinWatcher: postlast=57 postnew=57 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=9s
D/Kuroba-dev | PinWatcher: postlast=197 postnew=220 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=9s
D/Kuroba-dev | PinWatcher: postlast=195 postnew=225 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=9s
D/Kuroba-dev | PinWatcher: postlast=280 postnew=286 werenewposts=false quotelast=2 quotenew=2 werenewquotes=false nextload=9s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=false
D/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
I/Kuroba-dev | WakeManager: Stopped background alarm
D/Kuroba-dev | WatchManager: Setting interval type from BACKGROUND to FOREGROUND
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=0s
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=14s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | PinWatcher: postlast=57 postnew=57 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=14s
D/Kuroba-dev | PinWatcher: postlast=195 postnew=225 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=15s
D/Kuroba-dev | PinWatcher: postlast=314 postnew=321 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=15s
D/Kuroba-dev | PinWatcher: postlast=197 postnew=220 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=14s
D/Kuroba-dev | PinWatcher: postlast=280 postnew=286 werenewposts=false quotelast=2 quotenew=2 werenewquotes=false nextload=14s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=14s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | PinWatcher: postlast=177 postnew=177 werenewposts=false quotelast=11 quotenew=11 werenewquotes=false nextload=14s
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
E/Kuroba-dev | CaptchaNoJsLayoutV2: CaptchaV2 error
E/Kuroba-dev | CaptchaNoJsLayoutV2: java.io.IOException: Bad status code for captcha request = 404
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.handleGetRecaptchaResponse(CaptchaNoJsPresenterV2.java:263)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.getCaptchaInfo(CaptchaNoJsPresenterV2.java:226)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.lambda$requestCaptchaInfo$1(CaptchaNoJsPresenterV2.java:178)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.CaptchaNoJsPresenterV2.lambda$requestCaptchaInfo$1$CaptchaNoJsPresenterV2(Unknown Source:0)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.ui.captcha.v2.-$$Lambda$CaptchaNoJsPresenterV2$IatK49r-Hfa2rjokF-3mEraOOoQ.run(Unknown Source:2)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.utils.BackgroundUtils.lambda$runWithExecutor$4(BackgroundUtils.java:130)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at com.github.adamantcheese.chan.utils.-$$Lambda$BackgroundUtils$9rYhI88R5umxXjUeRlJcaj1Psyk.run(Unknown Source:6)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | CaptchaNoJsLayoutV2: 	at java.lang.Thread.run(Thread.java:923)
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=true foreground=true
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.IllegalStateException: closed
E/Kuroba-dev | UNCAUGHT: 	at okio.RealBufferedSource.select(RealBufferedSource.kt:81)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.Util.readBomAsCharset(Util.kt:258)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.captcha.v1.CaptchaNojsLayoutV1$3.onResponse(CaptchaNojsLayoutV1.java:180)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:923)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 30
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-b44786f
E/Kuroba-dev | UNCAUGHT: Phone Model: OnePlus OnePlus 7T


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Pictures/Kuroba, SAF location: content://com.android.externalstorage.documents/tree/primary%3APictures%2FKuroba, active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
```

**Comment by Adamantcheese** [comment]
This one was closed with 0883c6955ed78e465270e0a6835b21bb08ae7b2c, but people will have to update manually if they're stuck somewhere before cce9957ddd76b4ad1354f2878eb9a2a1e6fe8d9a due to some fixes I was testing out that broke a few things.
