### ISSUE TITLE
Report "Old style images gives 404 error"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1213]
UUID: 3d8490a39dd92736ff15aeb838213ff3
Build flavor: stable
Version name: v4.13.6
OS info: Android 10, sdk version: 29
Report description: Can you make old style images (media.8kun.top/boardname/src/unixtimestampfilename.extension) work in the 8kun extension? Some older and slower boards still have those images. I guess your extension try to parse media.8kun/file_store/hashedfilename format and that is the reason it gives 404 error for old file formats. Thank you!
```
Logs:
E/Kuroba | NetUtils: Error with request: 
E/Kuroba | NetUtils: java.net.ConnectException: Failed to connect to a.4cdn.org/104.16.61.249:443
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
E/Kuroba | NetUtils: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | NetUtils: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
E/Kuroba | NetUtils: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | NetUtils: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
E/Kuroba | NetUtils: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | NetUtils: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
E/Kuroba | NetUtils: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | NetUtils: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba | NetUtils: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.59.249 (port 443) from /192.168.1.195 (port 43128) after 30000ms
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | NetUtils: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | NetUtils: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | NetUtils: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | NetUtils: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | NetUtils: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | NetUtils: 		... 18 more
E/Kuroba | NetUtils: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.60.249 (port 443) from /192.168.1.195 (port 44232) after 30000ms
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | NetUtils: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | NetUtils: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | NetUtils: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | NetUtils: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | NetUtils: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | NetUtils: 		... 18 more
E/Kuroba | NetUtils: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.58.249 (port 443) from /192.168.1.195 (port 47762) after 30000ms
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | NetUtils: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | NetUtils: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | NetUtils: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | NetUtils: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | NetUtils: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | NetUtils: 		... 18 more
E/Kuroba | NetUtils: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.62.249 (port 443) from /192.168.1.195 (port 43978) after 30000ms
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | NetUtils: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | NetUtils: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | NetUtils: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | NetUtils: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | NetUtils: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | NetUtils: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | NetUtils: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | NetUtils: 		... 18 more
E/Kuroba | NetUtils: Caused by: java.net.ConnectException: failed to connect to a.4cdn.org/104.16.61.249 (port 443) from /192.168.1.195 (port 44436) after 30000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
E/Kuroba | NetUtils: 	at libcore.io.IoBridge.isConnected(IoBridge.java:288)
E/Kuroba | NetUtils: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
E/Kuroba | NetUtils: 	at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | NetUtils: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | NetUtils: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | NetUtils: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | NetUtils: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | NetUtils: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | NetUtils: 	at java.net.Socket.connect(Socket.java:621)
E/Kuroba | NetUtils: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | NetUtils: 	... 18 more
E/Kuroba | NetUtils: Caused by: android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
E/Kuroba | NetUtils: 	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
E/Kuroba | NetUtils: 	... 28 more
E/Kuroba | Chan4: Failed to get boards from server
E/Kuroba | Chan4: java.net.ConnectException: Failed to connect to a.4cdn.org/104.16.61.249:443
E/Kuroba | Chan4: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
E/Kuroba | Chan4: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | Chan4: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
E/Kuroba | Chan4: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | Chan4: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
E/Kuroba | Chan4: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | Chan4: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
E/Kuroba | Chan4: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
E/Kuroba | Chan4: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | Chan4: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | Chan4: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba | Chan4: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.59.249 (port 443) from /192.168.1.195 (port 43128) after 30000ms
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | Chan4: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | Chan4: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | Chan4: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | Chan4: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | Chan4: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | Chan4: 		... 18 more
E/Kuroba | Chan4: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.60.249 (port 443) from /192.168.1.195 (port 44232) after 30000ms
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | Chan4: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | Chan4: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | Chan4: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | Chan4: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | Chan4: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | Chan4: 		... 18 more
E/Kuroba | Chan4: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.58.249 (port 443) from /192.168.1.195 (port 47762) after 30000ms
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | Chan4: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | Chan4: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | Chan4: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | Chan4: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | Chan4: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | Chan4: 		... 18 more
E/Kuroba | Chan4: 	Suppressed: java.net.SocketTimeoutException: failed to connect to a.4cdn.org/104.16.62.249 (port 443) from /192.168.1.195 (port 43978) after 30000ms
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
E/Kuroba | Chan4: 		at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | Chan4: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | Chan4: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | Chan4: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | Chan4: 		at java.net.Socket.connect(Socket.java:621)
E/Kuroba | Chan4: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | Chan4: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | Chan4: 		... 18 more
E/Kuroba | Chan4: Caused by: java.net.ConnectException: failed to connect to a.4cdn.org/104.16.61.249 (port 443) from /192.168.1.195 (port 44436) after 30000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
E/Kuroba | Chan4: 	at libcore.io.IoBridge.isConnected(IoBridge.java:288)
E/Kuroba | Chan4: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
E/Kuroba | Chan4: 	at libcore.io.IoBridge.connect(IoBridge.java:135)
E/Kuroba | Chan4: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
E/Kuroba | Chan4: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/Kuroba | Chan4: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/Kuroba | Chan4: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/Kuroba | Chan4: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/Kuroba | Chan4: 	at java.net.Socket.connect(Socket.java:621)
E/Kuroba | Chan4: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
E/Kuroba | Chan4: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
E/Kuroba | Chan4: 	... 18 more
E/Kuroba | Chan4: Caused by: android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
E/Kuroba | Chan4: 	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
E/Kuroba | Chan4: 	... 28 more
I/Kuroba | WakeManager: Started background alarm with an interval of 15 minutes
E/Kuroba | NetUtils: Error parsing JSON: 
E/Kuroba | NetUtils: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY
E/Kuroba | NetUtils: 	at android.util.JsonReader.expect(JsonReader.java:312)
E/Kuroba | NetUtils: 	at android.util.JsonReader.beginObject(JsonReader.java:295)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.parser.CommentParserHelper.lambda$replaceYoutubeLinks$0(CommentParserHelper.java:150)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.parser.-$$Lambda$CommentParserHelper$9ajzVQqM4-uGmuZvdOXvAqvrToI.parse(Unknown Source:0)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.utils.NetUtils.makeJsonRequestSync(NetUtils.java:253)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.parser.CommentParserHelper.replaceYoutubeLinks(CommentParserHelper.java:119)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:207)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:227)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:227)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseComment(DefaultPostParser.java:178)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parse(DefaultPostParser.java:74)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.parser.PostParseCallable.call(PostParseCallable.java:66)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.site.parser.PostParseCallable.call(PostParseCallable.java:30)
E/Kuroba | NetUtils: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)
E/Kuroba | NetUtils: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
E/Kuroba | NetUtils: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
E/Kuroba | NetUtils: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
E/Kuroba | NetUtils: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
E/Kuroba | NetUtils: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
E/Kuroba | DefaultPostParser: Error parsing comment html
E/Kuroba | DefaultPostParser: java.lang.IllegalStateException: closed
E/Kuroba | DefaultPostParser: 	at okio.RealBufferedSource.select(RealBufferedSource.kt:220)
E/Kuroba | DefaultPostParser: 	at okhttp3.internal.Util.readBomAsCharset(Util.kt:259)
E/Kuroba | DefaultPostParser: 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.utils.NetUtils.makeJsonRequestSync(NetUtils.java:258)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.parser.CommentParserHelper.replaceYoutubeLinks(CommentParserHelper.java:119)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:207)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:227)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:227)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseComment(DefaultPostParser.java:178)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parse(DefaultPostParser.java:74)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.parser.PostParseCallable.call(PostParseCallable.java:66)
E/Kuroba | DefaultPostParser: 	at com.github.adamantcheese.chan.core.site.parser.PostParseCallable.call(PostParseCallable.java:30)
E/Kuroba | DefaultPostParser: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1433)
E/Kuroba | DefaultPostParser: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
E/Kuroba | DefaultPostParser: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
E/Kuroba | DefaultPostParser: 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
E/Kuroba | DefaultPostParser: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
E/Kuroba | DefaultPostParser: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jasonmyers-debug** [comment]
Having the same problem. 90% of threads past 2016 are not readable as the images don't load.

**Comment by Adamantcheese** [comment]
Not my fault the site's shit at managing assets and isn't consistent with it. If someone has an exact date for when it occurred, post it here and I can fix it quick.

**Comment by Staine** [comment]
I think they speak about images like this one: https://media.8kun.top/nohup/src/1432898528984.png
nohup is the board name and images were seperately stored under "boardname/src/unixtimestampname" format back then instead of the common file_store. This caused multiple instances of the same image on the server under different folders. Then the site was modified use a common image which is linked to boards.  
And it used the boardname/thumb/unixtimestampname format for the thumbs. (For example: https://media.8kun.top/nohup/thumb/1432898528984.jpg)

It was the old way which was used before 2016. Some boards still have threads with old style images.
`return HttpUrl.parse(
                        "https://media.8kun.top/" + "file_store/" + (arg.get("tim") + "." + arg.get("ext")));
            }`
Your code parses only to the file_store format so it gives a wrong link for the old images. You may need to add a switch if you wanna support old image links. Your choice if you wanna support these old, slow, abandoned boards or not.

**Comment by Adamantcheese** [comment]
I know what code to write, I don't know what date it starts at exactly. Give me a month/day/year or a unix timestamp for me to check against.

**Comment by Staine** [comment]
According to web archive, users started to question about new filenames and official respond from the owner with "Deduplication is live now and you might notice a difference in the way images are stored on the site. It shouldnt affect day-to-day usage much." happened at 08/25/16 (August 25 2016). And according to another changelog statement "8/25/2016 * Deduplication added to backend" I think this is the most accurate date I can provide.
