### ISSUE TITLE
Crash on opening thread

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#123]
```
--------- beginning of system
W/ViewRootImpl[StartActivity]: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x8, repeatCount=24, eventTime=166462321, downTime=166460645, deviceId=8, source=0x101 }
D/androidtc: Loading ModelFile { path=/data/misc/textclassifier/textclassifier.model name=textclassifier.model version=608 locales=en }
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.github.adamantcheese.chan, PID: 13573
E/AndroidRuntime: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/AndroidRuntime: 	at java.lang.String.substring(String.java:2036)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.cell.PostCell$PostIcons.setHttpIcons(PostCell.java:807)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.cell.PostCell.bindPost(PostCell.java:414)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.cell.PostCell.setPost(PostCell.java:295)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.onBindViewHolder(PostAdapter.java:108)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
E/AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
--------- beginning of main
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/mantcheese.cha: Background concurrent copying GC freed 264381(18MB) AllocSpace objects, 29(1236KB) LOS objects, 49% free, 13MB/27MB, paused 124us total 110.668ms
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/Kuroba | WatchManager: All watchers updated, removing wakelock
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/mantcheese.cha: Background concurrent copying GC freed 108213(7MB) AllocSpace objects, 86(5MB) LOS objects, 49% free, 14MB/28MB, paused 187us total 100.618ms
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/mantcheese.cha: Background concurrent copying GC freed 197860(13MB) AllocSpace objects, 25(904KB) LOS objects, 49% free, 14MB/28MB, paused 1.215ms total 107.014ms
I/Kuroba | WatchManager: All watchers updated, removing wakelock
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/mantcheese.cha: Background concurrent copying GC freed 206839(14MB) AllocSpace objects, 34(1440KB) LOS objects, 50% free, 17MB/35MB, paused 148us total 110.244ms
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/mantcheese.cha: Background concurrent copying GC freed 283995(19MB) AllocSpace objects, 40(1716KB) LOS objects, 50% free, 13MB/26MB, paused 437us total 114.815ms
I/mantcheese.cha: Background concurrent copying GC freed 166050(11MB) AllocSpace objects, 33(1912KB) LOS objects, 49% free, 14MB/28MB, paused 324us total 143.115ms
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/mantcheese.cha: Background concurrent copying GC freed 200840(13MB) AllocSpace objects, 13(540KB) LOS objects, 50% free, 15MB/30MB, paused 160us total 110.835ms
I/mantcheese.cha: Background concurrent copying GC freed 229284(15MB) AllocSpace objects, 22(1232KB) LOS objects, 49% free, 14MB/29MB, paused 122us total 100.813ms
I/mantcheese.cha: Background concurrent copying GC freed 209036(13MB) AllocSpace objects, 39(1152KB) LOS objects, 49% free, 14MB/28MB, paused 2.162ms total 163.965ms
I/mantcheese.cha: Background concurrent copying GC freed 189261(13MB) AllocSpace objects, 22(1084KB) LOS objects, 50% free, 13MB/27MB, paused 332us total 168.407ms
I/mantcheese.cha: Background concurrent copying GC freed 210752(12MB) AllocSpace objects, 33(1512KB) LOS objects, 49% free, 13MB/27MB, paused 166us total 138.712ms
I/mantcheese.cha: Background concurrent copying GC freed 130346(8MB) AllocSpace objects, 106(7MB) LOS objects, 50% free, 20MB/41MB, paused 258us total 109.607ms
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/mantcheese.cha: Background concurrent copying GC freed 339439(22MB) AllocSpace objects, 81(5MB) LOS objects, 49% free, 15MB/30MB, paused 182us total 105.333ms
I/Kuroba | WatchManager: All watchers updated, removing wakelock
I/mantcheese.cha: Background concurrent copying GC freed 187442(13MB) AllocSpace objects, 65(4MB) LOS objects, 47% free, 26MB/50MB, paused 1.656ms total 181.410ms
I/mantcheese.cha: Background concurrent copying GC freed 373370(25MB) AllocSpace objects, 159(10MB) LOS objects, 50% free, 20MB/40MB, paused 308us total 184.190ms
D/DatabaseLoadableManager: Creating loadable
D/DatabaseLoadableManager: Creating loadable
D/DatabaseLoadableManager: Creating loadable
I/mantcheese.cha: Background concurrent copying GC freed 310084(20MB) AllocSpace objects, 87(5MB) LOS objects, 49% free, 16MB/32MB, paused 441us total 133.848ms
D/DatabaseLoadableManager: Creating loadable
I/mantcheese.cha: Background concurrent copying GC freed 241734(15MB) AllocSpace objects, 37(1992KB) LOS objects, 45% free, 29MB/53MB, paused 136us total 152.369ms
D/DatabaseLoadableManager: Creating loadable
I/mantcheese.cha: Background concurrent copying GC freed 355575(23MB) AllocSpace objects, 240(15MB) LOS objects, 49% free, 14MB/28MB, paused 151us total 136.716ms
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/mantcheese.cha: Background concurrent copying GC freed 202587(12MB) AllocSpace objects, 35(1732KB) LOS objects, 49% free, 14MB/28MB, paused 285us total 117.618ms
I/mantcheese.cha: Background concurrent copying GC freed 205479(14MB) AllocSpace objects, 19(792KB) LOS objects, 49% free, 14MB/28MB, paused 1.053ms total 105.954ms
D/DatabaseLoadableManager: Creating loadable
I/mantcheese.cha: Background concurrent copying GC freed 118794(7MB) AllocSpace objects, 169(11MB) LOS objects, 49% free, 21MB/43MB, paused 370us total 111.182ms
W/System  : A resource failed to call response.body().close(). 
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.github.adamantcheese.chan, PID: 14144
E/AndroidRuntime: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/AndroidRuntime: 	at java.lang.String.substring(String.java:2036)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.cell.PostCell$PostIcons.setHttpIcons(PostCell.java:807)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.cell.PostCell.bindPost(PostCell.java:414)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.cell.PostCell.setPost(PostCell.java:295)
E/AndroidRuntime: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.onBindViewHolder(PostAdapter.java:108)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
E/AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
E/AndroidRuntime: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
E/AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/Kuroba | UNCAUGHT: 	at java.lang.String.substring(String.java:2036)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell$PostIcons.setHttpIcons(PostCell.java:807)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell.bindPost(PostCell.java:414)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell.setPost(PostCell.java:295)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.onBindViewHolder(PostAdapter.java:108)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:366)
E/Kuroba | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:397)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
I/mantcheese.cha: System.exit called, status: 999
I/AndroidRuntime: VM exiting with result code 999, cleanup skipped.
E/mantcheese.cha: Not starting debugger since process cannot load the jdwp agent.
I/mantcheese.cha: The ClassLoaderContext is a special shared library.
I/mantcheese.cha: The ClassLoaderContext is a special shared library.
I/mantcheese.cha: Waiting for a blocking GC AddRemoveAppImageSpace
I/Perf    : Connecting to perf service.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/DpmTcmClient: RegisterTcmMonitor from: $Proxy0
I/DpmTcmClient: connected to TCM
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@acc7f6a
D/OpenGLRenderer: Skia GL Pipeline
I/Adreno  : QUALCOMM build                   : 365e321, I294de8bafa
I/Adreno  : Build Date                       : 01/08/19
I/Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.02
I/Adreno  : Local Branch                     : 
I/Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.5.R1.09.00.00.464.040
I/Adreno  : Remote Branch                    : NONE
I/Adreno  : Reconstruct Branch               : NOTHING
I/Adreno  : Build Config                     : S L 6.0.7 AArch64
D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
I/Adreno  : PFP: 0x005ff110, ME: 0x005ff066
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8996.so from current namespace instead of sphal namespace.
I/mantcheese.cha: Background concurrent copying GC freed 54368(3MB) AllocSpace objects, 28(1848KB) LOS objects, 50% free, 16MB/33MB, paused 968us total 129.027ms
I/mantcheese.cha: Background concurrent copying GC freed 132420(9MB) AllocSpace objects, 252(17MB) LOS objects, 47% free, 26MB/50MB, paused 191us total 138.902ms
I/mantcheese.cha: Background concurrent copying GC freed 136194(12MB) AllocSpace objects, 522(34MB) LOS objects, 39% free, 37MB/61MB, paused 1.114ms total 162.133ms
```

**Comment by namazso** [comment]
nvm, was fixed in 8d5263865cc2032cc733e4c0cee0f256751242e1
