### ISSUE TITLE
Crash report "java.lang.IndexOutOfBoundsException: Index: 5, Size: 5"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1259]
Crash report
UUID: babdedab348c1044a295d4b3d5b95968
Build flavor: dev
Version name: v4.13.6-b0a4a24
OS info: Android 8.0.0, sdk version: 26
Report description: No title
Logs:
```
=== LOGS(May 18, 2021 4:50:43 PM UTC) ===
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
E/Kuroba-dev | UNCAUGHT: 	at java.util.ArrayList.get(ArrayList.java:437)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter$2.areItemsTheSame(PostAdapter.java:359)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.DiffUtil.diffPartial(DiffUtil.java:233)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:145)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:105)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.setThread(PostAdapter.java:332)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.showPosts(ThreadListLayout.java:280)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showPosts(ThreadLayout.java:244)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.showPosts(ThreadPresenter.java:1219)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.java:354)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$onResponseInternal$2(ChanThreadLoader.java:369)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$onResponseInternal$2$ChanThreadLoader(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.-$$Lambda$ChanThreadLoader$fZqqufCJ_gBygsof4M5FIE8P-YI.run(Unknown Source:4)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:789)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:164)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 26
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-b0a4a24
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-G935T


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by Adamantcheese** [comment]
Closed with 8eca0444b9c0bec68018f223825084feb1d32932.
