### ISSUE TITLE
Crash report "android.util.AndroidRuntimeException: Animators may only be run on Looper threads"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1273]
Crash report
UUID: 47fcd6b213812e42c105f27361959b40
Build flavor: dev
Version name: v4.13.6-15b58fd
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(24 May 2021 4:33:58 am UTC) ===
D/Kuroba-dev | Dependency Injection: Site repository
D/Kuroba-dev | Dependency Injection: Board repository
D/Kuroba-dev | Dependency Injection: Board manager
D/Kuroba-dev | Dependency Injection: Report manager
D/Kuroba-dev | SiteModel: Config: null, Settings: {"settings":{}}
D/Kuroba-dev | Dependency Injection: Database loadable manager
D/Kuroba-dev | Dependency Injection: Site resolver
D/Kuroba-dev | Dependency Injection: Database pin manager
D/Kuroba-dev | Dependency Injection: Wake manager
D/Kuroba-dev | Dependency Injection: Watch manager
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
D/Kuroba-dev | Dependency Injection: Android10GesturesExclusionZonesHolder
D/Kuroba-dev | Android10GesturesExclusionZonesHolder: Json setting string is empty, reset.
D/Kuroba-dev | Dependency Injection: Database hide manager
D/Kuroba-dev | Dependency Injection: Database saved reply manager
D/Kuroba-dev | Dependency Injection: Database filter manager
D/Kuroba-dev | Dependency Injection: Filter engine
D/Kuroba-dev | Dependency Injection: Filter watch manager
D/Kuroba-dev | WakeManager: Alarm trigger @ 24 May 2021 12:32:19 pm
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got new challenge
D/Kuroba-dev | CaptchaV2NoJsPresenter: Verify called
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got the verification token
D/Kuroba-dev | CaptchaTokenHolder: New token added, validCount = 1, token = validUntil = 2021-05-24 12:35:15, token = 03AGdBqâ€¦Z72PAELg
D/Kuroba-dev | CaptchaTokenHolder: Timer started
D/Kuroba-dev | CaptchaTokenHolder: Got token validUntil = 2021-05-24 12:35:15, token = 03AGdBqâ€¦Z72PAELg
D/Kuroba-dev | ReplyLayout: Switching to page LOADING
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
E/Kuroba-dev | UNCAUGHT: 	at android.animation.AnimatorSet.start(AnimatorSet.java:705)
E/Kuroba-dev | UNCAUGHT: 	at android.animation.AnimatorSet.start(AnimatorSet.java:684)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onPosted(ReplyLayout.java:686)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:302)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:76)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:378)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:375)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.http.HttpCall.onResponse(HttpCall.java:67)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-15b58fd
E/Kuroba-dev | UNCAUGHT: Phone Model: vivo V2026
D/Kuroba-dev | ReportManager: Stored new crash log, path = /data/user/0/com.github.adamantcheese.chan.dev/cache/crashlogs/crashlog_1621830798068.txt
D/Kuroba-dev | Dependency Injection: Database helper
D/Kuroba-dev | Dependency Injection: Database board manager
D/Kuroba-dev | Dependency Injection: Database site manager
D/Kuroba-dev | Dependency Injection: Site repository
D/Kuroba-dev | Dependency Injection: Board repository
D/Kuroba-dev | Dependency Injection: Board manager
D/Kuroba-dev | Dependency Injection: Report manager
D/Kuroba-dev | SiteModel: Config: null, Settings: {"settings":{}}
D/Kuroba-dev | Dependency Injection: Database loadable manager
D/Kuroba-dev | Dependency Injection: Site resolver
D/Kuroba-dev | Dependency Injection: Database pin manager
D/Kuroba-dev | Dependency Injection: Wake manager
D/Kuroba-dev | Dependency Injection: Watch manager
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
D/Kuroba-dev | Dependency Injection: Android10GesturesExclusionZonesHolder
D/Kuroba-dev | Android10GesturesExclusionZonesHolder: Json setting string is empty, reset.
D/Kuroba-dev | Dependency Injection: Database hide manager
D/Kuroba-dev | Dependency Injection: Database saved reply manager
D/Kuroba-dev | Dependency Injection: Database filter manager
D/Kuroba-dev | Dependency Injection: Filter engine
D/Kuroba-dev | Dependency Injection: Filter watch manager
D/Kuroba-dev | WakeManager: Alarm trigger @ 24 May 2021 12:33:25 pm
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got new challenge
D/Kuroba-dev | CaptchaV2NoJsPresenter: Verify called
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got the verification token
D/Kuroba-dev | CaptchaTokenHolder: New token added, validCount = 1, token = validUntil = 2021-05-24 12:35:55, token = 03AGdBqâ€¦1QinZU3w
D/Kuroba-dev | CaptchaTokenHolder: Timer started
D/Kuroba-dev | CaptchaTokenHolder: Got token validUntil = 2021-05-24 12:35:55, token = 03AGdBqâ€¦1QinZU3w
D/Kuroba-dev | ReplyLayout: Switching to page LOADING
E/Kuroba-dev | ReplyPresenter: onPostComplete error
D/Kuroba-dev | ReplyLayout: Switching to page INPUT
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
E/Kuroba-dev | UNCAUGHT: 	at android.animation.AnimatorSet.cancel(AnimatorSet.java:412)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.LoadView.setView(LoadView.java:96)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.LoadView.setView(LoadView.java:83)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.setPage(ReplyLayout.java:529)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:537)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:528)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:339)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:76)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:378)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:375)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.http.HttpCall.onResponse(HttpCall.java:67)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-15b58fd
E/Kuroba-dev | UNCAUGHT: Phone Model: vivo V2026


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
```
Crash report
UUID: 9e4522c294ee591604c029628f428c99
Build flavor: dev
Version name: v4.13.6-15b58fd
OS info: Android 8.0.0, sdk version: 26
Report description: No title
Logs:
=== LOGS(May 23, 2021 11:44:43 PM UTC) ===
D/Kuroba-dev | WakeManager: Alarm trigger @ May 23, 2021 4:44:21 PM
D/Kuroba-dev | WakeManager: Early; previous @ May 23, 2021 4:34:31 PM
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got new challenge
D/Kuroba-dev | ReplyLayout: Switching to page INPUT
D/Kuroba-dev | WakeManager: Alarm trigger @ May 23, 2021 4:44:31 PM
D/Kuroba-dev | WakeManager: Early; previous @ May 23, 2021 4:34:31 PM
D/Kuroba-dev | ReplyLayout: Switching to page AUTHENTICATION
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got new challenge
D/Kuroba-dev | CaptchaV2NoJsPresenter: Verify called
D/Kuroba-dev | CaptchaV2NoJsPresenter: Got the verification token
D/Kuroba-dev | CaptchaTokenHolder: New token added, validCount = 1, token = validUntil = 2021-05-23 16:46:40, token = 03AGdBqâ€¦SkXnFQpQ
D/Kuroba-dev | CaptchaTokenHolder: Timer started
D/Kuroba-dev | CaptchaTokenHolder: Got token validUntil = 2021-05-23 16:46:40, token = 03AGdBqâ€¦SkXnFQpQ
D/Kuroba-dev | ReplyLayout: Switching to page LOADING
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8525)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1427)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.requestLayout(View.java:23221)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5541)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.highlightPostNo(PostAdapter.java:416)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.highlightPostNo(ThreadListLayout.java:524)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.highlightPostNo(ReplyLayout.java:902)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.highlightQuotes(ReplyPresenter.java:588)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSelectionChanged(ReplyPresenter.java:415)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onSelectionChanged(ReplyLayout.java:907)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.SelectionListeningEditText.onSelectionChanged(SelectionListeningEditText.java:67)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.TextView.spanChange(TextView.java:10846)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:14132)
E/Kuroba-dev | UNCAUGHT: 	at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:1272)
E/Kuroba-dev | UNCAUGHT: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:773)
E/Kuroba-dev | UNCAUGHT: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
E/Kuroba-dev | UNCAUGHT: 	at android.text.Selection.setSelection(Selection.java:78)
E/Kuroba-dev | UNCAUGHT: 	at android.text.Selection.setSelection(Selection.java:87)
E/Kuroba-dev | UNCAUGHT: 	at android.text.method.ArrowKeyMovementMethod.initialize(ArrowKeyMovementMethod.java:337)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.TextView.setText(TextView.java:5991)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.TextView.setText(TextView.java:5849)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.EditText.setText(EditText.java:138)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.TextView.setText(TextView.java:5806)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.loadDraftIntoViews(ReplyLayout.java:595)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:301)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:76)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:378)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:375)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.http.HttpCall.onResponse(HttpCall.java:67)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 26
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-15b58fd
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-G935T
```

**Comment by K1rakishou** [comment]
```
Crash report
UUID: 82530bf3cce58d617066559f9cd77306
Build flavor: dev
Version name: v4.13.6-15b58fd
OS info: Android 11, sdk version: 30
Report description: No title
Logs:
=== LOGS(May 24, 2021 7:24:47 AM UTC) ===
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to BACKGROUND
D/Kuroba-dev | WakeManager: Registered class com.github.adamantcheese.chan.core.manager.WatchManager
I/Kuroba-dev | WakeManager: Started background alarm with an interval of 2 minutes
D/Kuroba-dev | WakeManager: Alarm trigger @ May 24, 2021 02:23:57
D/Kuroba-dev | WakeManager: Early; previous @ May 24, 2021 02:22:24
D/Kuroba-dev | WakeManager: Alarm trigger @ May 24, 2021 02:23:59
D/Kuroba-dev | WakeManager: Early; previous @ May 24, 2021 02:22:24
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
I/Kuroba-dev | WakeManager: Stopped background alarm
D/Kuroba-dev | WatchManager: Setting interval type from BACKGROUND to FOREGROUND
D/Kuroba-dev | ReplyLayout: Switching to page LOADING
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.IllegalStateException: Cannot be executed on a background thread!
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.BackgroundUtils.ensureMainThread(BackgroundUtils.java:98)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.manager.WatchManager.updateState(WatchManager.java:504)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.manager.WatchManager.updateState(WatchManager.java:498)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.manager.WatchManager.createPin(WatchManager.java:190)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.manager.WatchManager.createPin(WatchManager.java:161)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.manager.WatchManager.createPin(WatchManager.java:155)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:277)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSuccess(ReplyPresenter.java:76)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:378)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.sites.chan4.Chan4$3$2.onSuccess(Chan4.java:375)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.http.HttpCall.onResponse(HttpCall.java:67)
E/Kuroba-dev | UNCAUGHT: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba-dev | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:923)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 30
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-15b58fd
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-N975U


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Pictures, SAF location: , active: Java API
Phone layout mode: SLIDE
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by ghost** [comment]
That last one was mine, I'm crashing every time I try to post a reply
