### ISSUE TITLE
reCATCHPA v2 no longer supported

### ISSUE THREAD

**Issue by ConesTheCat** [Adamantcheese/Kuroba#1296]
![Screenshot_20210705-185214_Clover](https://user-images.githubusercontent.com/83641358/124522873-06e2e500-de38-11eb-94cb-dd334915bc57.jpg)

Unable to post after completing reCAPTCHPA on 4chan boards

**Comment by ZenythFactor** [comment]
Side note that this is due to new captcha that's been added.
Hopefully we get this supported soon.

**Comment by ghost** [comment]
Sucks, since the app logs me out of my pass all the time

**Comment by K1rakishou** [comment]
new captcha slider
UUID: 922cd134b365bca4b559c398135b18b0
Build flavor: dev
Version name: v4.13.6-3c82f2b
OS info: Android 11, sdk version: 30
Report description: size of overlying image and size of underlying sliding image are mismatched so the images will never overly such that the captcha is readable

**Comment by Astridchan** [comment]
^ Can confirm above. An anon posted a workaround: turn phone in landscape and then the sliding and static parts are scaled properly and you can read the captcha successfully.

**Comment by K1rakishou** [comment]
The CAPTCHA slider sometimes doesn't appear
UUID: 28e6cbbc8ff5f026c1671f6b7501b179
Build flavor: dev
Version name: v4.13.6-350665f
OS info: Android 10, sdk version: 29
Report description: Seemingly randomly the slider will not appear with the CAPTCHA, making it impossible to complete it - this sometimes happens after a refresh, and in portrait/landscape mode.

**Comment by K1rakishou** [comment]
I guess this is related somehow.

```
E/Kuroba-dev | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.captcha.CustomJsonLayout.onSuccess(CustomJsonLayout.java:181)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.captcha.CustomJsonLayout.onSuccess(CustomJsonLayout.java:29)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.net.NetUtilsClasses$MainThreadResponseResult.lambda$onSuccess$1(NetUtilsClasses.java:98)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.net.NetUtilsClasses$MainThreadResponseResult.lambda$onSuccess$1$NetUtilsClasses$MainThreadResponseResult(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.net.-$$Lambda$NetUtilsClasses$MainThreadResponseResult$FcopCX-oZZKaXdhZS2aIiHSHngU.run(Unknown Source:4)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:938)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:246)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Astridchan** [comment]
Any plans to add support for this?

![Untitled](https://user-images.githubusercontent.com/40862101/125172485-ae5a7180-e1c2-11eb-9d69-df36f5641660.png)

**Comment by Adamantcheese** [comment]
noop captchas are already supported. And that crash log corresponds to commit b58b7c, which was with #1300.

**Comment by Astridchan** [comment]
>noop captchas are already supported.

Really? I am getting a sliding captcha on 100% posts with Kuroba, I've never had it not require one. I just did two test posts on the desktop website and the second one already didn't require a captcha.

**Comment by Adamantcheese** [comment]
Whatever the site is doing with the captcha request is beyond me. I do know that the 4chan_pass cookie seems to be the culprit between getting sliding and non-sliding captchas at the very least, but all that should be handled transparently now that OkHttp is handling all of the cookies without my intervention.

**Comment by Astridchan** [comment]
I gave KurobaEX a try and that gave me "no verification required" on the first post, there must be something that app is doing that Kuroba isn't?

**Comment by Adamantcheese** [comment]
Dunno. Kuroba-Ex is manually handling the cookie which is why it might be working.

**Comment by K1rakishou** [comment]
I'm adding that cookie to the getCaptcha request and to the reply request (probably not necessary but just in case).

**Comment by K1rakishou** [comment]
says capcha expired no matter which thread i post in. cast post anymore
UUID: d88ba183689c4619ff25c123eced340f
Build flavor: dev
Version name: v4.13.6-063107c
OS info: Android 8.1.0, sdk version: 27

**Comment by K1rakishou** [comment]
I think this might be happening because 4chan and 4channel are supposed to have separate cookies. At least that's how it is in the browser.

**Comment by K1rakishou** [comment]
Filling out new captcha
UUID: 21db0468648527920c87e72dc83799e8
Build flavor: dev
Version name: v4.13.6-063107c
OS info: Android 11, sdk version: 30
Report description: Halfway through solving an already requested captcha, the captcha sometimes unpredictably force cancels and then a captcha cooldown toast notification appears

**Comment by K1rakishou** [comment]
Crash when entering captcha in landscape mode
UUID: 1c98107673b690ed5d6e85fbf8d98b39
Build flavor: dev
Version name: v4.13.6-063107c
OS info: Android 11, sdk version: 30
Report description: >Be in landscape
>Request captcha
>Open text field entry
>Type captcha
>Press "Done"
>App crashes to home

**Comment by K1rakishou** [comment]
error/bug when trying to post
UUID: 49342c1509e520b46774940d2ccee01e
Build flavor: dev
Version name: v4.13.6-063107c
OS info: Android 10, sdk version: 29
Report description: kuroba just go straight to sending a reply post without showing the captcha fill screen which results in an error that said "captcha is no longer valid beacuse it is expired'"

**Comment by K1rakishou** [comment]
So as it turns out

>"captcha is no longer valid beacuse it is expired'"

happens because there should be 2 separate cookies for 4chan/4channel.
I also noticed that for posting "sys.4chan.org" endpoint is always used which may be the reason why cookies are applied incorrectly in case of regular Kuroba. I've also split them in two separate endpoint "sys.4chan.org" and "sys.4channel.org" and it started working as expected.

**Comment by Adamantcheese** [comment]
Yeah I was figuring it was that 4chan_pass cookie being different on the two domains from my testing as well since when I changed from a sfw board to an nsfw one I went from no verification needed to a slider again. Guess I can probably use the worksafe field to switch the domain for the sys stuff; will test tomorrow.

**Comment by Spokes66** [comment]
How do I get the new captcha on mimi app? Do I need to re-download the app? It keeps giving me the captcha error. I'm an idiot so I need help switching to the new captcha

**Comment by ConesTheCat** [comment]
@Spokes66 

Download the latest Dev build APK and install it.  Backup your settings and boards from the stable build and import it into the dev build

https://github.com/Adamantcheese/Kuroba-Dev/releases/tag/v4.13.6-063107cb

**Comment by Adamantcheese** [comment]
> 
> 
> How do I get the new captcha on mimi app? Do I need to re-download the app? It keeps giving me the captcha error. I'm an idiot so I need help switching to the new captcha

@Spokes66 assuming you're talking about mimi, you're in the wrong place. Different app entirely.
If you want Kuroba-Dev, then yeah grab it from https://github.com/Adamantcheese/Kuroba-Dev/releases/latest

**Comment by K1rakishou** [comment]
captcha
UUID: 372a395680241b020dff1162ff85be11
Build flavor: dev
Version name: v4.13.6-1d48096
OS info: Android 9, sdk version: 28
Report description: there are random "cant initialize captcha" popups. seems like its trying to get captcha in the background even when I'm not posting anything.

**Comment by Astridchan** [comment]
The "No verification required" (noop) captcha was working earlier but now on the later builds it seems to have stopped appearing again, only got the regular slider and sliderless captchas for 20-30 posts (generally you only need to do 1-2 regular captchas to start getting the no verification ones). 1d480963 seems to be the last available Dev build where the noop captcha still works.

**Comment by ghost** [comment]
When will we be able to post comments? It's almost 3 months since the rollout of the new reCAPTCHA and Kuroba still doesnt suppprt it...

**Comment by Adamantcheese** [comment]
See #1302. If you want to use it, use the development branch.

**Comment by c933103** [comment]
> See #1302. If you want to use it, use the development branch.

Any plan to push it to stable release now that more than half year passed?
