### ISSUE TITLE
Crash report " android.content.res.Resources$NotFoundException: String resource ID #0x0"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#1334]
Crash report
UUID: 699527c46de556df017d079a2a8a3bee
Build flavor: dev
Version name: v4.13.6-3e9528b
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
=== LOGS(August 5, 2021 6:02:28 AM UTC) ===
```
D/Kuroba-dev | Dependency Injection: Database loadable manager
D/Kuroba-dev | Dependency Injection: Site resolver
D/Kuroba-dev | Dependency Injection: Database filter manager
D/Kuroba-dev | Dependency Injection: Filter engine
D/Kuroba-dev | Dependency Injection: Database pin manager
D/Kuroba-dev | Dependency Injection: Watch manager
D/Kuroba-dev | Dependency Injection: Filter watch manager
D/Kuroba-dev | Dependency Injection: Database hide manager
D/Kuroba-dev | Dependency Injection: Database saved reply manager
D/Kuroba-dev | WatchManager: No active pins found, unregistering for wake
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='g', no=82783XXX', listViewIndex=172, listViewTop=-237, lastViewed=82819XXX, lastLoaded=82819XXX, markedNo=-1}
D/Kuroba-dev | PinWatcher: created for Loadable{mode=0, board='g', no=82813XXX', listViewIndex=41, listViewTop=-363, lastViewed=82822XXX, lastLoaded=82822XXX, markedNo=-1}
D/Kuroba-dev | Android10GesturesExclusionZonesHolder: Screen sizes do not match! oldMinScreenSize = 0, currentMinScreenSize = 1080, oldMaxScreenSize = 0, currentMaxScreenSize = 2340
D/Kuroba-dev | Android10GesturesExclusionZonesHolder: All zones reset
D/Kuroba-dev | BoardRepository: updateAvailableBoardsForSite changed = false
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: android.content.res.Resources$NotFoundException: String resource ID #0x0
E/Kuroba-dev | UNCAUGHT: 	at android.content.res.Resources.getText(Resources.java:381)
E/Kuroba-dev | UNCAUGHT: 	at android.content.res.MiuiResources.getText(MiuiResources.java:97)
E/Kuroba-dev | UNCAUGHT: 	at android.content.Context.getText(Context.java:635)
E/Kuroba-dev | UNCAUGHT: 	at com.google.android.material.snackbar.Snackbar.setAction(Snackbar.java:270)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.buildCommonSnackbar(AndroidUtils.java:532)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.buildCommonSnackbar(AndroidUtils.java:540)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BoardSetupController.boardsWereAdded(BoardSetupController.java:192)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.BoardSetupPresenter.onAddDialogPositiveClicked(BoardSetupPresenter.java:130)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.BoardAddLayout.onPositiveClicked(BoardAddLayout.java:114)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BoardSetupController.lambda$showAddDialog$0(BoardSetupController.java:163)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$BoardSetupController$h9GukUOG2ZORy1-E8al37L0DREk.onClick(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:225)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7564)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.13.6-3e9528b
E/Kuroba-dev | UNCAUGHT: Phone Model: Xiaomi Redmi Note 8


=== SETTINGS ===
Prefetching enabled: false
Embedding enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Phone layout mode: AUTO
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by Adamantcheese** [comment]
Closed with fa713aa.
