### ISSUE TITLE
App occasionally crashes on startup

### ISSUE THREAD

**Issue by Twinov** [Adamantcheese/Kuroba#1447]
Sometimes I have a crash on startup, maybe related to the fix in 2d5f77b

captured a stack trace: 
```
E/Kuroba-dev | UNCAUGHT: Unhandled exception:
E/Kuroba-dev | UNCAUGHT: java.lang.RuntimeException: java.lang.IllegalStateException: message == null
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.utils.BackgroundUtils.lambda$runWithExecutor$3(BackgroundUtils.java:129)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.utils.BackgroundUtils.$r8$lambda$pNU0C8CWI4bwVEA5oO2zwmNxvMc(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.utils.BackgroundUtils$$ExternalSyntheticLambda1.run(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT:  at android.os.Handler.handleCallback(Handler.java:942)
E/Kuroba-dev | UNCAUGHT:  at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba-dev | UNCAUGHT:  at android.os.Looper.loopOnce(Looper.java:201)
E/Kuroba-dev | UNCAUGHT:  at android.os.Looper.loop(Looper.java:288)
E/Kuroba-dev | UNCAUGHT:  at android.app.ActivityThread.main(ActivityThread.java:7884)
E/Kuroba-dev | UNCAUGHT:  at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/Kuroba-dev | UNCAUGHT:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/Kuroba-dev | UNCAUGHT: Caused by: java.lang.IllegalStateException: message == null
E/Kuroba-dev | UNCAUGHT:  at okhttp3.Response$Builder.build(Response.kt:326)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.core.net.NetUtilsClasses$NullCall.execute(NetUtilsClasses.java:377)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.core.net.NetUtilsClasses$NullCall.lambda$enqueue$0(NetUtilsClasses.java:362)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.core.net.NetUtilsClasses$NullCall.$r8$lambda$eCsh4UsNtPorZmvx37B5pGJLb5g(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.core.net.NetUtilsClasses$NullCall$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/Kuroba-dev | UNCAUGHT:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.utils.BackgroundUtils.lambda$runWithExecutor$4(BackgroundUtils.java:121)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.utils.BackgroundUtils.$r8$lambda$9rYhI88R5umxXjUeRlJcaj1Psyk(Unknown Source:0)
E/Kuroba-dev | UNCAUGHT:  at com.github.adamantcheese.chan.utils.BackgroundUtils$$ExternalSyntheticLambda4.run(Unknown Source:6)
E/Kuroba-dev | UNCAUGHT:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/Kuroba-dev | UNCAUGHT:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/Kuroba-dev | UNCAUGHT:  at java.lang.Thread.run(Thread.java:1012)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 33
E/Kuroba-dev | UNCAUGHT: App Version: Kuroba-dev/v4.13.6-3b38cf65
E/Kuroba-dev | UNCAUGHT: Phone Model: Google Pixel 6 Pro
```

**Comment by lewri** [comment]
You may be better off now forking [K1rakishou/Kuroba-Experimental](https://github.com/K1rakishou/Kuroba-Experimental) (also appears to have become inactive) and starting from there if you wished to commit into the Kuroba system (though experimental is now a public archive, the whole release process would need taking over on a fork).

As far as I can tell, the last 'stable' release of Experimental runs everything more or less except the new Captcha changes with the auto-solver.
