### ISSUE TITLE
Crash on downloading image

### ISSUE THREAD

**Issue by ownBard** [Adamantcheese/Kuroba#171]
```I/Kuroba | WatchManager: Acquiring wakelock for pin watcher updates
I/Kuroba | WatchManager: All watchers updated, removing wakelock
W/Kuroba | CustomScaleImageView: onImageLoadError
W/Kuroba | CustomScaleImageView: java.io.IOException: Image format not supported
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
W/Kuroba | CustomScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/Kuroba | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | UNCAUGHT: android.app.RemoteServiceException: Bad notification for startForeground: java.util.ConcurrentModificationException
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1802)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:164)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6696)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 26
E/Kuroba | UNCAUGHT: App Version: v4.4.1-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Xiaomi MI 5
```
I tried downloading the same image after the crash and it worked fine that time.

**Comment by Adamantcheese** [comment]
I have no idea why that would be the case, but I guess I can just wrap the function in a synchronized block to see if that fixes it. Kinda hard to debug with that stack trace.
