### ISSUE TITLE
[Bug] Thread archiver crashes Kuroba upon entering an archived thread

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#242]
```
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.HttpUrl.toString()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.java:553)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$onResponseInternalNext$8$ChanThreadLoader(ChanThreadLoader.java:414)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.-$$Lambda$ChanThreadLoader$Np7-je8HyUhyZD2imS4IWq0Mg9w.run(lambda)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.HttpUrl.toString()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.java:553)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$onResponseInternalNext$8$ChanThreadLoader(ChanThreadLoader.java:414)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.-$$Lambda$ChanThreadLoader$Np7-je8HyUhyZD2imS4IWq0Mg9w.run(lambda)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.HttpUrl.toString()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.java:553)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.quickLoad(ChanThreadLoader.java:228)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.requestInitialData(ThreadPresenter.java:288)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.loadThread(ViewThreadController.java:365)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.loadThread(ViewThreadController.java:372)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.openPin(ViewThreadController.java:255)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.DrawerController.onPinClicked(DrawerController.java:148)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.DrawerAdapter$PinViewHolder.lambda$new$0$DrawerAdapter$PinViewHolder(DrawerAdapter.java:411)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.adapter.-$$Lambda$DrawerAdapter$PinViewHolder$l3d0rxXc6rQSgHLyEBulCi5pH40.onClick(lambda)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClick(View.java:5637)
E/Kuroba | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:22433)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
```

**Comment by K1rakishou** [comment]
Can you upload the thread files? At least the json file?

**Comment by floppyD** [comment]
Sure
[72053196.zip](https://github.com/Adamantcheese/Kuroba/files/3437897/72053196.zip)

**Comment by K1rakishou** [comment]
Try turning off the media prefetcher.

**Comment by floppyD** [comment]
Nice, it works now.

**Comment by K1rakishou** [comment]
For now turn off media prefetcher when viewing local threads. Fix is probably gonna be released by the end of the next week.
