### ISSUE TITLE
[Bug] Trying to open a 404'd thread in the browser = crash

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#245]
```
E/Kuroba | ChanThreadLoader: Could not find savedThread for loadable Loadable{id=147, mode=0, board='g', no=72062332, title='/g/ –  ', listViewIndex=3, listViewTop=-411, lastViewed=72062533, lastLoaded=72062571, markedNo=-1, dirty=false}
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.ServerError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:160)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to read from field 'com.github.adamantcheese.chan.core.model.orm.Loadable com.github.adamantcheese.chan.core.model.ChanThread.loadable' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showPosts(ThreadLayout.java:269)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.showPosts(ThreadPresenter.java:1117)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onListScrolledToBottom(ThreadPresenter.java:623)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.lambda$onRecyclerViewScrolled$0$ThreadListLayout(ThreadListLayout.java:164)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.-$$Lambda$ThreadListLayout$wCwyHJXO34_chrEhTvPk0rZTQGs.run(lambda)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
E/Kuroba | ChanThreadLoader: Could not find savedThread for loadable Loadable{id=147, mode=0, board='g', no=72062332, title='/g/ –  ', listViewIndex=3, listViewTop=-411, lastViewed=72062533, lastLoaded=72062571, markedNo=-1, dirty=false}
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.ServerError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:160)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
E/Kuroba | ChanThreadLoader: Could not find savedThread for loadable Loadable{id=147, mode=0, board='g', no=72062332, title='/g/ –  ', listViewIndex=3, listViewTop=-411, lastViewed=72062533, lastLoaded=72062571, markedNo=-1, dirty=false}
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.ServerError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:160)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to read from field 'com.github.adamantcheese.chan.core.model.Post com.github.adamantcheese.chan.core.model.ChanThread.op' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.openBrowserClicked(ViewThreadController.java:217)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.lambda$o-CwPWLy2eMgbzWL_dxn1OdXi58(ViewThreadController.java)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ViewThreadController$o-CwPWLy2eMgbzWL_dxn1OdXi58.clicked(lambda)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuSubItem.performClick(ToolbarMenuSubItem.java:56)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem$1.onFloatingMenuItemClicked(ToolbarMenuItem.java:165)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.FloatingMenu.lambda$show$0$FloatingMenu(FloatingMenu.java:162)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.-$$Lambda$FloatingMenu$jV5QSfy78m7c72btfnW0eJNDsgo.onItemClick(lambda)
E/Kuroba | UNCAUGHT: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView$3.run(AbsListView.java:4054)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
E/Kuroba | ChanThreadLoader: Could not find savedThread for loadable Loadable{id=147, mode=0, board='g', no=72062332, title='/g/ –  ', listViewIndex=3, listViewTop=-411, lastViewed=72062533, lastLoaded=72062571, markedNo=-1, dirty=false}
I/Kuroba | ChanThreadLoader: Loading error
I/Kuroba | ChanThreadLoader: com.android.volley.ServerError
I/Kuroba | ChanThreadLoader: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:160)
I/Kuroba | ChanThreadLoader: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:106)
```

**Comment by K1rakishou** [comment]
And after https://github.com/Adamantcheese/Kuroba/issues/244#issuecomment-515668941 you tried to open it in the browser, right?

**Comment by floppyD** [comment]
Exactly. Even after relaunching Kuroba it didn't work.

**Comment by floppyD** [comment]
I still have it bookmarked, and trying to open in the browser still triggers the crash.

**Comment by K1rakishou** [comment]
Wait a minute. You are still able to view it even though it got 404ed? And it's not a downloaded thread, right?

**Comment by floppyD** [comment]
No, just this page. And yes, not a downloaded thread.
![Screenshot_20190727-145557](https://user-images.githubusercontent.com/29208110/61997912-c2ad0e80-b07e-11e9-8f92-5880c34252c9.png)

**Comment by ayy91** [comment]
It seems that pressing Share and View removed posts in a 404'd thread also crash the app.
