### ISSUE TITLE
Crash on X button-click in filters settings

### ISSUE THREAD

**Issue by inshiro** [Adamantcheese/Kuroba#269]
App crashes on X button-click in filters settings.
* Have atleast 3 filters
* All look like this format: `*word*`
* Disable one of them
* Press X button
> **Crash**

```ruby
E/Kuroba | FilterEngine: Invalid pattern
E/Kuroba | FilterEngine: Invalid pattern
E/Kuroba | Chan4: Failed to get threads for board biz
E/Kuroba | Chan4: Failed to get threads for board biz
E/Kuroba | Chan4: Failed to get threads for board biz
E/Kuroba | Chan4: Failed to get threads for board biz
E/Kuroba | Chan4: Failed to get threads for board biz
E/Kuroba | Chan4: Failed to get threads for board biz
E/Kuroba | FilterEngine: Invalid pattern
E/Kuroba | FilterEngine: Invalid pattern
E/Kuroba | FilterEngine: Invalid pattern
E/Kuroba | UNCAUGHT: java.util.ConcurrentModificationException
E/Kuroba | UNCAUGHT: 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.FiltersController.setFilters(FiltersController.java:179)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.FiltersController.onClick(FiltersController.java:170)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClick(View.java:6597)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClickInternal(View.java:6574)
E/Kuroba | UNCAUGHT: 	at android.view.View.access$3100(View.java:778)
E/Kuroba | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:25906)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Google Pixel
E/Kuroba | UNCAUGHT: java.util.ConcurrentModificationException
E/Kuroba | UNCAUGHT: 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.FiltersController.setFilters(FiltersController.java:179)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.FiltersController.onClick(FiltersController.java:170)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClick(View.java:6597)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClickInternal(View.java:6574)
E/Kuroba | UNCAUGHT: 	at android.view.View.access$3100(View.java:778)
E/Kuroba | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:25906)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.5.3-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Google Pixel
```
Here's some more logs produced while I was debugging to reproduce this. https://del.dog/abedofufog

**Comment by Adamantcheese** [comment]
Fixed as of https://github.com/Adamantcheese/Kuroba/commit/5c4abda76194763a86ae0e7d0a720c9e261d689d
