### ISSUE TITLE
[BUG] Crash when checking for upadate on Android 5.0

### ISSUE THREAD

**Issue by ugaugabuga** [Adamantcheese/Kuroba#321]
Log:

```
E/Kuroba | UNCAUGHT: java.lang.NoClassDefFoundError: com.vladsch.flexmark.util.data.-$$Lambda$DataKey$w70X360D_iPjvPHPy0X-Au2N8lo
E/Kuroba | UNCAUGHT: 	at com.vladsch.flexmark.util.data.DataKey.<init>(DataKey.java:34)
E/Kuroba | UNCAUGHT: 	at com.vladsch.flexmark.ext.gfm.issues.GfmIssuesExtension.<clinit>(GfmIssuesExtension.java:22)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.net.UpdateApiRequest.readJson(UpdateApiRequest.java:92)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.net.UpdateApiRequest.readJson(UpdateApiRequest.java:39)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.net.JsonReaderRequest.parseNetworkResponse(JsonReaderRequest.java:59)
E/Kuroba | UNCAUGHT: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:117)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 21
E/Kuroba | UNCAUGHT: App Version: v4.6.0-dev Official
E/Kuroba | UNCAUGHT: Phone Model: LENOVO Lenovo A1000

**Comment by Adamantcheese** [comment]
Weird. It's meant for linkifying stuff in the update log but since the generated stuff isn't clickable anyways I'll just remove it.

**Comment by ugaugabuga** [comment]
I forgot to add that checking for update works perfectly fine on my Android 7.0

**Comment by ghost** [comment]
Crashes on Android 6, too.

**Comment by Adamantcheese** [comment]
Weird as hell. Anyways, that extension is being removed so this shouldn't be a problem in the next update. You will have to manually update however.
