### ISSUE TITLE
[BUG] App crashes whenever app is closed

### ISSUE THREAD

**Issue by TacoTheDank** [Adamantcheese/Kuroba#340]
I've dealt with some crashes for a while but they don't really bother me. I figured I might as well submit them so they can be fixed.

Phone is Samsung Note 9 running Android Pie.

```
FATAL EXCEPTION: main
Process: com.github.adamantcheese.chan, PID: 32542
java.lang.RuntimeException: Unable to create application com.github.adamantcheese.chan.Chan: org.codejargon.feather.FeatherException: Can't instantiate com.github.adamantcheese.chan.core.manager.FilterWatchManager with provider
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6167)
	at android.app.ActivityThread.access$1200(ActivityThread.java:235)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: org.codejargon.feather.FeatherException: Can't instantiate com.github.adamantcheese.chan.core.manager.FilterWatchManager with provider
	at org.codejargon.feather.Feather$3.get(Feather.java:131)
	at org.codejargon.feather.Feather$4.get(Feather.java:147)
	at org.codejargon.feather.Feather.instance(Feather.java:50)
	at com.github.adamantcheese.chan.Chan.onCreate(Chan.java:102)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6162)
	... 8 more
Caused by: org.codejargon.feather.FeatherException: Can't instantiate com.github.adamantcheese.chan.core.manager.WatchManager with provider
	at org.codejargon.feather.Feather$3.get(Feather.java:131)
	at org.codejargon.feather.Feather$4.get(Feather.java:147)
	at org.codejargon.feather.Feather$5.get(Feather.java:179)
	at org.codejargon.feather.Feather.params(Feather.java:198)
	at org.codejargon.feather.Feather.access$000(Feather.java:9)
	at org.codejargon.feather.Feather$3.get(Feather.java:129)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at org.codejargon.feather.Feather$3.get(Feather.java:129)
	... 18 more
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.adamantcheese.chan/.ui.service.WatchNotification }: app is in background uid UidRecord{81a4007 u0a688 SVC  idle change:idle|uncached procs:1 proclist:32542, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
	at android.app.ContextImpl.startService(ContextImpl.java:1611)
	at android.content.ContextWrapper.startService(ContextWrapper.java:677)
	at com.github.adamantcheese.chan.core.manager.WatchManager.updateState(WatchManager.java:678)
	at com.github.adamantcheese.chan.core.manager.WatchManager.updateState(WatchManager.java:657)
	at com.github.adamantcheese.chan.core.manager.WatchManager.<init>(WatchManager.java:173)
	at com.github.adamantcheese.chan.core.di.ManagerModule.provideWatchManager(ManagerModule.java:87)
	... 20 more
```

**Comment by Adamantcheese** [comment]
This should be fixed as of https://github.com/Adamantcheese/Kuroba/commit/03adc483f7fcc6d0ba5c8ea2e935c8fbaccfb949; I've updated the changelogs for v4.8.0 and v4.8.1 to include this.

**Comment by Adamantcheese** [comment]
Upon secondary inspection, this is because of the whole Android changing its notifications stuff again. Clover's already moved over to it, so I suppose I should do that as well, using it as an example.

**Comment by Adamantcheese** [comment]
This should be resolved as of some recent updates for Android 10.
