### ISSUE TITLE
Crash when closing image

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#345]
```
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.github.adamantcheese.chan.core.model.orm.Loadable.isThreadMode()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell.bindPost(PostCell.java:323)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell.setPost(PostCell.java:298)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.PostRepliesController$1.getView(PostRepliesController.java:150)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView.obtainView(AbsListView.java:2366)
E/Kuroba | UNCAUGHT: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1408)
E/Kuroba | UNCAUGHT: 	at android.widget.ListView.onMeasure(ListView.java:1315)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.PostRepliesContainer.onMeasure(PostRepliesContainer.java:46)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E/Kuroba | UNCAUGHT: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
E/Kuroba | UNCAUGHT: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
E/Kuroba | UNCAUGHT: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
E/Kuroba | UNCAUGHT: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
E/Kuroba | UNCAUGHT: 	at android.view.View.measure(View.java:23190)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2725)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1575)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
E/Kuroba | UNCAUGHT: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
E/Kuroba | UNCAUGHT: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.7.0-dev Official
E/Kuroba | UNCAUGHT: Phone Model: Motorola MotoG3
```

**Comment by K1rakishou** [comment]
Did this happen in the catalog or in a thread? And if it did happen in a thread was that a live thread or maybe an archived/404ed thread or even local (downloaded) thread?

**Comment by floppyD** [comment]
It was a live thread

**Comment by K1rakishou** [comment]
Huh, probably synchronization issue again.
