### ISSUE TITLE
Exception in DatabaseHelper

### ISSUE THREAD

**Issue by Baldomo** [Adamantcheese/Kuroba#382]
The issue appears to be the two `.eq()` calls around L517 of DatabaseHelper. This exception during app initialization after upgrading prevents it from starting in any way

<details>
  <summary>Log</summary>
  <pre>
java.lang.IllegalStateException: Both the "left-hand" and "right-hand" clauses have been defined.  Did you miss an AND or OR?
	at com.j256.ormlite.stmt.Where.appendSql(Where.java:550)
	at com.j256.ormlite.stmt.StatementBuilder.appendWhereStatement(StatementBuilder.java:151)
	at com.j256.ormlite.stmt.StatementBuilder.appendStatementString(StatementBuilder.java:133)
	at com.j256.ormlite.stmt.StatementBuilder.buildStatementString(StatementBuilder.java:116)
	at com.j256.ormlite.stmt.StatementBuilder.prepareStatement(StatementBuilder.java:75)
	at com.j256.ormlite.stmt.DeleteBuilder.prepare(DeleteBuilder.java:33)
	at com.j256.ormlite.stmt.DeleteBuilder.delete(DeleteBuilder.java:40)
	at com.github.adamantcheese.chan.core.database.DatabaseHelper.deleteBoard(DatabaseHelper.java:517)
	at com.github.adamantcheese.chan.core.database.DatabaseHelper.onUpgrade(DatabaseHelper.java:288)
	at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.onUpgrade(OrmLiteSqliteOpenHelper.java:238)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:68)
	at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:174)
	at com.j256.ormlite.misc.TransactionManager.callInTransaction(TransactionManager.java:158)
	at com.github.adamantcheese.chan.core.database.DatabaseManager$DatabaseCallable.call(DatabaseManager.java:264)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
  </pre>
</details>

**Comment by Adamantcheese** [comment]
If you want, until the next release, you can use one of K1rak's dev builds. Export from Kuroba stable and import into Kuroba dev and you should be up and running for the time being.

**Comment by K1rakishou** [comment]
You will probably have to rename the settings file from `Kuroba_exported_settings.json` to `Kuroba-dev_exported_settings.json` or something like this. But it should start with `Kuroba-dev`
