### ISSUE TITLE
Exception in DatabaseHelper #2

### ISSUE THREAD

**Issue by Baldomo** [Adamantcheese/Kuroba#391]
The error traces back to [boardDelete](https://github.com/Adamantcheese/Kuroba/blob/4cc3ed4ec7a9c0a366a069043345cc3e5a0d95c2/Kuroba/app/src/main/java/com/github/adamantcheese/chan/core/database/DatabaseHelper.java#L533) 

<details>
<summary>Log</summary>
<pre>
java.lang.IllegalArgumentException: You should use columnName 'value' for table board instead of fieldName 'code'
	at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:154)
	at com.j256.ormlite.stmt.Where.findColumnFieldType(Where.java:649)
	at com.j256.ormlite.stmt.Where.eq(Where.java:192)
	at com.github.adamantcheese.chan.core.database.DatabaseHelper.deleteBoard(DatabaseHelper.java:533)
	at com.github.adamantcheese.chan.core.database.DatabaseHelper.onUpgrade(DatabaseHelper.java:288)
	at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.onUpgrade(OrmLiteSqliteOpenHelper.java:238)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:68)
</pre>
</details>

**Comment by Adamantcheese** [comment]
Same as before, dev builds are available.
