### ISSUE TITLE
[BUG] No applications were found to open this link toast when updating

### ISSUE THREAD

**Issue by Esildor** [Adamantcheese/Kuroba#408]
When trying to update the app it seems like it downloads successfully but upon trying to install it fails and I get a toast to saying: No applications found to open this link

Device: Google Pixel 3 (Stock)
Android 10

![Screenshot_20191106-224529](https://user-images.githubusercontent.com/5234969/68358879-df2dfd80-00e7-11ea-8756-4c664aa886c4.png)

**Comment by Adamantcheese** [comment]
Weird, it's like you don't have a package installer; can you install it from the file itself?

**Comment by Esildor** [comment]
Yes, tapping on the APK through my files app installs it

**Comment by Adamantcheese** [comment]
Really weird. I'm not sure if I'll be able to reproduce it, because I'm specifically sending an INSTALL_PACKAGES intent, which should open up a package installer application. Unless it's built into the OS now or something so there's no "application" for it to open up.

**Comment by Esildor** [comment]
I bet it's reproduceable through the emulator provided with Android studio. As long as you're emulating Android 10

**Comment by K1rakishou** [comment]
I actually have the same issue on my Pixel 2 XL stock with Android 10 (it was the same on 9) and I can't even install it when clicking the apk so I usually just use adb.

**Comment by Adamantcheese** [comment]
Pixels are doing some weird shit then. I'll test it on an emulator then and see if changing the action from INSTALL to VIEW fixes it.

**Comment by Adamantcheese** [comment]
Yeah, I don't know why it doesn't like it on 10. If you change it to allow the app to install from unknown sources in your settings (which it SHOULD pop up a thing telling you if you want to or not in the app), then it might let you install it; I got it to let me do it once and then it stopped for some reason, even though all the permissions were in place. Otherwise, nothing else I tried let me do it; VIEW doesn't work, updating the compile and target SDK to 29 didn't work, using the PackageInstaller didn't work, I just don't know and I can't find documentation on Android 10 doing anything new in regards to package management.

**Comment by K1rakishou** [comment]
Here is the error I get when trying to install it manually (I use amaze as a file manager):

```I/ActivityTaskManager: START u0 {act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Download/Kuroba.apk} from uid 10000
W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Download/Kuroba.apk }
W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5192)
W/System.err:     at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5150)
W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
W/System.err:     at android.app.Activity.startActivity(Activity.java:5521)
W/System.err:     at android.app.Activity.startActivity(Activity.java:5489)
W/System.err:     at com.amaze.filemanager.utils.files.FileUtils.installApk(FileUtils.java:424)
W/System.err:     at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation.lambda$showPackageDialog$23$GeneralDialogCreation(GeneralDialogCreation.java:846)
W/System.err:     at com.amaze.filemanager.ui.dialogs.GeneralDialogCreation$$Lambda$23.onClick(Unknown Source:4)
W/System.err:     at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
W/System.err:     at android.view.View.performClick(View.java:7140)
W/System.err:     at android.view.View.performClickInternal(View.java:7117)
W/System.err:     at android.view.View.access$3500(View.java:801)
W/System.err:     at android.view.View$PerformClick.run(View.java:27351)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by K1rakishou** [comment]
Oh yeah, according to the answer here https://stackoverflow.com/questions/39147608/android-install-apk-with-intent-view-action-not-working-with-file-provider a directory where the apk is should be included in the fileprovider (`<external-path name="external_download" path="Download"/>`) and we don't have it included, so maybe that's the problem?

**Comment by Adamantcheese** [comment]
Well it's being downloaded to the file cache already, and that's in file_paths.xml already. The DIRECTORY_DOWNLOADS location is likely dynamic in that the user can change it, so that would break it if I just put another thing into the XML and the user modified their downloads location, since the entries in the XML are static. I'll have it install from the file cache instead, and throw a copy with a version number into the user's downloads folder. This does work from my testing.

**Comment by filippo-orru** [comment]
I have this issue as well, running miui 11/ android 10 on redmi k20 pro.

**Comment by Adamantcheese** [comment]
The issue you have might be similar to the one I've seen in #444 for PDF files, but I still don't know what causes it. Also MIUI does some weird shit in general so that may be a cause.
