### ISSUE TITLE
[BUG/DEV] Dead link parser throws an exception when opening ThemesController

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#427]
```java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.github.adamantcheese.chan.core.manager.ArchivesManager.domainsForBoard(ArchivesManager.java:36)
        at com.github.adamantcheese.chan.core.site.parser.CommentParser.handleDead(CommentParser.java:254)
        at com.github.adamantcheese.chan.core.site.parser.-$$Lambda$MbFLskLV8RthWFGR4emyX8_E1g8.execute(Unknown Source:7)
        at com.github.adamantcheese.chan.core.site.parser.StyleRule.apply(StyleRule.java:204)
        at com.github.adamantcheese.chan.core.site.parser.CommentParser.handleTag(CommentParser.java:137)
        at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:246)
        at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseComment(DefaultPostParser.java:193)
        at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parse(DefaultPostParser.java:85)
        at com.github.adamantcheese.chan.ui.controller.ThemeSettingsController$Adapter.getView(ThemeSettingsController.java:306)
        at com.github.adamantcheese.chan.ui.view.ViewPagerAdapter.instantiateItem(ViewPagerAdapter.java:27)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1224)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:805)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at com.github.adamantcheese.chan.ui.layout.DrawerWidthAdjustingLayout.onMeasure(DrawerWidthAdjustingLayout.java:56)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)```

**Comment by K1rakishou** [comment]
And some parts of the dummy posts become not visible.
