### ISSUE TITLE
[BUG] Crash when trying to update the app

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#430]
```
E/Kuroba | UNCAUGHT: java.lang.NoClassDefFoundError: com.vladsch.flexmark.util.data.-$$Lambda$DataKey$w70X360D_iPjvPHPy0X-Au2N8lo
E/Kuroba | UNCAUGHT: at com.vladsch.flexmark.util.data.DataKey.<init>(DataKey.java:34)
E/Kuroba | UNCAUGHT: at com.vladsch.flexmark.util.builder.BuilderBase.<clinit>(BuilderBase.java:10)
E/Kuroba | UNCAUGHT: at com.vladsch.flexmark.parser.Parser.<clinit>(Parser.java:34)
E/Kuroba | UNCAUGHT: at com.github.adamantcheese.chan.core.net.UpdateApiRequest.readJson(UpdateApiRequest.java:89)
E/Kuroba | UNCAUGHT: at com.github.adamantcheese.chan.core.net.UpdateApiRequest.readJson(UpdateApiRequest.java:35)
E/Kuroba | UNCAUGHT: at com.github.adamantcheese.chan.core.net.JsonReaderRequest.parseNetworkResponse(JsonReaderRequest.java:59)
E/Kuroba | UNCAUGHT: at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:143)
E/Kuroba | UNCAUGHT: at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
E/Kuroba | UNCAUGHT: at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: Android API Level: 21
E/Kuroba | UNCAUGHT: App Version: v4.10.0 Release
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-A310F```

**Comment by Adamantcheese** [comment]
God damned old devices and their shitty nonexistent Java 8 support. Which is fucking weird because the app is LOADED with lambdas and they work fine, but if it's in a library NOOOO that's not possible god damned bullshit I tell you
