### ISSUE TITLE
[BUG] Cannot load local threads

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#436]
```D/Kuroba-dev | ThreadSaveManager: Enqueued new download request for loadable [4chan, g, 73717009]
D/Kuroba-dev | ThreadSaveManager: Collected 1 local thread download requests
D/Kuroba-dev | ThreadSaveManager: Snapshot created
D/Kuroba-dev | ThreadSaveManager: New downloading request started [4chan, g, 73717009], activeDownloads count = 1
D/Kuroba-dev | ThreadSaveManager: Starting a new download for [4chan, g, 73717009], on thread pool-3-thread-4
D/Kuroba-dev | ThreadSaveManager: filterAndSortPosts() completed in 24ms for loadable [4chan, g, 73717009] with 231 posts
D/Kuroba-dev | ThreadSaveManager: 112 new posts for a thread 73717009, with images 22
D/Kuroba-dev | ThreadSaveManager: Download for loadable [4chan, g, 73717009] ended up with an error
D/Kuroba-dev | ThreadSaveManager: java.lang.RuntimeException: Unable to invoke no-args constructor for java.util.Comparator<com.github.adamantcheese.chan.core.model.save.SerializablePost>. Registering an InstanceCreator with Gson for this type may fix this problem.
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.Gson.fromJson(Gson.java:932)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.Gson.fromJson(Gson.java:897)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.Gson.fromJson(Gson.java:846)
D/Kuroba-dev | ThreadSaveManager: 	at com.google.gson.Gson.fromJson(Gson.java:817)
D/Kuroba-dev | ThreadSaveManager: 	at com.github.adamantcheese.chan.core.repository.SavedThreadLoaderRepository.loadOldThreadFromJsonFile(SavedThreadLoaderRepository.kt:49)
D/Kuroba-dev | ThreadSaveManager: 	at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.lambda$saveThreadInternal$8$ThreadSaveManager(ThreadSaveManager.java:431)
D/Kuroba-dev | ThreadSaveManager: 	at com.github.adamantcheese.chan.core.manager.-$$Lambda$ThreadSaveManager$N7pUJY1lknlgI1ix2CGIeLa0G2k.call(Unknown Source:6)
D/Kuroba-dev | ThreadSaveManager: 	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
D/Kuroba-dev | ThreadSaveManager: 	at io.reactivex.Single.subscribe(Single.java:3603)
D/Kuroba-dev | ThreadSaveManager: 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
D/Kuroba-dev | ThreadSaveManager: 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
D/Kuroba-dev | ThreadSaveManager: 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
D/Kuroba-dev | ThreadSaveManager: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D/Kuroba-dev | ThreadSaveManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D/Kuroba-dev | ThreadSaveManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D/Kuroba-dev | ThreadSaveManager: 	at java.lang.Thread.run(Thread.java:919)
D/Kuroba-dev | ThreadSaveManager: Caused by: java.lang.Unsupp```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/Adamantcheese/Kuroba/commit/ccd14de33b09c98843b54c3f9132f7ea0188c779
