### ISSUE TITLE
[bug] Exception in DefaultPostParser when parsing a dead crossboard link

### ISSUE THREAD

**Issue by Flyingtoast** [Adamantcheese/Kuroba#484]
Posts containing dead cross-board links seem to show up as blank posts.
![JointPics_20191230_194148](https://user-images.githubusercontent.com/9301153/71606141-789feb80-2b3c-11ea-8716-13ad5c77c5f4.PNG)

**Comment by K1rakishou** [comment]
Just encountered the same issue. 
It's a crash in `CommentParser.handleDead()` 

```
E/Kuroba-dev | DefaultPostParser: Error parsing comment html
    java.lang.NumberFormatException: For input string: ">/int/116000000"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.github.adamantcheese.chan.core.site.parser.CommentParser.handleDead(CommentParser.java:246)
        at com.github.adamantcheese.chan.core.site.parser.-$$Lambda$MbFLskLV8RthWFGR4emyX8_E1g8.execute(Unknown Source:7)
        at com.github.adamantcheese.chan.core.site.parser.StyleRule.apply(StyleRule.java:201)
        at com.github.adamantcheese.chan.core.site.parser.CommentParser.handleTag(CommentParser.java:135)
        at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseNode(DefaultPostParser.java:241)
        at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parseComment(DefaultPostParser.java:183)
        at com.github.adamantcheese.chan.core.site.common.DefaultPostParser.parse(DefaultPostParser.java:77)
        at com.github.adamantcheese.chan.core.site.parser.PostParseCallable.call(PostParseCallable.java:65)
        at com.github.adamantcheese.chan.core.site.parser.PostParseCallable.call(PostParseCallable.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Here is the post - https://boards.4channel.org/qa/thread/3076023#p3076807
