### ISSUE TITLE
[BUG/DEV] Crash when trying to change files base directory by selecting Old API

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#548]
```
2020-02-03 11:32:21.566 E/Kuroba-dev | UNCAUGHT: java.lang.IllegalArgumentException: Cannot navigate to /storage/emulated/0
        at com.github.adamantcheese.chan.core.saver.FileWatcher.navigateTo(FileWatcher.java:67)
        at com.github.adamantcheese.chan.core.saver.FileWatcher.initialize(FileWatcher.java:51)
        at com.github.adamantcheese.chan.ui.controller.SaveLocationController.initialize(SaveLocationController.java:181)
        at com.github.adamantcheese.chan.ui.controller.SaveLocationController.onCreate(SaveLocationController.java:98)
        at com.github.adamantcheese.chan.controller.Controller.addChildController(Controller.java:139)
        at com.github.adamantcheese.chan.controller.NavigationController.transition(NavigationController.java:128)
        at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.transition(ToolbarNavigationController.java:49)
        at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.transition(StyledToolbarNavigationController.java:62)
        at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:54)
        at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.pushController(StyledToolbarNavigationController.java:57)
        at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:42)
        at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:38)
        at com.github.adamantcheese.chan.ui.controller.settings.MediaSettingsController.onSaveLocationUseOldApiClicked(MediaSettingsController.java:439)
        at com.github.adamantcheese.chan.ui.controller.settings.MediaSettingsController.lambda$showUseSAFOrOldAPIForSaveLocationDialog$12$MediaSettingsController(MediaSettingsController.java:421)
        at com.github.adamantcheese.chan.ui.controller.settings.-$$Lambda$MediaSettingsController$RZsq5ehtqEtvU8Ny07gFRwtOh7k.onClick(Unknown Source:2)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-02-03 11:32:21.566 E/Kuroba-dev | UNCAUGHT: ------------------------------
2020-02-03 11:32:21.566 E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
2020-02-03 11:32:21.566 E/Kuroba-dev | UNCAUGHT: ------------------------------
2020-02-03 11:32:21.566 E/Kuroba-dev | UNCAUGHT: Android API Level: 29
2020-02-03 11:32:21.566 E/Kuroba-dev | UNCAUGHT: App Version: v4.10.2-386d93a
2020-02-03 11:32:21.567 E/Kuroba-dev | UNCAUGHT: Development Build: Yes
2020-02-03 11:32:21.567 E/Kuroba-dev | UNCAUGHT: Phone Model: Google Pixel 2 XL
```

**Comment by K1rakishou** [comment]
Probably because of the targetSdk 29.

**Comment by Adamantcheese** [comment]
Try adding android:requestLegacyExternalStorage="true" to the manifest under the application tag. If it works, I'll push it real quick before I go to bed.

**Comment by K1rakishou** [comment]
I am at work so I can't.

**Comment by Adamantcheese** [comment]
Bluh, alright. I'll push it anyways, and if it's resolved, just let me know here.

**Comment by K1rakishou** [comment]
Alright, I will check it.

**Comment by K1rakishou** [comment]
Yeah, it works, wew.

**Comment by Adamantcheese** [comment]
Alrighty then, good to know.
