### ISSUE TITLE
[REPORT] Crash report "	java.lang.IllegalArgumentException: Failed to determine if primary:Kuroba/Saved threads/4chan/g/74458591 is child of primary:Kuroba/Saved threads: java.io.FileNotFoundException: Missing file for primary:Kuroba/Saved threads/4chan/g/74458591 at /storage/emulated/10/Kuroba/Saved threads/4chan/g/74458591"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#560]
```
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:82)
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:290)
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
	at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
	at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
	at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
	at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:212)
	at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:81)
	at io.reactivex.internal.subscribers.QueueDrainSubscriber.fastPathEmitMax(QueueDrainSubscriber.java:77)
	at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.run(FlowableBufferTimed.java:207)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
  ComposedException 1 :
	java.lang.IllegalArgumentException: Failed to determine if primary:Kuroba/Saved threads/4chan/g/74458591 is child of primary:Kuroba/Saved threads: java.io.FileNotFoundException: Missing file for primary:Kuroba/Saved threads/4chan/g/74458591 at /storage/emulated/10/Kuroba/Saved threads/4chan/g/74458591
		at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
		at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
		at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
		at android.content.ContentResolver.query(ContentResolver.java:756)
		at android.content.ContentResolver.query(ContentResolver.java:705)
		at android.content.ContentResolver.query(ContentResolver.java:663)
		at com.github.k1rakishou.fsaf.util.SAFHelper.listFilesFast(SAFHelper.kt:273)
		at com.github.k1rakishou.fsaf.FileManager.createSnapshot(FileManager.kt:778)
		at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.processCollectedRequests(ThreadSaveManager.java:171)
		at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.lambda$I_4E8UtKudQ5A5O-LrMfSJm5Eg8(Unknown Source:0)
		at com.github.adamantcheese.chan.core.manager.-$$Lambda$ThreadSaveManager$I_4E8UtKudQ5A5O-LrMfSJm5Eg8.apply(Unknown Source:4)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:284)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
		at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:212)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:81)
		at io.reactivex.internal.subscribers.QueueDrainSubscriber.fastPathEmitMax(QueueDrainSubscriber.java:77)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.run(FlowableBufferTimed.java:207)
		at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at java.lang.Thread.run(Thread.java:764)
  ComposedException 2 :
	java.lang.RuntimeException: ThreadSaveManager Uncaught exception!!! workerQueue is in error state now!!! This should not happen!!!, original error = Failed to determine if primary:Kuroba/Saved threads/4chan/g/74458591 is child of primary:Kuroba/Saved threads: java.io.FileNotFoundException: Missing file for primary:Kuroba/Saved threads/4chan/g/74458591 at /storage/emulated/10/Kuroba/Saved threads/4chan/g/74458591
		at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.lambda$initRxWorkerQueue$2(ThreadSaveManager.java:143)
		at com.github.adamantcheese.chan.core.manager.-$$Lambda$ThreadSaveManager$2Q3y8VtWERJ5KrYKpmo87Tg8bS8.accept(Unknown Source:2)
		at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:290)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
		at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:212)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:81)
		at io.reactivex.internal.subscribers.QueueDrainSubscriber.fastPathEmitMax(QueueDrainSubscriber.java:77)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.run(FlowableBufferTimed.java:207)
		at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
		at java.lang.Thread.run(Thread.java:764)


```

**Comment by K1rakishou** [comment]
That's pretty interesting. Directory names with spaces can sneak into SAF if you choose a directory on the internal storage via SAF. And apparently it's a SAF bug.

**Comment by K1rakishou** [comment]
>/storage/emulated/10/Kuroba/Saved threads/4chan/g/74458591

>10

This is somehow related to multi-account cases. When you open the app in a different account on the same phone, and, maybe, import settings where we use full paths to the directories including the user id which should normally be zero, but in case of using another user it's not zero (but it is zero in the settings so we are trying to open a directory that belongs to a different user). 

Basically we shouldn't use absolute paths in the exported settings but relative, e.g. not "/storage/emulated/10/Kuroba/Saved threads/" but just "/Saved threads/". So then when importing them back we should do something like:
```
getDefaultExternalAppDir() + "/Saved threads/"
```

And that should fix this issue. I hope.
