### ISSUE TITLE
unfriendly message when 404 on images

### ISSUE THREAD

**Issue by namazso** [Adamantcheese/Kuroba#562]
![Screenshot_20200205-184305](https://user-images.githubusercontent.com/8676443/73867769-85a0b080-4847-11ea-89d7-80156ed589ed.jpg)

**Comment by K1rakishou** [comment]
Did you just swipe to an image that was 404ed?

**Comment by namazso** [comment]
I clicked a threadstarter image in the catalog that was 404'd

**Comment by K1rakishou** [comment]
This is probably a bug. Damn this shit is going to be hard to reproduce.

**Comment by K1rakishou** [comment]
Maybe you still have the logs? Probably not, though.

**Comment by namazso** [comment]
No, sorry

**Comment by Adamantcheese** [comment]
@K1rakishou would it be possible to have the downloader cancel itself there instead of throwing that exception? I don't know if that would muck up something in the reactive stream.

**Comment by K1rakishou** [comment]
It should have actually canceled it but for some reason it didn't. "Expected Canceled or Stopped but was Running" is a check I do in some places after canceling a request. And I do the canceling by throwing an exception (CancellationException).

**Comment by Adamantcheese** [comment]
It's asynchronous, right? So maybe the request didn't get processed fast enough. Although if you cancel the request afterwards anyways, why keep the exception around? Basically, is there a better action to do than to throw an exception in this case, so users aren't confused by things only developers should see.

**Comment by K1rakishou** [comment]
The problem here is an illegal state (in other words it's a bug). I cancel a request and then I expect the state to be canceled but for some reason it isn't canceled so I throw an exception which is then propagated to the top and the user sees it. Ideally, the state should have been canceled so the user wouldn't have seen anything other than the 404 message. And I throw it because, well, I need to do something and show the user what had happened. Anyway I just came up with an idea how to reproduce this thing. Rolling sticky threads should do the thing. I just now need to find one.

**Comment by Adamantcheese** [comment]
/s4s/ has 4 stickies right now, maybe they'll get to 1000 replies soonish before the mods decide their time is up

**Comment by K1rakishou** [comment]
I hope they are not gone by the time I get home.

**Comment by K1rakishou** [comment]
Gotcha!

```
java.lang.RuntimeException: Expected: Canceled or Stopped, but actual state is Running
	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister.handleErrors(ChunkPersister.kt:136)
	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister.access$handleErrors(ChunkPersister.kt:17)
	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister$storeChunkInFile$1.subscribe(ChunkPersister.kt:101)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

Damn, implementing automatic crash report uploading was the best idea ever. Too bad it doesn't work in release for now because we would get so many priceless stacktraces we would be able to fix everything.
