### ISSUE TITLE
[REPORT] Crash report d4f2a69c2a352f089d78a740abe3a099

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#565]
```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@7a2a740 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
	at android.widget.Toast$TN.handleShow(Toast.java:459)
	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by K1rakishou** [comment]
So this is the price we have to pay for having toasts use app context.

**Comment by Adamantcheese** [comment]
Guess I'm going to not be clever and fix that then.

**Comment by K1rakishou** [comment]
I wonder if we could just check for this thing outselves, whether we can add a window or not. But your fix should be even better.

**Comment by Adamantcheese** [comment]
I considered checking it and then just said nah, just do it how it should be done.
