### ISSUE TITLE
Attempting to download files from 2ch.hk crashes the app.

### ISSUE THREAD

**Issue by wobblyyy** [Adamantcheese/Kuroba#574]
No message is displayed. I saw other users on 4chan have a similar problem. I can post logs later if necessary

**Comment by K1rakishou** [comment]
> I can post logs later if necessary

Please do. Right after the app crashes if possible.

**Comment by wobblyyy** [comment]
[logs.txt](https://github.com/Adamantcheese/Kuroba/files/4166723/logs.txt)

**Comment by K1rakishou** [comment]
```
E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: Only the last segment may have an extension, bad segment index = 0/1, bad name = 2ch.hk
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.file.AbstractFile.clone(AbstractFile.kt:85)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.file.AbstractFile.cloneUnsafe(AbstractFile.kt:56)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaver.getSaveLocation(ImageSaver.java:261)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaver.startDownloadTaskInternal(ImageSaver.java:199)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaver.startDownloadTask(ImageSaver.java:179)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:323)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveClicked(ImageViewerController.java:235)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.lambda$YTaxqp3Z9HaAlCji6bOdoidkYgY(Unknown Source:0)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageViewerController$YTaxqp3Z9HaAlCji6bOdoidkYgY.clicked(Unknown Source:2)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem.performClick(ToolbarMenuItem.java:200)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuView.handleClick(ToolbarMenuView.java:90)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuView.lambda$setupMenuViews$0$ToolbarMenuView(ToolbarMenuView.java:71)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.-$$Lambda$ToolbarMenuView$XxndyQBpeckpIT0kUQ_qKt6_FVc.onClick(Unknown Source:4)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClick(View.java:7259)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClickInternal(View.java:7236)
E/Kuroba | UNCAUGHT: 	at android.view.View.access$3600(View.java:801)
E/Kuroba | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:27892)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.11.0
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: Google Pixel 3a
```

**Comment by K1rakishou** [comment]
Thanks.

**Comment by K1rakishou** [comment]
The problem you are having is because a name of the directory where you store images contains a period. I will fix it, but for now you can just rename it (remove the period symbol).

**Comment by wobblyyy** [comment]
Strange because I don't see any periods in my directory names and downloading from 4chan works fine.Thanks for taking a look and glad it will be fixed.

**Comment by K1rakishou** [comment]
It should be called " 2ch.hk"

**Comment by wobblyyy** [comment]
No such folder. Only one for 4chan. I guess Kuroba isn't even making one? It isn't critical for me anyhow so I'll wait for the fix.

**Comment by K1rakishou** [comment]
>No such folder.

Ohh, I see now. It's because the app has crashed so it didn't create the directory. But it tried and encountered the period and the crashed because I don't allow periods. Alright.
