### ISSUE TITLE
Crash report "java.lang.IllegalStateException: Could not create directory /storage/emulated/0/Kuroba'

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#579]
```
java.lang.IllegalStateException: Could not create directory /storage/emulated/0/Kuroba
	at com.github.adamantcheese.chan.ui.controller.SaveLocationController.onPositionButtonClick(SaveLocationController.java:130)
	at com.github.adamantcheese.chan.ui.controller.SaveLocationController.lambda$onClick$0$SaveLocationController(SaveLocationController.java:115)
	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$SaveLocationController$6UPXcMYvOg1m6lpV22aK15eUd2I.onClick(lambda)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)

```

**Comment by K1rakishou** [comment]
What the fuck?
