### ISSUE TITLE
Crash report "Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10089 and Uri 0 @ content://com.android.externalstorage.documents/tree/6BF9-1F19:mehvuyycf55836z"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#580]
OS info: Android 5.1, sdk version: 22

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10001, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/tree/6BF9-1F19:mehvuyycf55836z flg=0xc3 }} to activity {com.github.adamantcheese.chan/com.github.adamantcheese.chan.StartActivity}: java.lang.SecurityException: No persistable permission grants found for UID 10089 and Uri 0 @ content://com.android.externalstorage.documents/tree/6BF9-1F19:mehvuyycf55836z
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4092)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4135)
	at android.app.ActivityThread.access$1400(ActivityThread.java:189)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10089 and Uri 0 @ content://com.android.externalstorage.documents/tree/6BF9-1F19:mehvuyycf55836z
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4256)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1716)
	at com.github.k1rakishou.fsaf.FileChooser.handleDirectoryChooserCallback(FileChooser.kt:314)
	at com.github.k1rakishou.fsaf.FileChooser.onActivityResult(FileChooser.kt:140)
	at com.github.adamantcheese.chan.StartActivity.onActivityResult(StartActivity.java:555)
	at android.app.Activity.dispatchActivityResult(Activity.java:6402)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4088)
	... 10 more
```

**Comment by K1rakishou** [comment]
What the fuck is this bullshit? From stackoverflow:

>takePersistableUriPermission() is for ACTION_OPEN_DOCUMENT and other actions that are part of the Storage Access Framework, not for ACTION_GET_CONTENT.

And that's exactly what's happening there I'm using ACTION_OPEN_DOCUMENT_TREE which is a part of SAF.

**Comment by K1rakishou** [comment]
And I wonder what the fuck is this shit:
```
content://com.android.externalstorage.documents/tree/6BF9-1F19:mehvuyycf55836z

this -> mehvuyycf55836z
```
