### ISSUE TITLE
Crash report "java.lang.RuntimeException: Unable to create file chunks cache dir /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/file_chunks_cache"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#585]
Crash report
UUID: 5d2cb6143f694b3fd638cb9a2f65c2b8
Build flavor: stable
Version name: v4.11.0
OS info: Android 5.0.2, sdk version: 21
Report description: No title
Logs:

```
java.lang.RuntimeException: Unable to create file chunks cache dir /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/file_chunks_cache
	at com.github.adamantcheese.chan.core.cache.CacheHandler.createDirectories(CacheHandler.kt:620)
	at com.github.adamantcheese.chan.core.cache.CacheHandler.getCacheFileInternal(CacheHandler.kt:550)
	at com.github.adamantcheese.chan.core.cache.CacheHandler.exists(CacheHandler.kt:103)
	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.imageAutoLoad(ImageViewerPresenter.java:593)
	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onLowResInCenter(ImageViewerPresenter.java:283)
	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onModeLoaded(ImageViewerPresenter.java:234)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.onModeLoaded(MultiImageView.java:801)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.access$400(MultiImageView.java:86)
	at com.github.adamantcheese.chan.ui.view.MultiImageView$1.onResponse(MultiImageView.java:316)
	at com.android.volley.toolbox.ImageLoader.get(ImageLoader.java:231)
	at com.android.volley.toolbox.ImageLoader.get(ImageLoader.java:193)
	at com.github.adamantcheese.chan.core.image.ImageLoaderV2.getImage(ImageLoaderV2.java:94)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.setThumbnail(MultiImageView.java:294)
	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$setMode$0$MultiImageView(MultiImageView.java:174)
	at com.github.adamantcheese.chan.ui.view.-$$Lambda$MultiImageView$shKI1JtMKREPy760_mbgGoeA6iM.onMeasured(lambda)
	at com.github.adamantcheese.chan.utils.AndroidUtils$1.onPreDraw(AndroidUtils.java:363)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1986)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by K1rakishou** [comment]
>Unable to create file chunks cache dir /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/file_chunks_cache

Why in the name of fuck it crashes there? It even managed to create the file_cache directory but failed to create the chunks directory!!!
