### ISSUE TITLE
[BUG] Media pre-fetching crashes the app

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#590]
UUID: 61ebb0ee3227cd9cd8259100e2016167
Build flavor: stable
Version name: v4.11.0
OS info: Android 5.1, sdk version: 22
Report description: Enabling the media pre-fetching replaces the thumbnail images for the full-size version in the catalog view.
This ultimately makes the app to stutter/crash.

Tested pre-fetching inside a thread, and it didn't crash since it displayed the thumbnails, but some images while clicked where displaying a zoom-in error notification.
Logs:
```
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1581061730380.jpg, state = Canceled
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1581064769108.jpg, state = Canceled
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1581101263778.jpg, state = Canceled
W/Kuroba | CustomScaleImageView: onImageLoadError
W/Kuroba | CustomScaleImageView: java.lang.RuntimeException: java.lang.OutOfMemoryError: Failed to allocate a 7471344 byte allocation with 7397810 free bytes and 7MB until OOM
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1751)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1717)
W/Kuroba | CustomScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Kuroba | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:818)
W/Kuroba | CustomScaleImageView: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 7471344 byte allocation with 7397810 free bytes and 7MB until OOM
W/Kuroba | CustomScaleImageView: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:87)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1743)
W/Kuroba | CustomScaleImageView: 	... 6 more
W/Kuroba | CustomScaleImageView: onImageLoadError
W/Kuroba | CustomScaleImageView: java.lang.RuntimeException: java.lang.OutOfMemoryError: Failed to allocate a 9340012 byte allocation with 7381486 free bytes and 7MB until OOM
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1751)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1717)
W/Kuroba | CustomScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Kuroba | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:818)
W/Kuroba | CustomScaleImageView: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 9340012 byte allocation with 7381486 free bytes and 7MB until OOM
W/Kuroba | CustomScaleImageView: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:87)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1743)
W/Kuroba | CustomScaleImageView: 	... 6 more
W/Kuroba | CustomScaleImageView: onImageLoadError
W/Kuroba | CustomScaleImageView: java.lang.RuntimeException: java.lang.OutOfMemoryError: Failed to allocate a 8129388 byte allocation with 6989716 free bytes and 6MB until OOM
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1751)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1717)
W/Kuroba | CustomScaleImageView: 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Kuroba | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Kuroba | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:818)
W/Kuroba | CustomScaleImageView: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 8129388 byte allocation with 6989716 free bytes and 6MB until OOM
W/Kuroba | CustomScaleImageView: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
W/Kuroba | CustomScaleImageView: 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:391)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:87)
W/Kuroba | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1743)
W/Kuroba | CustomScaleImageView: 	... 6 more
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1581107042292.jpg, state = Canceled
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1581107042292.jpg, state = Canceled
```

**Comment by K1rakishou** [comment]
The images are way too big, they are causing OOMs. Nothing can be done here.
