### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to read from field 'java.util.List com.github.adamantcheese.chan.ui.toolbar.ToolbarMenu.items' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#619]
UUID: 29c65d941e79bc765cec08f059b8c311
Build flavor: stable
Version name: v4.11.0
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
java.lang.NullPointerException: Attempt to read from field 'java.util.List com.github.adamantcheese.chan.ui.toolbar.ToolbarMenu.items' on a null object reference
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuView.detach(ToolbarMenuView.java:60)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarContainer$ItemView.remove(ToolbarContainer.java:434)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarContainer.removeItem(ToolbarContainer.java:407)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarContainer.update(ToolbarContainer.java:151)
	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.updateViewForItem(Toolbar.java:314)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarPresenter.update(ToolbarPresenter.java:56)
	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.updateTitle(Toolbar.java:270)
	at com.github.adamantcheese.chan.ui.controller.BrowseController.loadBoard(BrowseController.java:389)
	at com.github.adamantcheese.chan.core.presenter.BrowsePresenter.loadBoard(BrowsePresenter.java:121)
	at com.github.adamantcheese.chan.core.presenter.BrowsePresenter.onBoardsFloatingMenuBoardClicked(BrowsePresenter.java:74)
	at com.github.adamantcheese.chan.ui.controller.BrowseController.onBoardClicked(BrowseController.java:254)
	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu.itemClicked(BrowseBoardsFloatingMenu.java:215)
	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu.access$400(BrowseBoardsFloatingMenu.java:86)
	at com.github.adamantcheese.chan.ui.layout.BrowseBoardsFloatingMenu$BoardViewHolder.lambda$new$0$BrowseBoardsFloatingMenu$BoardViewHolder(BrowseBoardsFloatingMenu.java:496)
	at com.github.adamantcheese.chan.ui.layout.-$$Lambda$BrowseBoardsFloatingMenu$BoardViewHolder$5MsXd7kLbr8dUssLeTrwDfbvxo0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25885)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by K1rakishou** [comment]
Maybe it was related to tollbar issues and is already fixed.

**Comment by Adamantcheese** [comment]
On stable, so likely not.

**Comment by Adamantcheese** [comment]
This stack trace makes no sense, because removeItem is never called from update in the current stable code. https://github.com/Adamantcheese/Kuroba/blob/e1b3aac14126a3332905e66afa1ae2c328f9fab9/Kuroba/app/src/main/java/com/github/adamantcheese/chan/ui/toolbar/ToolbarContainer.java#L151
