### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.snackbar.Snackbar.dismiss()' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#620]
UUID: 670a53b6524f96ada50d78eb8300617c
Build flavor: stable
Version name: v4.11.0
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.snackbar.Snackbar.dismiss()' on a null object reference
	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.switchVisible(ThreadLayout.java:689)
	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showLoading(ThreadLayout.java:306)
	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.unbindLoadable(ThreadPresenter.java:218)
	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.destroy(ThreadLayout.java:183)
	at com.github.adamantcheese.chan.ui.controller.ThreadController.onDestroy(ThreadController.java:98)
	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.onDestroy(ViewThreadController.java:374)
	at com.github.adamantcheese.chan.controller.Controller.removeChildController(Controller.java:143)
	at com.github.adamantcheese.chan.controller.NavigationController.endSwipeTransition(NavigationController.java:102)
	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.endSwipeTransition(ToolbarNavigationController.java:79)
	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.endSwipeTransition(StyledToolbarNavigationController.java:74)
	at com.github.adamantcheese.chan.controller.ui.NavigationControllerContainerLayout.endTracking(NavigationControllerContainerLayout.java:276)
	at com.github.adamantcheese.chan.controller.ui.NavigationControllerContainerLayout.access$500(NavigationControllerContainerLayout.java:38)
	at com.github.adamantcheese.chan.controller.ui.NavigationControllerContainerLayout$1.run(NavigationControllerContainerLayout.java:312)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by K1rakishou** [comment]
Maybe it was related to Snackbar issues and is already fixed.

**Comment by Adamantcheese** [comment]
Yep, already fixed.
