### ISSUE TITLE
Crash report "java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#622]
UUID: b4cbc7d5baa4f958faca3e7555deb8d9
Build flavor: dev
Version name: v4.11.0-f3b9c00
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.ref.FinalizerReference.add(FinalizerReference.java:56)
	at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:62)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
	at java.lang.Daemons$Daemon.run(Daemons.java:103)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by K1rakishou** [comment]
Maybe OOM/Hi-res cells related.

**Comment by Adamantcheese** [comment]
Yeah this is going to be basically impossible to replicate.

**Comment by Adamantcheese** [comment]
From my research, because it's all the way down in the garbage collector, it's not really anything we can solve. It's likely a hi-res cells thing yeah, but recent application changes should have mitigated this problem. Closing as wontfix, happens too rarely to bother attempting to fix.
