### ISSUE TITLE
Crash report "java.lang.OutOfMemoryError: Failed to allocate a 146304 byte allocation with 79320 free bytes and 77KB until OOM, max allowed footprint 134217728, growth limit 134217728"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#623]
UUID: da4572773fe2f2cc3635a261764a49f1
Build flavor: dev
Version name: v4.11.0-f3b9c00
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.lang.OutOfMemoryError: Failed to allocate a 146304 byte allocation with 79320 free bytes and 77KB until OOM, max allowed footprint 134217728, growth limit 134217728
	at com.android.volley.toolbox.ByteArrayPool.getBuf(ByteArrayPool.java:99)
	at com.android.volley.toolbox.PoolingByteArrayOutputStream.expand(PoolingByteArrayOutputStream.java:75)
	at com.android.volley.toolbox.PoolingByteArrayOutputStream.write(PoolingByteArrayOutputStream.java:83)
	at com.android.volley.toolbox.BasicNetwork.inputStreamToBytes(BasicNetwork.java:291)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:152)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

**Comment by K1rakishou** [comment]
Hi-res cells maybe? Or a really big image was attempted to be opened?

**Comment by Adamantcheese** [comment]
If it's an OOM error, that recent change for #590 should take care of it.
