### ISSUE TITLE
Crash report "android.view.InflateException: Binary XML file line #38: Binary XML file line #38: Error inflating class <unknown>"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#630]
UUID: 8833979903dbc7e47eebb1748e912232
Build flavor: dev
Version name: v4.11.0-cf89929
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
android.view.InflateException: Binary XML file line #38: Binary XML file line #38: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #38: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_1(MethodHookerStubs32.java:564)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.github.adamantcheese.chan.utils.AndroidUtils.inflate(AndroidUtils.java:457)
	at com.github.adamantcheese.chan.ui.adapter.PostAdapter.onCreateViewHolder(PostAdapter.java:96)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassCastException: android.content.res.XResources cannot be cast to android.content.res.XResources
	at android.content.res.XResources$XTypedArray.getColor(XResources.java:1286)
	at com.github.adamantcheese.chan.ui.text.FastTextView.<init>(FastTextView.java:70)
	at com.github.adamantcheese.chan.ui.text.FastTextView.<init>(FastTextView.java:61)
	... 32 more
```

**Comment by Adamantcheese** [comment]
`android.content.res.XResources cannot be cast to android.content.res.XResources`
lolwut

**Comment by K1rakishou** [comment]
Yeah, and then there is also this thing:
```
at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_1(MethodHookerStubs32.java:564)
```

**Comment by K1rakishou** [comment]
Apparently it's some shitty custom ROM
