### ISSUE TITLE
Crash report "java.lang.NullPointerException: siteModel == null"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#632]
UUID: 93b919f0f8f658a580c94e5529ac7b2e
Build flavor: dev
Version name: v4.11.0-89b9ec7
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.lang.NullPointerException: siteModel == null
	at com.github.adamantcheese.chan.core.site.SiteService.updateUserSettings(SiteService.java:70)
	at com.github.adamantcheese.chan.core.site.SiteBase.lambda$postInitialize$0$SiteBase(SiteBase.java:68)
	at com.github.adamantcheese.chan.core.site.-$$Lambda$SiteBase$X4McErqP9wnQWoEMwrbjFZ2TToI.save(Unknown Source:4)
	at com.github.adamantcheese.chan.core.settings.json.JsonSettingsProvider.putString(JsonSettingsProvider.java:120)
	at com.github.adamantcheese.chan.core.settings.StringSetting.set(StringSetting.java:42)
	at com.github.adamantcheese.chan.core.settings.StringSetting.set(StringSetting.java:19)
	at com.github.adamantcheese.chan.ui.settings.StringSettingView.lambda$onClick$0$StringSettingView(StringSettingView.java:78)
	at com.github.adamantcheese.chan.ui.settings.-$$Lambda$StringSettingView$z9UMdrFfkjElco8gtHYQXequ_YY.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by K1rakishou** [comment]
@Adamantcheese 
Apparently this thing (https://github.com/Adamantcheese/Kuroba/commit/a84cbcf95585a4f0d555b2aa110b467e7f614287) blew up

**Comment by Adamantcheese** [comment]
That's not a problem with any of the code I wrote in that commit though, for some reason the SiteModel ID no longer matches with the old one so it's not finding it anymore; it's like the updated string setting caused it to think that this is a new database entry when it shouldn't be.

**Comment by K1rakishou** [comment]
Oh, well, I just saw you did change it and the report version has the same commit as the one with the change so I just assumed they are related.

**Comment by Adamantcheese** [comment]
They are, but it doesn't make sense as to why the database is shitting itself over this.
