### ISSUE TITLE
Crash report "android.app.RemoteServiceException: Bad notification posted from package com.github.adamantcheese.chan: Couldn't create icon: StatusBarIcon(pkg=com.github.adamantcheese.chanuser=0 id=0x7f0800c2 level=0 visible=true num=0 )"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#634]
UUID: c4353419d49a329b3fa631c98914bd8d
Build flavor: stable
Version name: v4.11.0
OS info: Android 5.0.2, sdk version: 21
Report description: No title
Logs:
```
android.app.RemoteServiceException: Bad notification posted from package com.github.adamantcheese.chan: Couldn't create icon: StatusBarIcon(pkg=com.github.adamantcheese.chanuser=0 id=0x7f0800c2 level=0 visible=true num=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1652)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:95)
```

**Comment by Adamantcheese** [comment]
Uh, I have no clue about this one. There's literally nothing I can do to even check if that would fail. Considering it's such an old device and there's some Xposed stuff in that log, I'm going to call it a bad ROM.
