### ISSUE TITLE
Crash report "android.content.res.Resources$NotFoundException: String resource ID #0x2040003"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#639]
UUID: f5cb5b7b6ed46236c90181cb3b81c483
Build flavor: stable
Version name: v4.11.0
OS info: Android 5.1.1, sdk version: 22
Report description: No title
Logs:
```
android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:321)
	at android.content.res.Resources.getString(Resources.java:407)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:489)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:459)
	at android.webkit.WebView.<init>(WebView.java:449)
	at com.github.adamantcheese.chan.ui.captcha.CaptchaLayout.<init>(CaptchaLayout.java:83)
	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.initializeAuthentication(ReplyLayout.java:349)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:536)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:518)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.submitOrAuthenticate(ReplyPresenter.java:272)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSubmitClicked(ReplyPresenter.java:228)
	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:314)
	at android.view.View.performClick(View.java:4789)
	at android.view.View$PerformClick.run(View.java:19881)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by Adamantcheese** [comment]
Yeah this one's just weird. Don't really know if this will fix it or not, but probably?
