### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to read from field 'boolean com.github.adamantcheese.chan.ui.toolbar.NavigationItem.search' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#641]
UUID: 014b1f58255ecd2e894457d2d86204e0
Build flavor: stable
Version name: v4.11.0
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.adamantcheese.chan/com.github.adamantcheese.chan.StartActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean com.github.adamantcheese.chan.ui.toolbar.NavigationItem.search' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean com.github.adamantcheese.chan.ui.toolbar.NavigationItem.search' on a null object reference
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarContainer$ItemView.createNavigationItemView(ToolbarContainer.java:443)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarContainer$ItemView.<init>(ToolbarContainer.java:425)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarContainer.set(ToolbarContainer.java:129)
	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.showForNavigationItem(Toolbar.java:275)
	at com.github.adamantcheese.chan.ui.toolbar.ToolbarPresenter.set(ToolbarPresenter.java:52)
	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.setNavigationItem(Toolbar.java:239)
	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.transition(ToolbarNavigationController.java:52)
	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.transition(StyledToolbarNavigationController.java:62)
	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:54)
	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.pushController(StyledToolbarNavigationController.java:57)
	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:42)
	at com.github.adamantcheese.chan.StartActivity.setupLayout(StartActivity.java:314)
	at com.github.adamantcheese.chan.StartActivity.onCreate(StartActivity.java:143)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	... 11 more
```

**Comment by Adamantcheese** [comment]
This is one of the crashes I got when I was testing the text downloading stuff. I've turned off the automatic upload setting since.

**Comment by Adamantcheese** [comment]
It might be a good idea to check if the platform sending the report is an emulator or not, and prevent the report from being sent if it is one.

**Comment by K1rakishou** [comment]
Yeah, maybe.
