### ISSUE TITLE
Crash report "android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@b394673 is not valid; is your activity running?"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#644]
UUID: aedcb8ebfaf6ce571d52bef13118f4ca
Build flavor: dev
Version name: v4.11.0-516a9fd
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
Called from unhandled exception handler.
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@b394673 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1123)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:439)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.app.Dialog.show(Dialog.java:473)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at com.github.adamantcheese.chan.core.manager.UpdateManager.lambda$runUpdateApi$3$UpdateManager(UpdateManager.java:226)
	at com.github.adamantcheese.chan.core.manager.-$$Lambda$UpdateManager$Yo4kn0spSGbRsS0gkoT0lDfFhNE.onResponse(Unknown Source:6)
	at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:90)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7807)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

**Comment by K1rakishou** [comment]
This one is in UpdateManager I don't remember us fixing it.

**Comment by jbzor** [comment]
i need a helpe on this error


E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.csu.controller, PID: 18071
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@68e3850 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.widget.Toast$TN.handleShow(Toast.java:459)
        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Adamantcheese** [comment]
What version are you running?
