### ISSUE TITLE
Crash report "Unable to start activity ComponentInfo{com.github.adamantcheese.chan.dev/com.github.adamantcheese.chan.StartActivity}: java.lang.IllegalArgumentException: The view given to waitForLayout is not attached to the window and does not have a ViewTreeObserver."

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#649]
UUID: 5bff7ab97a44266c5ea0112213a6e631
Build flavor: dev
Version name: v4.11.0-aaa26a9
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
E/Kuroba-dev | UNCAUGHT: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.adamantcheese.chan.dev/com.github.adamantcheese.chan.StartActivity}: java.lang.IllegalArgumentException: The view given to waitForLayout is not attached to the window and does not have a ViewTreeObserver.
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2944)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
E/Kuroba-dev | UNCAUGHT: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/Kuroba-dev | UNCAUGHT: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/Kuroba-dev | UNCAUGHT: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/Kuroba-dev | UNCAUGHT: Caused by: java.lang.IllegalArgumentException: The view given to waitForLayout is not attached to the window and does not have a ViewTreeObserver.
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.waitForLayout(AndroidUtils.java:318)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.scrollTo(ThreadListLayout.java:606)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.scrollTo(ThreadLayout.java:430)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.scrollTo(ThreadPresenter.java:733)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.scrollToPost(ThreadPresenter.java:768)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.java:599)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.quickLoad(ChanThreadLoader.java:280)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.requestInitialData(ThreadPresenter.java:310)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.loadThreadInternal(ViewThreadController.java:515)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.loadThread(ViewThreadController.java:492)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.loadThread(ViewThreadController.java:581)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.onCreate(ViewThreadController.java:145)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.Controller.addChildController(Controller.java:139)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.transition(NavigationController.java:128)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.transition(ToolbarNavigationController.java:49)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.transition(StyledToolbarNavigationController.java:62)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:54)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.pushController(StyledToolbarNavigationController.java:57)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:42)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.BrowseController.showThread(BrowseController.java:504)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.StartActivity.restoreFromUrl(StartActivity.java:203)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.StartActivity.setupFromStateOrFreshLaunch(StartActivity.java:170)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.StartActivity.onCreate(StartActivity.java:157)
E/Kuroba-dev | UNCAUGHT: 	at android.app.Activity.performCreate(Activity.java:7136)
E/Kuroba-dev | UNCAUGHT: 	at android.app.Activity.performCreate(Activity.java:7127)
E/Kuroba-dev | UNCAUGHT: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.performLaunchActiv
```

**Comment by K1rakishou** [comment]
And here is the culprit:
```
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to BACKGROUND
```

**Comment by K1rakishou** [comment]
Probably should add the background/foreground check around any dialog window/popup window/toast/snackbar etc.

**Comment by K1rakishou** [comment]
Or even better create custom classes that extend dialog window/popup window/toast/snackbar etc. with this check internal so it's more clean and we won't have to think about it in the future.

**Comment by K1rakishou** [comment]
Oh, there is already a similar issue.
