### ISSUE TITLE
Crash report "java.lang.NullPointerException: getData() returned null"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#650]
UUID: 39effcdf7b7841bda1737f00e8817a64
Build flavor: dev
Version name: v4.11.0-aaa26a9
OS info: Android 9, sdk version: 28
Report description: No title
Logs:

```
Called from unhandled exception handler.
java.lang.NullPointerException: getData() returned null
	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$requestMoreData$1$ChanThreadLoader(ChanThreadLoader.java:238)
	at com.github.adamantcheese.chan.core.site.loader.-$$Lambda$ChanThreadLoader$9PM3eOCUR_Dipzz2OCTjqZEt7rA.call(Unknown Source:2)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by K1rakishou** [comment]
Apparently this is fine. The error got into the RxJava global error handler because the stream was already disposed at the time this exception was thrown. So RxJava kinda doesn't know where to put this exception and sends it into it's global error handler. Otherwise it should have been sent into the regular onError handler. I wonder how can I check it and just ignore such errors so they don't spam us to death.
