### ISSUE TITLE
Crash report  "java.lang.IllegalArgumentException: Cannot pop with no controllers left"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#655]
UUID: 05a50a34176f40502f0d782715b0bbe7
Build flavor: dev
Version name: v4.11.0-fd6f0e1
OS info: Android 7.1.2, sdk version: 25
Report description: No title

```
E/Kuroba-dev | UNCAUGHT: java.lang.IllegalArgumentException: Cannot pop with no controllers left
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.transition(NavigationController.java:119)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.transition(ToolbarNavigationController.java:49)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.transition(StyledToolbarNavigationController.java:62)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.popController(NavigationController.java:73)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.popController(StyledToolbarNavigationController.java:52)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.popController(NavigationController.java:64)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.AlbumViewController.goToPost(AlbumViewController.java:143)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.goPostClicked(ImageViewerController.java:212)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.lambda$Sww0oz4mkJcZvDzA1N40ubE_WKo(ImageViewerController.java)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageViewerController$Sww0oz4mkJcZvDzA1N40ubE_WKo.clicked(lambda)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem.performClick(ToolbarMenuItem.java:200)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuView.handleClick(ToolbarMenuView.java:92)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuView.lambda$setupMenuViews$0$ToolbarMenuView(ToolbarMenuView.java:73)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.-$$Lambda$ToolbarMenuView$XxndyQBpeckpIT0kUQ_qKt6_FVc.onClick(lambda)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.performClick(View.java:5647)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:22465)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:754)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:163)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6238)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 25
E/Kuroba-dev | UNCAUGHT: App Version: v4.11.0-fd6f0e1
E/Kuroba-dev | UNCAUGHT: Development Build: Yes
E/Kuroba-dev | UNCAUGHT: Phone Model: Xiaomi Redmi 4X
```

**Comment by Adamantcheese** [comment]
Yeah this one is basically impossible to replicate. Somehow in the literal span of milliseconds between function calls, someone managed to both tap the goto button and exit out of the image viewer and album viewer.

**Comment by K1rakishou** [comment]
>someone managed to both tap the goto button and exit out of the image viewer and album viewer.

I wonder how their hands look like.
