### ISSUE TITLE
Crash report "Caused by: java.io.IOException: No such file or directory"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#659]
UUID: e913c7e210b25167b789d4c76f59c3c9
Build flavor: dev
Version name: v4.11.0-516a9fd
OS info: Android 7.1.2, sdk version: 25
Report description: No title
Logs:
```
Called from unhandled exception handler.
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	... 1 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
	at java.io.File.createNewFile(File.java:948)
	at com.github.k1rakishou.fsaf.manager.RawFileManager.create(RawFileManager.kt:33)
	at com.github.k1rakishou.fsaf.manager.RawFileManager.create(RawFileManager.kt:14)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
	at com.github.adamantcheese.chan.core.manager.UpdateManager$1.onSuccess(UpdateManager.java:301)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:679)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:43)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$resultHandler$1$1.run(FileCacheV2.kt:831)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	... 3 more
```

**Comment by K1rakishou** [comment]
Looks like one of the parent directories (like maybe the Downloads directory where we copy the apk?) was nonexistent. Is it even possible to not have the Downloads directory on the phone? I guess with custom ROMs it is.

**Comment by Adamantcheese** [comment]
For this specific case, since the APK is only a backup copy that is being made, I'll just wrap it in a try-catch and ignore the failure. The APK should still be able to be installed without issue.
