### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.adamantcheese.chan.core.model.Post com.github.adamantcheese.chan.core.model.ChanThread.getOp()' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#661]
UUID: 07c04d12b6a5b8aa1f53a77f777862f6
Build flavor: dev
Version name: v4.11.0-2b57d72
OS info: Android 10, sdk version: 29
Report description: No title

```
E/Kuroba-dev | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.adamantcheese.chan.core.model.Post com.github.adamantcheese.chan.core.model.ChanThread.getOp()' on a null object reference
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.manager.WatchManager$PinWatcher.onChanLoaderData(WatchManager.java:1249)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$onResponseInternalNext$11$ChanThreadLoader(ChanThreadLoader.java:522)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.site.loader.-$$Lambda$ChanThreadLoader$XrVbmH-bv74v7UUBuKhInygVGS4.run(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:219)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7441)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by K1rakishou** [comment]
Apparently BackgroundUtils.runOnMainThread(()) in onResponseInternalNext in ChanThreadLoader is the culprit. The loader probably was released while we were waiting for the main thread to call the callback. Should add an additional null-check right after the runOnMainThread calls the callback.

**Comment by K1rakishou** [comment]
Also, apparently `thread`, `loadable`, `pendingFuture` and maybe `request` are not properly synchronized (in ChanThreadLoader).
