### ISSUE TITLE
Crash report " java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#662]
UUID: 806a4253aad3e3c91901511c12ddaa8b
Build flavor: dev
Version name: v4.11.0-2b57d72
OS info: Android 10, sdk version: 29
Report description: No title

```
E/Kuroba-dev | ImageReencodingPresenter: Error while trying to get image format
E/Kuroba-dev | ImageReencodingPresenter: java.io.IOException: File is null!
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.utils.BitmapUtils.getImageFormat(BitmapUtils.java:223)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ImageReencodingPresenter.getImageFormat(ImageReencodingPresenter.java:113)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.controller.ImageOptionsController.onCreate(ImageOptionsController.java:144)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:200)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:192)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.presentReencodeOptionsController(ThreadLayout.java:762)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.helper.ImageOptionsHelper.showController(ImageOptionsHelper.java:49)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:651)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.showImageReencodingWindow(ThreadPresenter.java:1303)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:253)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.showImageReencodingWindow(ThreadListLayout.java:652)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:326)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.view.View.performClick(View.java:7158)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.view.View.performClickInternal(View.java:7135)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.view.View.access$3500(View.java:801)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.view.View$PerformClick.run(View.java:27373)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.os.Looper.loop(Looper.java:219)
E/Kuroba-dev | ImageReencodingPresenter: 	at android.app.ActivityThread.main(ActivityThread.java:7441)
E/Kuroba-dev | ImageReencodingPresenter: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/Kuroba-dev | ImageReencodingPresenter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.ImageDecoder.decodeFile(ImageDecoder.java:86)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.ImageDecoder.lambda$decodeFileOnBackgroundThread$1(ImageDecoder.java:44)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.-$$Lambda$ImageDecoder$HM8bqGlc2CvIreKC5wkGtqc7txU.run(Unknown Source:8)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:919)
E/Kuroba-dev | UNCAUGHT: ------------------------------
```

**Comment by K1rakishou** [comment]
Note: there are two different exceptions. But the cause is apparently the same.

**Comment by Adamantcheese** [comment]
Related to #631.
