### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to read from field 'int com.github.adamantcheese.chan.core.model.orm.Board.siteId' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#677]
UUID: 76b9d036b067d79898d80623fc0c625e
Build flavor: dev
Version name: v4.11.0-34af4e6
OS info: Android 8.0.0, sdk version: 26
Report description: No title
Logs:

```
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-3]: Request [FileDownloadRequest: url = https://media.8kun.top/file_store/1d139600bd60eeb4cee53c8e853d11e3885b032f422fd474bbb820ebba74dXXX.jpg, outputFileName = 8c4ebd42dbf524c1b70465218f0cd3d6.cache] canceled, downloaded = 0, total = 0, network class = WIFI, downloads = 1


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.NullPointerException: Attempt to read from field 'int com.github.adamantcheese.chan.core.model.orm.Board.siteId' on a null object reference
	at com.github.adamantcheese.chan.core.model.orm.Loadable.forCatalog(Loadable.java:132)
	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onPostLinkableClicked(ThreadPresenter.java:1057)
	at com.github.adamantcheese.chan.ui.cell.PostCell$PostViewMovementMethod.onTouchEvent(PostCell.java:765)
	at android.widget.TextView.onTouchEvent(TextView.java:9734)
	at android.view.View.dispatchTouchEvent(View.java:11740)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:456)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1839)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3333)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:418)
	at android.view.View.dispatchPointerEvent(View.java:11979)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4822)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4636)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4227)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4193)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4201)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4377)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4227)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4193)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4201)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6695)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6669)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6630)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6798)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: true
Youtube titles parsing enabled: true
Youtube durations parsing enabled: true
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba-dev/saved_threads, SAF location: , active: Java API
Phone layout mode: SLIDE
```

**Comment by K1rakishou** [comment]
Actually, I think I know what's going on here. 8kun has like thousands of boards and IIRC we don't download them. So whenever you are trying to open a board via a link we won't find it in the DB and we will get the NPE. That's kinda a big problem. IIRC during 8chan times we were actually downloading the whole board list so there was no such problem. Maybe I'm wrong.

**Comment by Adamantcheese** [comment]
No that makes sense, that's the conclusion I just reached looking at the code. I'll just add in some code to generate those boards if the database doesn't have them.

**Comment by K1rakishou** [comment]
I wonder is there an API where you can get the info about one specific board instead of loading the whole list. That would be really useful.

**Comment by K1rakishou** [comment]
Are you planning to adding new boards with some default values? Maybe we could just disable crossboard linking for a time being for 8kun? Because a proper solution may take some time.

**Comment by Adamantcheese** [comment]
The way dynamic boards work means that the above solution should work for 8kun. Feel free to test it.

**Comment by K1rakishou** [comment]
But we are not storing them in the DB. Once you navigate to such a board what would happen once you tried to pin a thread or something like that?

**Comment by Adamantcheese** [comment]
Well I guess a crash report will show up here then.

**Comment by K1rakishou** [comment]
Damn I can't post so I can't test it.

**Comment by Adamantcheese** [comment]
Looking through the code flow it hits the DatabaseLoadableManager, which will keep track of the board itself, so there shouldn't be any problems.

**Comment by Adamantcheese** [comment]
And for Pins, the DatabasePinManager keeps track of the loadable, so it doesn't even need to be stored in the DatabaseLoadableManager.

**Comment by K1rakishou** [comment]
Yeah, I found couple of crossboard links and looks like it works.

**Comment by K1rakishou** [comment]
Actually no it crashes.

```
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
    java.lang.NullPointerException: Attempt to read from field 'int com.github.adamantcheese.chan.core.model.orm.Board.bumpLimit' on a null object reference
        at com.github.adamantcheese.chan.ui.adapter.DrawerAdapter.updatePinViewHolderInternal(DrawerAdapter.java:333)
        at com.github.adamantcheese.chan.ui.adapter.DrawerAdapter.updatePinViewHolder(DrawerAdapter.java:284)
        at com.github.adamantcheese.chan.ui.adapter.DrawerAdapter.onBindViewHolder(DrawerAdapter.java:174)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:21912)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
    	at android.view.Choreographer$CallbackR
```

**Comment by K1rakishou** [comment]
After you restart the app.

**Comment by K1rakishou** [comment]
```
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
    java.lang.NullPointerException: Loadable.board == null
        at com.github.adamantcheese.chan.core.site.parser.ChanReaderRequest.getChanUrl(ChanReaderRequest.java:117)
        at com.github.adamantcheese.chan.core.site.parser.ChanReaderRequest.<init>(ChanReaderRequest.java:89)
        at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.getData(ChanThreadLoader.java:348)
        at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.requestDataInternal(ChanThreadLoader.java:190)
        at com.github.adamantcheese.chan.core.site.loader.ChanThreadLoader.lambda$FVqw8K8PO_ud6C6tv4UL0l2-mJ8(Unknown Source:0)
        at com.github.adamantcheese.chan.core.site.loader.-$$Lambda$ChanThreadLoader$FVqw8K8PO_ud6C6tv4UL0l2-mJ8.accept(Unknown Source:4)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
