### ISSUE TITLE
Crash report "java.lang.RuntimeException: android.os.DeadSystemException"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#681]
```
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.RuntimeException: android.os.DeadSystemException
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.handleSleeping(ActivityThread.java:5003)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.access$2600(ActivityThread.java:268)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2080)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:237)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7811)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
E/Kuroba-dev | UNCAUGHT: Caused by: android.os.DeadSystemException
E/Kuroba-dev | UNCAUGHT: 	... 9 more
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.11.0-bd5b314
E/Kuroba-dev | UNCAUGHT: Development Build: Yes
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-N960U

=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: false
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba-dev/files, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba-dev/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
Probably there is nothing we can do here.

**Comment by Adamantcheese** [comment]
Literally nothing we can do, it's an exception that says the OS is restarting. Seems to happen more often on Samsung devices (which this is one).
