### ISSUE TITLE
Crash report "java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionStatusViewHolder

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#686]
UUID: 77b87c25c02bc311bf8b33f90e7929c9
Build flavor: dev
Version name: v4.11.1-0c8c22c
OS info: Android 9, sdk version: 28
Report description: No title

```
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionStatusViewHolder{9bc101c position=22 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{5863c4b VFED..... ......I. 0,0-1080,2157 #7f09017c app:id/recycler_view}, adapter:com.github.adamantcheese.chan.ui.adapter.PostAdapter@220a56a, layout:com.github.adamantcheese.chan.ui.layout.ThreadListLayout$2@448ea5b, context:com.github.adamantcheese.chan.StartActivity@ec22d67
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
E/Kuroba-dev | UNCAUGHT: 	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:193)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 28
E/Kuroba-dev | UNCAUGHT: App Version: v4.11.1-0c8c22c
E/Kuroba-dev | UNCAUGHT: Development Build: Yes
E/Kuroba-dev | UNCAUGHT: Phone Model: Xiaomi POCO F1

=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: false, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: true
Concurrent file loading chunks count: 4
WEBM streaming enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba-dev/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
Concurrency issue in adapter?
