### ISSUE TITLE
Crash report "java.lang.RuntimeException: Expected: Canceled or Stopped, but actual state is Running"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#688]
UUID: d18c746e233e75c38af9d266d8d92a26
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
java.lang.RuntimeException: Expected: Canceled or Stopped, but actual state is Running
	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister.handleErrors(ChunkPersister.kt:136)
	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister.access$handleErrors(ChunkPersister.kt:17)
	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister$storeChunkInFile$1.subscribe(ChunkPersister.kt:101)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by K1rakishou** [comment]
Damn this thing again.

**Comment by K1rakishou** [comment]
This one is one of the old crash logs. It's already been fixed. Stack trace doesn't make any sense so I'm closing it.
