### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: dir is not a directory"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#690]
UUID: c700edc21e83fa87ab30190804c40da9
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:82)
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:290)
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
	at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
	at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
	at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
	at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:212)
	at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:81)
	at io.reactivex.internal.subscribers.QueueDrainSubscriber.fastPathEmitMax(QueueDrainSubscriber.java:77)
	at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.run(FlowableBufferTimed.java:207)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
  ComposedException 1 :
	java.lang.IllegalArgumentException: dir is not a directory
		at com.github.k1rakishou.fsaf.FileManager.createSnapshot(FileManager.kt:764)
		at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.processCollectedRequests(ThreadSaveManager.java:171)
		at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.lambda$I_4E8UtKudQ5A5O-LrMfSJm5Eg8(Unknown Source:0)
		at com.github.adamantcheese.chan.core.manager.-$$Lambda$ThreadSaveManager$I_4E8UtKudQ5A5O-LrMfSJm5Eg8.apply(Unknown Source:4)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:284)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
		at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:212)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:81)
		at io.reactivex.internal.subscribers.QueueDrainSubscriber.fastPathEmitMax(QueueDrainSubscriber.java:77)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.run(FlowableBufferTimed.java:207)
		at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:919)
  ComposedException 2 :
	java.lang.RuntimeException: ThreadSaveManager Uncaught exception!!! workerQueue is in error state now!!! This should not happen!!!, original error = dir is not a directory
		at com.github.adamantcheese.chan.core.manager.ThreadSaveManager.lambda$initRxWorkerQueue$2(ThreadSaveManager.java:143)
		at com.github.adamantcheese.chan.core.manager.-$$Lambda$ThreadSaveManager$2Q3y8VtWERJ5KrYKpmo87Tg8bS8.accept(Unknown Source:2)
		at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:290)
		at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
		at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
		at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
		at io.reactivex.subscribers.SerializedSubscriber.onNext(SerializedSubscriber.java:100)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:212)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.accept(FlowableBufferTimed.java:81)
		at io.reactivex.internal.subscribers.QueueDrainSubscriber.fastPathEmitMax(QueueDrainSubscriber.java:77)
		at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactUnboundedSubscriber.run(FlowableBufferTimed.java:207)
		at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:919)
```

**Comment by K1rakishou** [comment]
Should update FSAF with more logs in that particular place because this doesn't make any sense.
