### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#693]
Crash report
UUID: 0f6c3a01cf7588d803aae6d9e9416152
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6742)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23190)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2725)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1575)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Adamantcheese** [comment]
This isn't enough information to do anything about. Closing.
