### ISSUE TITLE
Crash report "kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = com.github.k1rakishou.fsaf.file.FileManagerId@c9ebc8b"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#694]
UUID: 27d374cf73e2d2d015cc99cd56e97f9c
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.0.0, sdk version: 26
Report description: No title
Logs:
```
=== LOGS ===
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Error while trying to download, class = FileNotFoundOnTheServerException, message = FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: [NormalFileCacheV2Thread-0]: Exception for request [FileDownloadRequest: url = https://media.8kun.top/file_store/e48944a49ab95c83e731419fed6386602904c0cb7af1e9cd625b85563b2f8XXX.jpg, outputFileName = baee1026751fe9e4b04e7d1f68b786fd.cache], network class = WIFI, downloads = 1
E/Kuroba | FileCacheV2: com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$FileNotFoundOnTheServerException: FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: 	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister$storeChunkInFile$1.subscribe(ChunkPersister.kt:53)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/Kuroba | FileCacheV2: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Error while trying to download, class = FileNotFoundOnTheServerException, message = FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: [NormalFileCacheV2Thread-2]: Exception for request [FileDownloadRequest: url = https://media.8kun.top/file_store/e48944a49ab95c83e731419fed6386602904c0cb7af1e9cd625b85563b2f8XXX.jpg, outputFileName = baee1026751fe9e4b04e7d1f68b786fd.cache], network class = WIFI, downloads = 2
E/Kuroba | FileCacheV2: com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$FileNotFoundOnTheServerException: FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: 	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister$storeChunkInFile$1.subscribe(ChunkPersister.kt:53)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/Kuroba | FileCacheV2: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://media.8kun.top/file_store/6e57bf512c5c5d91bf98171b0c995d311ad672fb7d7b321b059c266d71e4dXXX.jpg, state = Canceled
E/FileManager: Base directory class com.github.adamantcheese.chan.ui.settings.base_directory.LocalThreadsBaseDirectory with path /storage/emulated/0/Kuroba/saved_threads does not exist!
E/Kuroba | ViewThreadController: saveClickedInternal() fileManager.newLocalThreadFile() returned null
E/FileManager: Base directory class com.github.adamantcheese.chan.ui.settings.base_directory.LocalThreadsBaseDirectory with path /storage/emulated/0/Kuroba/saved_threads does not exist!
E/Kuroba | ViewThreadController: saveClickedInternal() fileManager.newLocalThreadFile() returned null
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = com.github.k1rakishou.fsaf.file.FileManagerId@c9ebc8b
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.getName(FileManager.kt:656)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.areTheSame(FileManager.kt:844)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.settings.base_directory.SharedLocationSetupDelegate.askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory(SharedLocationSetupDelegate.kt:102)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:147)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:120)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$$inlined$let$lambda$1.run(MediaSettingsControllerPresenter.kt:263)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:789)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:164)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 26
E/Kuroba | UNCAUGHT: App Version: v4.11.1
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G930P


=== STACKTRACE ===
Called from unhandled exception handler.
kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = com.github.k1rakishou.fsaf.file.FileManagerId@c9ebc8b
	at com.github.k1rakishou.fsaf.FileManager.getName(FileManager.kt:656)
	at com.github.k1rakishou.fsaf.FileManager.areTheSame(FileManager.kt:844)
	at com.github.adamantcheese.chan.ui.controller.settings.base_directory.SharedLocationSetupDelegate.askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory(SharedLocationSetupDelegate.kt:102)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:147)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:120)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$$inlined$let$lambda$1.run(MediaSettingsControllerPresenter.kt:263)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2F4chan, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
Damn what a stupid mistake. Basically this happened because FileManagerId didn't have overloaded hashcode and equals functions so it was comparing them by their addresses. Strange that this is the first time I'm seeing this, though. It should have happened way more often.
