### ISSUE TITLE
Crash report "java.lang.SecurityException: Document 2562 is not a descendant of downloads"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#696]
UUID: 47d1fb120a93a58a6114472823481032
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
java.lang.SecurityException: Document 2562 is not a descendant of downloads
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1205)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.getInputStream(ExternalFileManager.kt:287)
	at com.github.k1rakishou.fsaf.FileManager.getInputStream(FileManager.kt:642)
	at com.github.k1rakishou.fsaf.FileManager.copyFileContents(FileManager.kt:356)
	at com.github.k1rakishou.fsaf.FileManager.copyDirectoryWithContent(FileManager.kt:490)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$moveFilesInternal$1.run(MediaSettingsControllerPresenter.kt:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by K1rakishou** [comment]
```
java.lang.SecurityException: Document 17 is not a descendant of downloads
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1460)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1297)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1017)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.getInputStream(ExternalFileManager.kt:287)
	at com.github.k1rakishou.fsaf.FileManager.getInputStream(FileManager.kt:642)
	at com.github.k1rakishou.fsaf.FileManager.copyFileContents(FileManager.kt:356)
	at com.github.k1rakishou.fsaf.FileManager.copyDirectoryWithContent(FileManager.kt:490)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$moveFilesInternal$1.run(MediaSettingsControllerPresenter.kt:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by K1rakishou** [comment]
Literally zero information about this exception in google.
