### ISSUE TITLE
Crash report "java.lang.IllegalStateException: Drag shadow dimensions must be positive"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#700]
UUID: 5f5ef55ac12aa46bb1ea7cb4815e3d67
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
java.lang.IllegalStateException: Drag shadow dimensions must be positive
	at android.view.View.startDragAndDrop(View.java:24087)
	at android.widget.Editor.startDragAndDrop(Editor.java:1165)
	at android.widget.Editor.performLongClick(Editor.java:1191)
	at android.widget.TextView.performLongClick(TextView.java:11346)
	at android.view.View.performLongClick(View.java:6675)
	at android.view.View$CheckForLongPress.run(View.java:25915)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6693)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
```

**Comment by Adamantcheese** [comment]
Given that there's nothing in the application that does anything with drag shadows as they should be automatically platform generated, this likely isn't solvable by any dev. From https://github.com/wordpress-mobile/WordPress-Android/issues/10492#issuecomment-568892433, and that the report says Android 9, this is likely an Android platform issue that is not resolvable.
