### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3131-6232/Android/data/com.github.adamantcheese.chan/cache/filecache/c6fab536589aa5c5cb7c82630501fcfb.cache"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#703]
UUID: b03163add48b8afcf1aba434617cc7eb
Build flavor: stable
Version name: v4.11.1
OS info: Android 7.0, sdk version: 24
Report description: No title
Logs:
```
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3131-6232/Android/data/com.github.adamantcheese.chan/cache/filecache/c6fab536589aa5c5cb7c82630501fcfb.cache
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
	at com.github.adamantcheese.chan.core.manager.UpdateManager.installApk(UpdateManager.java:360)
	at com.github.adamantcheese.chan.core.manager.UpdateManager.access$100(UpdateManager.java:76)
	at com.github.adamantcheese.chan.core.manager.UpdateManager$1.onSuccess(UpdateManager.java:310)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:667)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:44)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$resultHandler$1$1.run(FileCacheV2.kt:798)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by K1rakishou** [comment]
```
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/4498-6558/Android/data/com.github.adamantcheese.chan/cache/filecache/c6fab536589aa5c5cb7c82630501fcfb.cache
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:744)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
	at com.github.adamantcheese.chan.core.manager.UpdateManager.installApk(UpdateManager.java:360)
	at com.github.adamantcheese.chan.core.manager.UpdateManager.access$100(UpdateManager.java:76)
	at com.github.adamantcheese.chan.core.manager.UpdateManager$1.onSuccess(UpdateManager.java:310)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:667)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleResults$3.invoke(FileCacheV2.kt:44)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$resultHandler$1$1.run(FileCacheV2.kt:798)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by Adamantcheese** [comment]
Makes no sense though, shouldn't be any issues installing directly from the file cache.

**Comment by K1rakishou** [comment]
The problem here, apparently, is that the file cache exists somewhere on the external storage instead of internal (presumably an SD-card judging by this thing - "4498-6558" it looks like an SD-card UID or whatever it is). The safest route here is to just use SAF.

**Comment by Adamantcheese** [comment]
Sounds like someone's a moron that put their file cache on an external directory instead of internal and that'll just cause all sorts of issues.

**Comment by K1rakishou** [comment]
Well we actually support that, so it's partly our problem too:
```
static File getCacheDir() {
        // See also res/xml/filepaths.xml for the fileprovider.
        if (getAppContext().getExternalCacheDir() != null) {
            return getAppContext().getExternalCacheDir();
        } else {
            return getAppContext().getCacheDir();
        }
    }
```
