### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/yeah....webm"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#714]
UUID: fb1c27fc2dbc92438971a1742a89b099
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/yeah....webm
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
	at android.content.ContentResolver.call(ContentResolver.java:2042)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:128)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:198)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:149)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:537)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by K1rakishou** [comment]
```
java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/imagine_being_on_v..jpg
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
	at android.content.ContentResolver.call(ContentResolver.java:2042)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:128)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:198)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:149)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:537)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by K1rakishou** [comment]
Basically, should filter any periods other than the last one in file segments. Gotta also check whether it works with directories and add tests to FSAF.

**Comment by K1rakishou** [comment]
```
=== LOGS ===
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/2b0a7b7b-12a5-428e-91d8-36d8dfeb75e7..png
E/Kuroba | UNCAUGHT: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
E/Kuroba | UNCAUGHT: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/Kuroba | UNCAUGHT: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
E/Kuroba | UNCAUGHT: 	at android.content.ContentResolver.call(ContentResolver.java:2049)
E/Kuroba | UNCAUGHT: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1333)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:129)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:202)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:153)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:538)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:237)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7762)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.11.1
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G970U
```

**Comment by thshailesh** [comment]
![image](https://user-images.githubusercontent.com/86474696/192081487-981ea27c-b450-4653-b54d-3434da85c053.png)


I am facing this issue, please help me
