### ISSUE TITLE
Crash report "kotlin.KotlinNullPointerException 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$1.run"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#716]
UUID: 1458b6af0ae1fc4701a7c0aae89b2dc2
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
kotlin.KotlinNullPointerException
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$1.run(MediaSettingsControllerPresenter.kt:261)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by K1rakishou** [comment]
Oh no no no, Kotlin, you were supposed to prevent NPEs!
