### ISSUE TITLE
Crash report "java.lang.Error: java.io.IOException: File name too long"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#719]
UUID: 310ac9b3c5b87ee04180d9b319ef95d9
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.0.0, sdk version: 26
Report description: No title
Logs:
```
java.lang.Error: java.io.IOException: File name too long
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: File name too long
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
	at java.io.File.createNewFile(File.java:1000)
	at com.github.k1rakishou.fsaf.manager.RawFileManager.create(RawFileManager.kt:54)
	at com.github.k1rakishou.fsaf.manager.RawFileManager.create(RawFileManager.kt:14)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
	at com.github.k1rakishou.fsaf.FileManager.copyDirectoryWithContent(FileManager.kt:483)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$moveFilesInternal$1.run(MediaSettingsControllerPresenter.kt:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	... 2 more
```

**Comment by K1rakishou** [comment]
Gonna put this here for now
```
 /storage/emulated/0/Download/Screenshot_2020-03-04_Charlie_Kirk_on_Twitter_Wow_Look_at_the_results_in_Colorado_tonight_so_far_Bernie_SandersвЂ”238,345_Mik....png
/mnt/media_rw/6338-3264/DCIM/4chan/my_stinky_boyрџҐєгЂЃ#guineapig.webm
```

**Comment by K1rakishou** [comment]
I think there is nothing can be done on the FSAF side, we just need to trim everything that is longer than 255 characters (I believe?)
