### ISSUE TITLE
OutOfMemory exceptions

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#723]
Here we are going to try to catch the OOM that happens when something is trying to allocate a HUGE memory chunk (like 100MB). So far the possible culprits are: inlined files and hi-res cells.

**Comment by K1rakishou** [comment]
Crash report
UUID: 641048cfeefbe1cba8a0615811faa430
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:
```
java.lang.RuntimeException: Canvas: trying to draw too large(118520000bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at android.view.View.draw(View.java:19218)
	at android.view.View.updateDisplayListIfDirty(View.java:18168)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.updateDisplayListIfDirty(View.java:18159)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.draw(View.java:19221)
	at android.view.View.updateDisplayListIfDirty(View.java:18168)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
	at android.view.View.draw(View.java:19221)
	at android.view.View.updateDisplayListIfDirty(View.java:18168)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.updateDisplayListIfDirty(View.java:18159)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.updateDisplayListIfDirty(View.java:18159)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.updateDisplayListIfDirty(View.java:18159)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.updateDisplayListIfDirty(View.java:18159)
	at android.view.View.draw(View.java:18946)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
	at android.view.View.draw(View.java:19221)
	at com.android.internal.policy.DecorView.draw(DecorView.java:791)
	at android.view.View.updateDisplayListIfDirty(View.java:18168)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3046)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2841)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2394)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1427)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6827)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
	at android.view.Choreographer.doCallbacks(Choreographer.java:838)
	at android.view.Choreographer.doFrame(Choreographer.java:769)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:171)
	at android.app.ActivityThread.main(ActivityThread.java:6606)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by K1rakishou** [comment]
It was trying to allocate 3GB of memory?

```
E/Kuroba | UNCAUGHT: java.lang.OutOfMemoryError: Failed to allocate a 3288070920 byte allocation with 7512120 free bytes and 376MB until OOM, max allowed footprint 15024240, growth limit 402653184
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler$readCacheFileMeta$1.invoke(CacheHandler.kt:521)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler$readCacheFileMeta$1.invoke(CacheHandler.kt:63)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.RawFileManager.withFileDescriptor(RawFileManager.kt:257)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.withFileDescriptor(FileManager.kt:727)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.readCacheFileMeta(CacheHandler.kt:509)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.groupFilterAndSortFiles(CacheHandler.kt:736)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.trim(CacheHandler.kt:686)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.access$trim(CacheHandler.kt:63)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler$fileWasAdded$1.run(CacheHandler.kt:295)
E/Kuroba | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/Kuroba | UNCAUGHT: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/Kuroba | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by Adamantcheese** [comment]
Closed with https://github.com/Adamantcheese/Kuroba/commit/cc4f70ca2acf54138cb4664a4b27189cbb142859.
