### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/imagine_being_on_v..jpg"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#732]
UUID: 73f156d814cbb55275171d3ab5ea57c2
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
java.lang.IllegalArgumentException: Invalid file path: /storage/emulated/0/Download/imagine_being_on_v..jpg
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
	at android.content.ContentResolver.call(ContentResolver.java:2042)
	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:128)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:198)
	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:149)
	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:537)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by K1rakishou** [comment]
Actually this one is the same as this #714
