### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Parent document isn't a directory"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#734]
Crash report
UUID: d5aee964bfa39c5d4d5b0fdcffa97862
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS ===
E/DirectoryManager: SAF base directory content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba has no permissions whatsoever anymore!
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 21:43:44
D/FileChooser: treeUri = content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 21:46:32
E/DirectoryManager: dir content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba is not a directory
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.IllegalArgumentException: Parent document isn't a directory
E/Kuroba | UNCAUGHT: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
E/Kuroba | UNCAUGHT: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/Kuroba | UNCAUGHT: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
E/Kuroba | UNCAUGHT: 	at android.content.ContentResolver.call(ContentResolver.java:2058)
E/Kuroba | UNCAUGHT: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:129)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.create(ExternalFileManager.kt:25)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:342)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.create(FileManager.kt:318)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.copyToDestination(ImageSaveTask.java:202)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaveTask.onSuccess(ImageSaveTask.java:153)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.FileCacheV2$handleFileImmediatelyAvailable$1$1.run(FileCacheV2.kt:538)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:224)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.11.1
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: Xiaomi Mi 9T Pro

=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
Moved to https://github.com/K1rakishou/Fuck-Storage-Access-Framework/issues/20
