### ISSUE TITLE
Crash report "java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.adamantcheese.chan/.ui.service.SavingNotification"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#735]
UUID: 3ccfc2c14e6212624b404f54f240d0d9
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:
```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.github.adamantcheese.chan/.ui.service.SavingNotification (has extras) }: app is in background uid UidRecord{e3192f8 u0a117 CAC  bg:+2m57s793ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
	at android.app.ContextImpl.startService(ContextImpl.java:1477)
	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
	at com.github.adamantcheese.chan.core.saver.ImageSaver.updateNotification(ImageSaver.java:399)
	at com.github.adamantcheese.chan.core.saver.ImageSaver.startBundledTaskInternal(ImageSaver.java:369)
	at com.github.adamantcheese.chan.core.saver.ImageSaver.startBundledTask(ImageSaver.java:219)
	at com.github.adamantcheese.chan.ui.controller.AlbumDownloadController.handleDownloadResult(AlbumDownloadController.java:161)
	at com.github.adamantcheese.chan.ui.controller.AlbumDownloadController.lambda$onClick$0$AlbumDownloadController(AlbumDownloadController.java:154)
	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$AlbumDownloadController$c5mN6zJjadSU1PhVtzB2dwEJig0.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by K1rakishou** [comment]
Just need to add a check that we are in foreground before starting the service.
