### ISSUE TITLE
Crash report "java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 13(offset:13)."

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#738]
UUID: ce636698de6220138a17ed372560c151
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 13(offset:13).state:64 androidx.recyclerview.widget.RecyclerView{62dad8 VFED.V... ........ 49,160-1220,2671 #7f09019c app:id/suggestions}, adapter:com.github.adamantcheese.chan.ui.layout.BoardAddLayout$SuggestionsAdapter@443c63e, layout:androidx.recyclerview.widget.LinearLayoutManager@9367c9f, context:com.github.adamantcheese.chan.StartActivity@23bce72
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6183)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by K1rakishou** [comment]
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionStatusViewHolder{e40abf7 position=163 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{d97996f VFED..... ......I. 0,0-1440,2672 #7f09012b app:id/recycler_view}, adapter:com.github.adamantcheese.chan.ui.adapter.PostAdapter@526567c, layout:com.github.adamantcheese.chan.ui.layout.ThreadListLayout$2@f94cb05, context:com.github.adamantcheese.chan.StartActivity@7fc7204
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

**Comment by K1rakishou** [comment]
The second one is actually from a different adapter.

**Comment by K1rakishou** [comment]
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionStatusViewHolder{8f53cfa position=32 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{11ec9738 VFED.... ......I. 0,0-540,850 #7f09012b app:id/recycler_view}, adapter:com.github.adamantcheese.chan.ui.adapter.PostAdapter@251fa311, layout:com.github.adamantcheese.chan.ui.layout.ThreadListLayout$2@224dcc76, context:com.github.adamantcheese.chan.StartActivity@32c37232
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5974)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6158)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5310)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by K1rakishou** [comment]
These three are definitely issues that are tied to synchronization issues. There is just no other way for the adapter items to change between recycler passes.
