### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to invoke interface method 'void com.github.adamantcheese.chan.core.cache.stream.WebmStreamingDataSource$Callback.dataSourceAddedFile(java.io.File)' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#742]
UUID: 63692289b5d942fbb5211731cc262593
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:

```
=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.NullPointerException: Attempt to invoke interface method 'void com.github.adamantcheese.chan.core.cache.stream.WebmStreamingDataSource$Callback.dataSourceAddedFile(java.io.File)' on a null object reference
	at com.github.adamantcheese.chan.core.cache.stream.WebmStreamingDataSource.lambda$cacheComplete$0$WebmStreamingDataSource(WebmStreamingDataSource.java:392)
	at com.github.adamantcheese.chan.core.cache.stream.-$$Lambda$WebmStreamingDataSource$yraBdug7FhOp_vAAgApdjna1q8E.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7022)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: true
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.externalstorage.documents/tree/primary%3AClover/document/primary%3AClover, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: PHONE
```

**Comment by Adamantcheese** [comment]
This one makes no sense because the only listener that's ever set is never null. Unless I'm missing something with Kotlin destroying the listener function and so the reference is updated to be null?

**Comment by K1rakishou** [comment]
Probably synchronization issue.
