### ISSUE TITLE
Crash report "java.io.IOException: File is null!"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#743]
UUID: 84b7738c28237f9c8692372e0329ee59
Build flavor: stable
Version name: v4.11.1
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
=== LOGS ===
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | ReplyPresenter: onPostComplete error
E/Kuroba | ImageReencodingPresenter: Error while trying to get image format
E/Kuroba | ImageReencodingPresenter: java.io.IOException: File is null!
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.utils.BitmapUtils.getImageFormat(BitmapUtils.java:223)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ImageReencodingPresenter.getImageFormat(ImageReencodingPresenter.java:113)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.controller.ImageOptionsController.onCreate(ImageOptionsController.java:142)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:200)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:192)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.presentReencodeOptionsController(ThreadLayout.java:756)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.helper.ImageOptionsHelper.showController(ImageOptionsHelper.java:49)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:647)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.showImageReencodingWindow(ThreadPresenter.java:1328)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:244)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.showImageReencodingWindow(ThreadListLayout.java:680)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:326)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View.performClick(View.java:7339)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View.performClickInternal(View.java:7305)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View.access$3200(View.java:846)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View$PerformClick.run(View.java:27787)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Looper.loop(Looper.java:214)
E/Kuroba | ImageReencodingPresenter: 	at android.app.ActivityThread.main(ActivityThread.java:7078)
E/Kuroba | ImageReencodingPresenter: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | ImageReencodingPresenter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/Kuroba | ImageReencodingPresenter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.ImageDecoder.decodeFile(ImageDecoder.java:86)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.ImageDecoder.lambda$decodeFileOnBackgroundThread$1(ImageDecoder.java:44)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.-$$Lambda$ImageDecoder$HM8bqGlc2CvIreKC5wkGtqc7txU.run(Unknown Source:8)
E/Kuroba | UNCAUGHT: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.11.1
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-A920F
```

**Comment by Adamantcheese** [comment]
This one was already technically resolved from #662, but somehow this dude is the fastest man alive.
