### ISSUE TITLE
Crash report "java.lang.IndexOutOfBoundsException: setSpan (146 ... 1830) ends beyond length 146"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#749]
UUID: e28d0f78a59622473ae26a87a5e663e1
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:
```
java.lang.IndexOutOfBoundsException: setSpan (146 ... 1830) ends beyond length 146
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1309)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
	at android.widget.Editor$SuggestionsPopupWindow.updateSuggestions(Editor.java:3719)
	at android.widget.Editor$SuggestionsPopupWindow.show(Editor.java:3591)
	at android.widget.Editor.replace(Editor.java:386)
	at android.widget.Editor$3.run(Editor.java:2231)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6640)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

**Comment by Adamantcheese** [comment]
This is a platform bug for whoever this came from, not an application bug.
