### ISSUE TITLE
Crash report " java.lang.RuntimeException: Unable to create file cache dir /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/filecache"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#770]
UUID: 23ce0433d3df12f806f96a29f4a2d8bf
Build flavor: stable
Version name: v4.11.2
OS info: Android 7.1.2, sdk version: 25
Report description: No title
Logs:
```
=== LOGS(2020-02-28 17:29:30 UTC) ===
E/FileManager: Base directory class com.github.adamantcheese.chan.ui.settings.base_directory.SavedFilesBaseDirectory with path /storage/emulated/0/Kuroba/files does not exist!
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/gif/1582895628XXX.webm, state = Canceled
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/gif/1582444312XXX.webm, state = Canceled
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/gif/1582576640XXX.webm, state = Canceled
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/gif/1582576640XXX.webm, state = Canceled
I/Kuroba | CaptchaLayout: 0:Refused to load the script 'https://www.gstatic.com/recaptcha/releases/61bII03-TtCmSUR7dw9MJF9q/recaptcha__en.js' because it violates the following Content Security Policy directive: "script-src 'nonce-IcCvdTyPrA9qAbxyk5IKiQ' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'". 'strict-dynamic' is present, so host-based whitelisting is disabled.
I/Kuroba | CaptchaLayout:  https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc&co=aHR0cHM6Ly9ib2FyZHMuNGNoYW4ub3JnOjQ0Mw..&hl=en&v=61bII03-TtCmSUR7dw9MJF9q&theme=light&size=compact&cb=y2slqrbm10yl
I/Kuroba | CaptchaLayout: 1:Uncaught [object DOMException] https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=61bII03-TtCmSUR7dw9MJF9q
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.RuntimeException: Unable to create file cache dir /storage/emulated/0/Android/data/com.github.adamantcheese.chan/cache/filecache
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.createDirectories(CacheHandler.kt:612)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.getCacheFileInternal(CacheHandler.kt:547)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.cache.CacheHandler.exists(CacheHandler.kt:104)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.imageAutoLoad(ImageViewerPresenter.java:614)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onTap(ImageViewerPresenter.java:473)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.onTap(MultiImageView.java:250)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onSingleTapConfirmed(MultiImageViewGestureDetector.kt:37)
E/Kuroba | UNCAUGHT: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 25
E/Kuroba | UNCAUGHT: App Version: v4.11.2
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: samsung GT-I9500


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
Not this shit again.

**Comment by K1rakishou** [comment]
Well at least now I know that this isn't the FSAF's fault because it fails here:
```
rawFile.mkdirs()
```

Honestly, I blame this shit:

```
static File getCacheDir() {
        // See also res/xml/filepaths.xml for the fileprovider.
        if (getAppContext().getExternalCacheDir() != null) {
            return getAppContext().getExternalCacheDir();
        } else {
            return getAppContext().getCacheDir();
        }
    }
```

But I have no idea why would it fucking crash and why it happens so rarely.

**Comment by K1rakishou** [comment]
So what else can it be? Permissions? But this directory is supposed to be private to the app. Or maybe cachedir was moved to sd-card?

**Comment by Adamantcheese** [comment]
Most likely thing I can tell is that someone just disabled the storage permission entirely from their system settings.

**Comment by K1rakishou** [comment]
Maybe there is an app that does it automatically? Like it allows you to enable the permissions for some time and then automatically revoke them? I mean the rooted phones. That would explain a lot.

**Comment by Adamantcheese** [comment]
Maybe? That would be out of our control though.
