### ISSUE TITLE
Crash report "java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getName()' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#775]
UUID: 1be0653705686559ac03ba5e76ace30c
Build flavor: stable
Version name: v4.11.2
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(2020-02-29 15:09:52 UTC) ===
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getName()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.showPreview(ReplyPresenter.java:578)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onImageOptionsApplied(ReplyPresenter.java:600)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onImageOptionsApplied(ReplyLayout.java:794)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.onImageOptionsApplied(ThreadListLayout.java:841)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.onImageOptionsApplied(ThreadLayout.java:752)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.helper.ImageOptionsHelper.onImageOptionsApplied(ImageOptionsHelper.java:87)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageOptionsController.lambda$onImageOptionsApplied$1$ImageOptionsController(ImageOptionsController.java:274)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageOptionsController$v_LJwZKgew-NNO8v2GN1Iqr2Y4M.run(Unknown Source:6)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:237)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7777)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.11.2
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G975F


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: false, active downloads = 0
Hi-res thumbnails enabled: true
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: PHONE
```

**Comment by Adamantcheese** [comment]
Should've closed this with https://github.com/Adamantcheese/Kuroba/commit/1174d45e5fb19916dff4e0f3b128716c8713761e
