### ISSUE TITLE
Crash log "android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#780]
```
E/Kuroba | UNCAUGHT: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
E/Kuroba | UNCAUGHT: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:471)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:251)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.getFactory(WebView.java:2681)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.ensureProviderCreated(WebView.java:2676)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.setOverScrollMode(WebView.java:2741)
E/Kuroba | UNCAUGHT: 	at android.view.View.<init>(View.java:4825)
E/Kuroba | UNCAUGHT: 	at android.view.View.<init>(View.java:4966)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.<init>(ViewGroup.java:659)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:659)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:604)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:587)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:574)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:564)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.captcha.CaptchaLayout.<init>(CaptchaLayout.java:80)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.initializeAuthentication(ReplyLayout.java:358)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:538)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:521)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.submitOrAuthenticate(ReplyPresenter.java:275)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSubmitClicked(ReplyPresenter.java:231)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:324)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClick(View.java:6615)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClickInternal(View.java:6592)
E/Kuroba | UNCAUGHT: 	at android.view.View.access$3100(View.java:778)
E/Kuroba | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:25907)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:198)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6732)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/Kuroba | UNCAUGHT: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
E/Kuroba | UNCAUGHT: 	at android.webkit.WebViewFactory.fixupStubApplicationInfo(WebViewFactory.java:344)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:412)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:439)
E/Kuroba | UNCAUGHT: 	... 31 more
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.11.2
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: asus ASUS_X017DA
```

**Comment by K1rakishou** [comment]
And here is what we can do:
https://stackoverflow.com/questions/46048912/android-failed-to-load-webview-provider-no-webview-installed
https://stackoverflow.com/questions/52253951/androidruntimeexception-android-webkit-webviewfactorymissingwebviewpackageexce

**Comment by K1rakishou** [comment]
Just wrap everything into a try/catch and show a toast in case of this error.

**Comment by K1rakishou** [comment]
There is also this thing that I see in the crash logs sometimes:
```
android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:321)
	at android.content.res.Resources.getString(Resources.java:407)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:489)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:459)
	at android.webkit.WebView.<init>(WebView.java:449)
	at com.github.adamantcheese.chan.ui.captcha.CaptchaLayout.<init>(CaptchaLayout.java:83)
	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.initializeAuthentication(ReplyLayout.java:349)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:536)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.switchPage(ReplyPresenter.java:518)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.submitOrAuthenticate(ReplyPresenter.java:272)
	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onSubmitClicked(ReplyPresenter.java:228)
	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:314)
	at android.view.View.performClick(View.java:4789)
	at android.view.View$PerformClick.run(View.java:19881)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
