### ISSUE TITLE
Crash report "java.io.IOException: File picked_file is neither PNG nor JPEG"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#783]
UUID: 8fbd30a5016237c5843d2379a4e30e47
Build flavor: stable
Version name: v4.11.2
OS info: Android 7.0, sdk version: 24
Report description: No title
Logs:
```
=== LOGS(2020-03-01 20:40:42 UTC) ===
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:10:42
I/Kuroba | WatchManager: All watchers updated, finished at 03:10:42
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:15:37
I/Kuroba | WatchManager: All watchers updated, finished at 03:15:38
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:17:44
I/Kuroba | WatchManager: All watchers updated, finished at 03:17:45
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | ImageReencodingPresenter: Error while trying to get image format
E/Kuroba | ImageReencodingPresenter: java.io.IOException: File picked_file is neither PNG nor JPEG
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.utils.BitmapUtils.getImageFormat(BitmapUtils.java:265)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ImageReencodingPresenter.getImageFormat(ImageReencodingPresenter.java:113)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.controller.ImageOptionsController.onCreate(ImageOptionsController.java:142)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:200)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:192)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.presentReencodeOptionsController(ThreadLayout.java:747)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.helper.ImageOptionsHelper.showController(ImageOptionsHelper.java:49)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:638)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.showImageReencodingWindow(ThreadPresenter.java:1321)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:242)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.showImageReencodingWindow(ThreadListLayout.java:648)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:326)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View.performClick(View.java:5619)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View$PerformClick.run(View.java:22298)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Handler.handleCallback(Handler.java:754)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Looper.loop(Looper.java:165)
E/Kuroba | ImageReencodingPresenter: 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/Kuroba | ImageReencodingPresenter: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | ImageReencodingPresenter: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/Kuroba | ImageReencodingPresenter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:20:07
I/Kuroba | WatchManager: All watchers updated, finished at 03:20:08
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:22:39
I/Kuroba | WatchManager: All watchers updated, finished at 03:22:40
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:27:27
I/Kuroba | WatchManager: All watchers updated, finished at 03:27:28
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:30:13
I/Kuroba | WatchManager: All watchers updated, finished at 03:30:14
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:31:51
I/Kuroba | WatchManager: All watchers updated, finished at 03:31:52
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:34:12
I/Kuroba | WatchManager: All watchers updated, finished at 03:34:13
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:35:50
I/Kuroba | WatchManager: All watchers updated, finished at 03:35:51
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | ImageReencodingPresenter: Error while trying to get image format
E/Kuroba | ImageReencodingPresenter: java.io.IOException: File picked_file is neither PNG nor JPEG
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.utils.BitmapUtils.getImageFormat(BitmapUtils.java:265)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ImageReencodingPresenter.getImageFormat(ImageReencodingPresenter.java:113)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.controller.ImageOptionsController.onCreate(ImageOptionsController.java:142)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:200)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.controller.Controller.presentController(Controller.java:192)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.presentReencodeOptionsController(ThreadLayout.java:747)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.helper.ImageOptionsHelper.showController(ImageOptionsHelper.java:49)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:638)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.showImageReencodingWindow(ThreadPresenter.java:1321)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.showImageReencodingWindow(ThreadLayout.java:242)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.showImageReencodingWindow(ThreadListLayout.java:648)
E/Kuroba | ImageReencodingPresenter: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onClick(ReplyLayout.java:326)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View.performClick(View.java:5619)
E/Kuroba | ImageReencodingPresenter: 	at android.view.View$PerformClick.run(View.java:22298)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Handler.handleCallback(Handler.java:754)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | ImageReencodingPresenter: 	at android.os.Looper.loop(Looper.java:165)
E/Kuroba | ImageReencodingPresenter: 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/Kuroba | ImageReencodingPresenter: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | ImageReencodingPresenter: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/Kuroba | ImageReencodingPresenter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
I/Kuroba | WatchManager: 2 pin watchers beginning updates, started at 03:39:04
I/Kuroba | WatchManager: All watchers updated, finished at 03:39:05
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.

=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: , active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
There is also another crash in the same crash logs, maybe they are related so I'm gonna post it here

```
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getName()' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.showPreview(ReplyPresenter.java:578)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ReplyPresenter.onImageOptionsApplied(ReplyPresenter.java:600)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ReplyLayout.onImageOptionsApplied(ReplyLayout.java:794)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadListLayout.onImageOptionsApplied(ThreadListLayout.java:841)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.onImageOptionsApplied(ThreadLayout.java:752)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.helper.ImageOptionsHelper.onImageOptionsApplied(ImageOptionsHelper.java:87)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageOptionsController.lambda$onImageOptionsApplied$1$ImageOptionsController(ImageOptionsController.java:274)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ImageOptionsController$v_LJwZKgew-NNO8v2GN1Iqr2Y4M.run(lambda)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:754)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:165)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 24
E/Kuroba | UNCAUGHT: App Version: v4.11.2
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: Xiaomi Redmi Note 4
```
