### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Bad symbols encountered at index 7, symbol = ' '"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#793]
UUID: 915af9ed6128c26a241e643ddf185e7b
Build flavor: dev
Version name: v4.11.2-38d0f1b
OS info: Android 9, sdk version: 28
Report description: No title
Logs:

```
E/Kuroba-dev | UNCAUGHT: java.lang.IllegalArgumentException: Bad symbols encountered at index 7, symbol = ' '
E/Kuroba-dev | UNCAUGHT: 	at com.github.k1rakishou.fsaf.util.FSAFUtils.checkBadSymbolsAndApplyResolutionStrategy$fsaf_release(FSAFUtils.kt:179)
E/Kuroba-dev | UNCAUGHT: 	at com.github.k1rakishou.fsaf.util.FSAFUtils.checkBadSymbolsAndApplyResolutionStrategy$fsaf_release(FSAFUtils.kt:146)
E/Kuroba-dev | UNCAUGHT: 	at com.github.k1rakishou.fsaf.file.AbstractFile.clone(AbstractFile.kt:86)
E/Kuroba-dev | UNCAUGHT: 	at com.github.k1rakishou.fsaf.file.AbstractFile.clone(AbstractFile.kt:63)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaver.deduplicateFile(ImageSaver.java:531)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaver.startDownloadTaskInternal(ImageSaver.java:220)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.saver.ImageSaver.startDownloadTask(ImageSaver.java:186)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveShare(ImageViewerController.java:326)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ImageViewerController.saveImage(ImageViewerController.java:457)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ImageViewerPresenter.onSwipeToSaveImage(ImageViewerPresenter.java:518)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.onSwipeToSaveImage(MultiImageView.java:281)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.swipeToSaveOrClose(MultiImageViewGestureDetector.kt:151)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onSwipedBottom(MultiImageViewGestureDetector.kt:135)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageViewGestureDetector.onFling(MultiImageViewGestureDetector.kt:84)
E/Kuroba-dev | UNCAUGHT: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:656)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.MultiImageView.lambda$new$0$MultiImageView(MultiImageView.java:145)
E/Kuroba-dev | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.-$$Lambda$MultiImageView$G1rwpqirIgHwz9JAWG3h73IU6Go.onTouch(Unknown Source:2)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.dispatchTouchEvent(View.java:12509)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
E/Kuroba-dev | UNCAUGHT: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
E/Kuroba-dev | UNCAUGHT: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.dispatchPointerEvent(View.java:12752)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5113)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$View
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 28
E/Kuroba-dev | UNCAUGHT: App Version: v4.11.2-38d0f1b
E/Kuroba-dev | UNCAUGHT: Development Build: Yes
E/Kuroba-dev | UNCAUGHT: Phone Model: Xiaomi Mi A1
```

**Comment by K1rakishou** [comment]
>v4.11.2-38d0f1b

??? What the hell? There is no apk with this version. Someone is building their own apks?

**Comment by Adamantcheese** [comment]
Seems like it, but none of the public forks have any activity.

**Comment by K1rakishou** [comment]
So this wasn't supposed to happen because we remove all the spaces right before calling clone() (where it had crashed). There is nothing to do. I think it was a custom change in the code of that particular build that caused the crash.

```
String fileName = filterName(name + (task.getShare() ? "_shared" : "") + "." + postImage.extension, true);
AbstractFile saveFile = saveLocation.clone(new FileSegment(fileName));
```
