### ISSUE TITLE
Crash report "kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = FileManagerId(id='ExternalFile')"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#798]
UUID: 74d11037a811229e07ec934e9b09e242
Build flavor: stable
Version name: v4.11.2
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(2020-03-04 11:51:52 UTC) ===
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = FileManagerId(id='ExternalFile')
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.getName(FileManager.kt:672)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.areTheSame(FileManager.kt:858)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.settings.base_directory.SharedLocationSetupDelegate.askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory(SharedLocationSetupDelegate.kt:102)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:147)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:120)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$1.run(MediaSettingsControllerPresenter.kt:263)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Unknown Source:2)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Unknown Source:242)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(Unknown Source:98)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 29
E/Kuroba | UNCAUGHT: App Version: v4.11.2
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: Xiaomi MI MAX 3


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: true
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.providers.downloads.documents/tree/downloads, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
Moved to https://github.com/K1rakishou/Fuck-Storage-Access-Framework/issues/19
