### ISSUE TITLE
Crash report "android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: null"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#812]
UUID: 61a24f91f27c0984228d2c0f374411b7
Build flavor: dev
Version name: v4.11.2-d789d75
OS info: Android 10, sdk version: 29
Report description: No title

```
E/Kuroba-dev | UNCAUGHT: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: null
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1945)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 29
E/Kuroba-dev | UNCAUGHT: App Version: v4.11.2-d789d75
E/Kuroba-dev | UNCAUGHT: Development Build: Yes
E/Kuroba-dev | UNCAUGHT: Phone Model: Google Pixel 3


=== SETTINGS ===
Prefetching enabled: true
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: true
Concurrent file loading chunks count: 4
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Pictures/Kuroba, SAF location: content://com.android.externalstorage.documents/tree/primary%3APictures%2FKuroba/document/primary%3APictures%2FKuroba, active: Java API
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba-dev/saved_threads, SAF location: content://com.android.externalstorage.documents/tree/primary%3AKuroba%2Fsaved_threads/document/primary%3AKuroba%2Fsaved_threads, active: SAF
Phone layout mode: AUTO
```

**Comment by K1rakishou** [comment]
https://stackoverflow.com/questions/51587863/bad-notification-for-start-foreground-invalid-channel-for-service-notification
