### ISSUE TITLE
Crash report " java.lang.ClassCastException: com.github.adamantcheese.chan.ui.controller.AlbumViewController cannot be cast to com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController$ToolbarSearchCallback"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#815]
UUID: 021bebbb9b04f945029b07b64be316c2
Build flavor: stable
Version name: v4.11.2
OS info: Android 9, sdk version: 28
Report description: No title

```
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.ClassCastException: com.github.adamantcheese.chan.ui.controller.AlbumViewController cannot be cast to com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController$ToolbarSearchCallback
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.onSearchVisibilityChanged(ToolbarNavigationController.java:106)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.onSearchVisibilityChanged(Toolbar.java:300)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarPresenter.openSearch(ToolbarPresenter.java:100)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.Toolbar.openSearch(Toolbar.java:208)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.showSearch(ToolbarNavigationController.java:44)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.searchClicked(ViewThreadController.java:266)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ViewThreadController.lambda$ju8Lvv0HC_x3T-nhkTECdNTwvvk(Unknown Source:0)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.-$$Lambda$ViewThreadController$ju8Lvv0HC_x3T-nhkTECdNTwvvk.clicked(Unknown Source:2)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuSubItem.performClick(ToolbarMenuSubItem.java:63)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.toolbar.ToolbarMenuItem$1.onFloatingMenuItemClicked(ToolbarMenuItem.java:177)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.FloatingMenu.lambda$show$0$FloatingMenu(FloatingMenu.java:169)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.-$$Lambda$FloatingMenu$jV5QSfy78m7c72btfnW0eJNDsgo.onItemClick(Unknown Source:6)
E/Kuroba | UNCAUGHT: 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1198)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView$3.run(AbsListView.java:4132)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:201)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6815)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.11.2
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: Xiaomi Mi 9 SE


=== SETTINGS ===
Prefetching enabled: true
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FKuroba, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

**Comment by Adamantcheese** [comment]
You can cause this by tapping the overflow menu button and then the album search button in rapid succession. This also resolves multiple floating menus appearing if you tap on the overflow menu several times.
