### ISSUE TITLE
Crash report "Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: null"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#831]
UUID: 9850a630332b2e9938e3f3bc0548484c
Build flavor: stable
Version name: v4.12.0
OS info: Android 9, sdk version: 28
Report description: No title

```
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: null
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7094)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 28
E/Kuroba | UNCAUGHT: App Version: v4.12.0
E/Kuroba | UNCAUGHT: Development Build: Release
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-A705FN
```

**Comment by K1rakishou** [comment]
Well, this still keeps happening for some unknown reason. Also, I noticed how can this be reproduced. Run the app via Android Studio. Once the "Waiting for debugger" dialog appears in the emulator click "Force Close" and it should crash. It's not a 100% STR, though.
