### ISSUE TITLE
Crash report "android.content.res.Resources$NotFoundException: String resource ID #0x3040002"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#841]
UUID: b2a71c3a5c43b9234b97587b374f3d6a
Build flavor: stable
Version name: v4.12.0
OS info: Android 5.0, sdk version: 21
Report description: No title
Logs:
```
=== LOGS(2020-03-29 13:41:37 UTC) ===
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: android.content.res.Resources$NotFoundException: String resource ID #0x3040002
E/Kuroba | UNCAUGHT: 	at android.content.res.Resources.getText(Resources.java:1334)
E/Kuroba | UNCAUGHT: 	at android.content.res.Resources.getString(Resources.java:1428)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:758)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:608)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:546)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:97)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:124)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:111)
E/Kuroba | UNCAUGHT: 	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:108)
E/Kuroba | UNCAUGHT: 	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:548)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:483)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:466)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:453)
E/Kuroba | UNCAUGHT: 	at android.webkit.WebView.<init>(WebView.java:443)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ReportController.onCreate(ReportController.java:53)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.Controller.addChildController(Controller.java:146)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.transition(NavigationController.java:128)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ToolbarNavigationController.transition(ToolbarNavigationController.java:49)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.transition(StyledToolbarNavigationController.java:62)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:54)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.StyledToolbarNavigationController.pushController(StyledToolbarNavigationController.java:57)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:42)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.controller.NavigationController.pushController(NavigationController.java:38)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.ThreadController.openReportController(ThreadController.java:173)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.openReportView(ThreadLayout.java:356)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.ThreadPresenter.onPostOptionClicked(ThreadPresenter.java:962)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell$1.onFloatingMenuItemClicked(PostCell.java:250)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.FloatingMenu.lambda$show$0$FloatingMenu(FloatingMenu.java:169)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.view.-$$Lambda$FloatingMenu$jV5QSfy78m7c72btfnW0eJNDsgo.onItemClick(lambda)
E/Kuroba | UNCAUGHT: 	at android.widget.AdapterView.performItemClick(AdapterView.java:334)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3686)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:5617)
E/Kuroba | UNCAUGHT: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:5383)
E/Kuroba | UNCAUGHT: 	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
E/Kuroba | UNCAUGHT: 	at android.view.View.dispatchTouchEvent(View.java:8920)
E/Kuroba | UNCAUGHT: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2673
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 21
E/Kuroba | UNCAUGHT: App Version: v4.12.0
E/Kuroba | UNCAUGHT: Development Build: Release
E/Kuroba | UNCAUGHT: Phone Model: samsung SAMSUNG-SM-G870A
```

**Comment by K1rakishou** [comment]
I guess we can just wrap it into try/catch and show a toast with an error like I did for the captcha.
