### ISSUE TITLE
Crash report "Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#850]
UUID: 33d3538c5efbacb2ac2df04fc63b33ce
Build flavor: stable
Version name: v4.12.0
OS info: Android 7.0, sdk version: 24
Report description: No title

```
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
E/Kuroba | UNCAUGHT: 	at android.os.Parcel.readException(Parcel.java:1697)
E/Kuroba | UNCAUGHT: 	at android.os.Parcel.readException(Parcel.java:1644)
E/Kuroba | UNCAUGHT: 	at android.content.pm.IPackageManager$Stub$Proxy.resolveIntent(IPackageManager.java:3281)
E/Kuroba | UNCAUGHT: 	at android.app.ApplicationPackageManager.resolveActivityAsUser(ApplicationPackageManager.java:807)
E/Kuroba | UNCAUGHT: 	at android.app.ApplicationPackageManager.resolveActivity(ApplicationPackageManager.java:801)
E/Kuroba | UNCAUGHT: 	at android.content.Intent.resolveActivity(Intent.java:6662)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.utils.AndroidUtils.openLinkInBrowser(AndroidUtils.java:222)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.openLinkConfirmed(ThreadLayout.java:350)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.ThreadLayout.lambda$openLink$1$ThreadLayout(ThreadLayout.java:337)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.layout.-$$Lambda$ThreadLayout$8JqsYWiJPb8EM5ctsK3IGYT2Pjk.onClick(lambda)
E/Kuroba | UNCAUGHT: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:203)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 24
E/Kuroba | UNCAUGHT: App Version: v4.12.0
E/Kuroba | UNCAUGHT: Development Build: Release
E/Kuroba | UNCAUGHT: Phone Model: BLU Studio View XL
```

**Comment by K1rakishou** [comment]
We probably can't fix it but at least we can make it not crash the app.
