### ISSUE TITLE
App crashes if you make a post and then go to another thread when it's uploading

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#87]
I had this crash multiple times already on Kuroba. Here's a log, hope it helps.
```--------- beginning of system
W/ViewRootImpl[PopupWindow:eb06d85]: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=291.62137, y[0]=-20.105392, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=56033257, downTime=56033246, deviceId=6, source=0x1002 }
--------- beginning of main
I/art     : Starting a blocking GC AddRemoveAppImageSpace
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/NFC     : this device does not have NFC support
W/PhoneWindow: Previously focused view reported id 2131296339 during save, but can't be found during restore.
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
I/art     : Background partial concurrent mark sweep GC freed 35112(3MB) AllocSpace objects, 65(4MB) LOS objects, 40% free, 8MB/14MB, paused 7.606ms total 95.208ms
I/art     : Background partial concurrent mark sweep GC freed 49625(4MB) AllocSpace objects, 72(5MB) LOS objects, 40% free, 8MB/14MB, paused 2.245ms total 105.512ms
D/OpenGLRenderer: endAllActiveAnimators on 0x9b1b6700 (H) with handle 0x989d3500
I/art     : Background partial concurrent mark sweep GC freed 32067(3MB) AllocSpace objects, 99(6MB) LOS objects, 39% free, 8MB/14MB, paused 1.852ms total 134.048ms
D/OpenGLRenderer: endAllActiveAnimators on 0x9b2f6580 (RippleDrawable) with handle 0x98b5cd00
W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
I/art     : Starting a blocking GC AddRemoveAppImageSpace
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/NFC     : this device does not have NFC support
W/PhoneWindow: Previously focused view reported id 2131296339 during save, but can't be found during restore.
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
D/OpenGLRenderer: endAllActiveAnimators on 0x9ae6e800 (RippleDrawable) with handle 0x9b08cba0
W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
I/art     : Starting a blocking GC AddRemoveAppImageSpace
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/NFC     : this device does not have NFC support
W/PhoneWindow: Previously focused view reported id 2131296339 during save, but can't be found during restore.
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
W/art     : Suspending all threads took: 7.690ms
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
D/OpenGLRenderer: endAllActiveAnimators on 0x9b2a5c00 (RippleDrawable) with handle 0x99cc62f0
W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
D/OpenGLRenderer: endAllActiveAnimators on 0x9b2a4e00 (H) with handle 0xab4bac20
I/art     : Background sticky concurrent mark sweep GC freed 21611(2MB) AllocSpace objects, 40(2MB) LOS objects, 32% free, 9MB/13MB, paused 5.130ms total 32.859ms
I/art     : Background sticky concurrent mark sweep GC freed 16683(1924KB) AllocSpace objects, 54(3MB) LOS objects, 22% free, 10MB/13MB, paused 5.126ms total 70.215ms
I/art     : Background partial concurrent mark sweep GC freed 41893(3MB) AllocSpace objects, 95(6MB) LOS objects, 40% free, 9MB/15MB, paused 1.286ms total 101.559ms
D/AndroidRuntime: Shutting down VM
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to read from field 'com.github.adamantcheese.chan.b.l.j com.github.adamantcheese.chan.core.model.orm.Loadable.site' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.h.r.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.e.c.n.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.e.c.n.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.b.e.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.b.a.run(lambda)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
I/art     : System.exit called, status: 999
I/AndroidRuntime: VM exiting with result code 999, cleanup skipped.
I/art     : Starting a blocking GC AddRemoveAppImageSpace
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/NFC     : this device does not have NFC support
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
I/art     : Background partial concurrent mark sweep GC freed 47758(3MB) AllocSpace objects, 59(3MB) LOS objects, 40% free, 8MB/14MB, paused 4.166ms total 147.506ms
```

**Comment by Adamantcheese** [comment]
I've updated your log to make it more readable (use 3 backticks instead of 1 for block code in Markdown).
