### ISSUE TITLE
Crash report "java.lang.StringIndexOutOfBoundsException: length=231; regionStart=98; regionLength=-21"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#903]
UUID: e3606c0015a320af1b5a6b277856df6d
Build flavor: stable
Version name: v4.12.0
OS info: Android 7.0, sdk version: 24
Report description: No title
Logs:
```
=== LOGS(2020-05-24 10:58:56 UTC) ===
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: java.lang.StringIndexOutOfBoundsException: length=231; regionStart=98; regionLength=-21
E/Kuroba | UNCAUGHT: 	at java.lang.String.substring(String.java:1931)
E/Kuroba | UNCAUGHT: 	at android.text.SpannableStringInternal.<init>(SpannableStringInternal.java:33)
E/Kuroba | UNCAUGHT: 	at android.text.SpannableString.<init>(SpannableString.java:34)
E/Kuroba | UNCAUGHT: 	at android.text.SpannableString.subSequence(SpannableString.java:54)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.cell.PostCell$2.onActionItemClicked(PostCell.java:504)
E/Kuroba | UNCAUGHT: 	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4145)
E/Kuroba | UNCAUGHT: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2740)
E/Kuroba | UNCAUGHT: 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:95)
E/Kuroba | UNCAUGHT: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
E/Kuroba | UNCAUGHT: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:157)
E/Kuroba | UNCAUGHT: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
E/Kuroba | UNCAUGHT: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
E/Kuroba | UNCAUGHT: 	at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:124)
E/Kuroba | UNCAUGHT: 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:414)
E/Kuroba | UNCAUGHT: 	at android.view.View.performClick(View.java:6213)
E/Kuroba | UNCAUGHT: 	at android.widget.TextView.performClick(TextView.java:11074)
E/Kuroba | UNCAUGHT: 	at android.view.View$PerformClick.run(View.java:23645)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 24
E/Kuroba | UNCAUGHT: App Version: v4.12.0
E/Kuroba | UNCAUGHT: Development Build: Release
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G935F


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: false, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: true
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.externalstorage.documents/tree/B40F-2CC3%3AEbaumsworld/document/B40F-2CC3%3AEbaumsworld, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
I remember there were similar crashes but this one actually has our code in the stacktrace so at least it's possible to do something with it.
