### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by floppyD** [Adamantcheese/Kuroba#92]
I was browsing and the app crashed suddenly. I think this happened about 3 times already since I installed Kuroba, dunno if they are related. Anyway, here's a log.
```--------- beginning of system
W/ViewRootImpl[StartActivity]: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=462.3329, y[0]=678.121, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=8739690, downTime=8739667, deviceId=6, source=0x1002 }
W/ViewRootImpl[StartActivity]: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=309.54507, y[0]=816.0133, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=12280398, downTime=12280376, deviceId=6, source=0x1002 }
--------- beginning of main
I/art     : Starting a blocking GC AddRemoveAppImageSpace
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/NFC     : this device does not have NFC support
W/PhoneWindow: Previously focused view reported id 2131296339 during save, but can't be found during restore.
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
D/OpenGLRenderer: endAllActiveAnimators on 0x9a8b1d80 (H) with handle 0x98948330
I/art     : Background partial concurrent mark sweep GC freed 81575(5MB) AllocSpace objects, 4(268KB) LOS objects, 40% free, 10MB/17MB, paused 1.413ms total 102.294ms
D/OpenGLRenderer: endAllActiveAnimators on 0x99089800 (H) with handle 0x9b174db0
D/OpenGLRenderer: endAllActiveAnimators on 0x98b1de00 (H) with handle 0x9b174fe0
I/art     : Background sticky concurrent mark sweep GC freed 75638(5MB) AllocSpace objects, 6(348KB) LOS objects, 30% free, 11MB/17MB, paused 7.027ms total 44.102ms
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
I/art     : Background partial concurrent mark sweep GC freed 83599(6MB) AllocSpace objects, 32(1352KB) LOS objects, 40% free, 9MB/15MB, paused 1.505ms total 101.609ms
D/OpenGLRenderer: endAllActiveAnimators on 0x9b2cd280 (H) with handle 0x9bdbf130
I/art     : Background partial concurrent mark sweep GC freed 80479(5MB) AllocSpace objects, 15(552KB) LOS objects, 40% free, 10MB/18MB, paused 1.299ms total 110.810ms
D/AndroidRuntime: Shutting down VM
E/Kuroba | UNCAUGHT: java.lang.NullPointerException: Attempt to read from field 'com.github.adamantcheese.chan.b.l.j com.github.adamantcheese.chan.core.model.orm.Loadable.site' on a null object reference
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.h.r.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.e.c.n.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.e.c.n.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.b.e.a()
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.b.l.b.a.run(lambda)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:751)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:154)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/Kuroba | UNCAUGHT: .
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ----------------------------------------
E/Kuroba | UNCAUGHT: .
I/art     : System.exit called, status: 999
I/AndroidRuntime: VM exiting with result code 999, cleanup skipped.
I/art     : Starting a blocking GC AddRemoveAppImageSpace
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
V/NFC     : this device does not have NFC support
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
I/Adreno-EGL: Build Date: 02/18/17 Sat
I/Adreno-EGL: Local Branch: 
I/Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
I/Adreno-EGL: Local Patches: NONE
I/Adreno-EGL: Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
W/System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
I/art     : Background sticky concurrent mark sweep GC freed 36683(1810KB) AllocSpace objects, 6(716KB) LOS objects, 27% free, 5MB/8MB, paused 8.392ms total 69.210ms
```

**Comment by Adamantcheese** [comment]
This crash is exactly the same as the one listed in #87, so I'm going to close this and leave the other one open.
