### ISSUE TITLE
Report "pressing install update crash"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#933]
UUID: b63a30ba5aad5149eea1af5cff9fb424
Build flavor: dev
Version name: v4.12.0-19c8e9a
OS info: Android 5.0.2, sdk version: 21
Report description:
Logs:
```
D/Kuroba-dev | UpdateManager: Calling update API
D/Kuroba-dev | FileCacheV2: [main]: Downloading a file, url = https://kuroba.io:8443/apk/41200_19c8e9aec8a4f9566762c28a5556af21b23e6XXX.apk
D/Kuroba-dev | PartialContentSupportChecker: Sending HEAD request to url (https://kuroba.io:8443/apk/41200_19c8e9aec8a4f9566762c28a5556af21b23e6XXX.apk)
D/Kuroba-dev | PartialContentSupportChecker: [OkHttp https://kuroba.io:8443/...]: (https://kuroba.io:8443/apk/41200_19c8e9aec8a4f9566762c28a5556af21b23e6XXX.apk) does not support partial content (ACCEPT_RANGES_HEADER is null
D/Kuroba-dev | PartialContentSupportChecker: HEAD request to url (https://kuroba.io:8443/apk/41200_19c8e9aec8a4f9566762c28a5556af21b23e6XXX.apk) has succeeded, time = 52ms
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-3]: Download ([FileDownloadRequest: url = https://kuroba.io:8443/apk/41200_19c8e9aec8a4f9566762c28a5556af21b23e6XXX.apk, outputFileName = 67e390aeb8f187ee4354ca92267c43c8.cache]) has started. Chunks count = 1. Network class = WIFI. Downloads = 1
D/Kuroba-dev | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Starting downloading (https://kuroba.io:8443/apk/41200_19c8e9aec8a4f9566762c28a5556af21b23e6XXX.apk)
E/Kuroba-dev | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba-dev | UNCAUGHT: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Paint.getAlpha()' on a null object reference
E/Kuroba-dev | UNCAUGHT: 	at android.graphics.drawable.NinePatchDrawable.draw(NinePatchDrawable.java:252)
E/Kuroba-dev | UNCAUGHT: 	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:537)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.ProgressBar.drawTrack(ProgressBar.java:1793)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.ProgressBar.onDraw(ProgressBar.java:1760)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.draw(FrameLayout.java:592)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.draw(FrameLayout.java:592)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3708)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.draw(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.widget.FrameLayout.draw(FrameLayout.java:592)
E/Kuroba-dev | UNCAUGHT: 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:3047)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.updateDisplayListIfDirty(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.View.getDisplayList(View.java)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:307)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:313)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:352)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2811)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2634)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2222)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1230)
E/Kuroba-dev | UNCAUGHT: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6726)
E/Kuroba-dev | UNCAUGHT: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
E/Kuroba-dev | UNCAUGHT: 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/Kuroba-dev | UNCAUGHT: 	at android.view.Choreographer.doFrame(Choreographer.java:560)
E/Kuroba-dev | UNCAUGHT: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:739)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Kuroba-dev | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:145)
E/Kuroba-dev | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
E/Kuroba-dev | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native M
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba-dev | UNCAUGHT: ------------------------------
E/Kuroba-dev | UNCAUGHT: Android API Level: 21
E/Kuroba-dev | UNCAUGHT: App Version: v4.12.0-66d420d
D/Kuroba-dev | AndroidUtils: Build Signature: 10d4e433
E/Kuroba-dev | UNCAUGHT: Development Build: Development
E/Kuroba-dev | UNCAUGHT: Phone Model: samsung SM-A310F
D/Kuroba-dev | ReportManager: Stored new crash log, path = /storage/emulated/0/Android/data/com.github.adamantcheese.chan.dev/cache/crashlogs/crashlog_1592103851376.txt
D/Kuroba-dev | AndroidUtils: Build Signature: 10d4e433
```

**Comment by Adamantcheese** [comment]
Internal Android failure that I can't fix. Looking at the source code of getPaint() for that SDK, there should be no way for this failure to occur because that method can't return a null value; someone's got a fucked ROM and anyways this Android version is ancient.
