### ISSUE TITLE
Report "Deep zoom loading failed error while browsing /sci/ catalog"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#935]
UUID: 45fdfd96eec92c434bfa057348c22e51
Build flavor: dev
Version name: v4.12.0-b4f080e
OS info: Android 10, sdk version: 29
Report description:
Logs:
```
W/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | ReportManager: No new crash logs
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | WakeUpdateReceiver: Alarm trigger at 12:04:58 AM
W/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | AndroidUtils: Build Signature: 10d4e433
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
D/Kuroba-dev | WakeUpdateReceiver: Alarm trigger at 12:05:00 AM
W/Kuroba-dev | WakeManager: Background update broadcast ignored because it was requested too soon
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | ChanThreadLoader: Requested /c/, 3683XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 5XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 4XXX
D/Kuroba-dev | PinWatcher: postlast=31 postnew=31 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=9s
D/Kuroba-dev | PinWatcher: postlast=75 postnew=78 werenewposts=true quotelast=1 quotenew=1 werenewquotes=false nextload=9s
D/Kuroba-dev | PinWatcher: postlast=32 postnew=32 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=10s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | ChanThreadLoader: Requested /c/, 3683XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 5XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 4XXX
D/Kuroba-dev | PinWatcher: postlast=75 postnew=78 werenewposts=true quotelast=1 quotenew=1 werenewquotes=false nextload=15s
D/Kuroba-dev | PinWatcher: postlast=31 postnew=31 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=14s
D/Kuroba-dev | PinWatcher: postlast=32 postnew=32 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=15s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | ChanThreadLoader: Requested /c/, 3683XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 5XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 4XXX
D/Kuroba-dev | PinWatcher: postlast=31 postnew=31 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=20s
D/Kuroba-dev | PinWatcher: postlast=32 postnew=32 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=20s
D/Kuroba-dev | PinWatcher: postlast=75 postnew=78 werenewposts=true quotelast=1 quotenew=1 werenewquotes=false nextload=19s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | ChanThreadLoader: Requested /c/, 3683XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 5XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 4XXX
D/Kuroba-dev | PinWatcher: postlast=31 postnew=31 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=29s
D/Kuroba-dev | PinWatcher: postlast=75 postnew=78 werenewposts=true quotelast=1 quotenew=1 werenewquotes=false nextload=29s
D/Kuroba-dev | PinWatcher: postlast=32 postnew=32 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=29s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
D/Kuroba-dev | Dependency Injection: Image saver
D/Kuroba-dev | Dependency Injection: WebmStreamingSource
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/sci/1592463719XXX.jpg
D/Kuroba-dev | PartialContentSupportChecker: Sending HEAD request to url (https://i.4cdn.org/sci/1592463719XXX.jpg)
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592435613XXX.jpg
D/Kuroba-dev | PartialContentSupportChecker: [OkHttp https://i.4cdn.org/...]: url = https://i.4cdn.org/sci/1592463719XXX.jpg, fileSize = 105730, cfCacheStatusHeader = MISS, took = 88ms
D/Kuroba-dev | PartialContentSupportChecker: HEAD request to url (https://i.4cdn.org/sci/1592463719XXX.jpg) has succeeded, time = 88ms
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-3]: Download ([FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]) has started. Chunks count = 4. Network class = WIFI. Downloads = 1
D/Kuroba-dev | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: File (https://i.4cdn.org/sci/1592463719XXX.jpg) was split into chunks: [Chunk(start=0, end=26431), Chunk(start=26432, end=52863), Chunk(start=52864, end=79295), Chunk(start=79296, end=105729)]
D/Kuroba-dev | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Starting downloading (https://i.4cdn.org/sci/1592463719XXX.jpg)
D/Kuroba-dev | ChunkDownloader: [NormalFileCacheV2Thread-3]: Start downloading (https://i.4cdn.org/sci/1592463719XXX.jpg), chunk 0..26431
D/Kuroba-dev | ChunkDownloader: [NormalFileCacheV2Thread-3]: Start downloading (https://i.4cdn.org/sci/1592463719XXX.jpg), chunk 26432..52863
D/Kuroba-dev | ChunkDownloader: [NormalFileCacheV2Thread-3]: Start downloading (https://i.4cdn.org/sci/1592463719XXX.jpg), chunk 52864..79295
D/Kuroba-dev | ChunkDownloader: [NormalFileCacheV2Thread-3]: Start downloading (https://i.4cdn.org/sci/1592463719XXX.jpg), chunk 79296..105729
D/Kuroba-dev | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Got chunk response in (https://i.4cdn.org/sci/1592463719XXX.jpg) 26432..52863 in 35ms
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) (https://i.4cdn.org/sci/1592463719XXX.jpg) called for chunk 26432..52863
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-0]: Progress chunkIndex = 1, downloaded: (8.0 KiB) (8192 B) / 25.8 KiB (26432 B), 30.992737%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-0]: Progress chunkIndex = 1, downloaded: (16.0 KiB) (16384 B) / 25.8 KiB (26432 B), 61.985474%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-0]: Progress chunkIndex = 1, downloaded: (24.0 KiB) (24576 B) / 25.8 KiB (26432 B), 92.97821%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-0]: Progress chunkIndex = 1, downloaded: (25.8 KiB) (26432 B) / 25.8 KiB (26432 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-0]: Progress chunkIndex = 1, downloaded: (25.8 KiB) (26432 B) / 25.8 KiB (26432 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-0]: pipeChunk(1) (https://i.4cdn.org/sci/1592463719XXX.jpg) SUCCESS for chunk 26432..52863
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) success, url = https://i.4cdn.org/sci/1592463719XXX.jpg, chunk 26432..52863
D/Kuroba-dev | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Got chunk response in (https://i.4cdn.org/sci/1592463719XXX.jpg) 0..26431 in 52ms
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-3]: storeChunkInFile(0) (https://i.4cdn.org/sci/1592463719XXX.jpg) called for chunk 0..26431
D/Kuroba-dev | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Got chunk response in (https://i.4cdn.org/sci/1592463719XXX.jpg) 52864..79295 in 51ms
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(2) (https://i.4cdn.org/sci/1592463719XXX.jpg) called for chunk 52864..79295
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-3]: pipeChunk(0) (https://i.4cdn.org/sci/1592463719XXX.jpg) SUCCESS for chunk 0..26431
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 2, downloaded: (8.0 KiB) (8192 B) / 25.8 KiB (26432 B), 30.992737%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-3]: storeChunkInFile(0) success, url = https://i.4cdn.org/sci/1592463719XXX.jpg, chunk 0..26431
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 0, downloaded: (8.0 KiB) (8192 B) / 25.8 KiB (26432 B), 30.992737%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 0, downloaded: (16.0 KiB) (16384 B) / 25.8 KiB (26432 B), 61.985474%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ChunkDownloader: [OkHttp https://i.4cdn.org/...]: Got chunk response in (https://i.4cdn.org/sci/1592463719XXX.jpg) 79296..105729 in 54ms
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 0, downloaded: (24.0 KiB) (24576 B) / 25.8 KiB (26432 B), 92.97821%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-2]: storeChunkInFile(3) (https://i.4cdn.org/sci/1592463719XXX.jpg) called for chunk 79296..105729
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 0, downloaded: (25.8 KiB) (26432 B) / 25.8 KiB (26432 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 0, downloaded: (25.8 KiB) (26432 B) / 25.8 KiB (26432 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 2, downloaded: (16.0 KiB) (16384 B) / 25.8 KiB (26432 B), 61.985474%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 3, downloaded: (8.0 KiB) (8192 B) / 25.8 KiB (26434 B), 30.990393%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-2]: pipeChunk(3) (https://i.4cdn.org/sci/1592463719XXX.jpg) SUCCESS for chunk 79296..105729
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-2]: storeChunkInFile(3) success, url = https://i.4cdn.org/sci/1592463719XXX.jpg, chunk 79296..105729
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 3, downloaded: (16.0 KiB) (16384 B) / 25.8 KiB (26434 B), 61.980785%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 3, downloaded: (24.0 KiB) (24576 B) / 25.8 KiB (26434 B), 92.971176%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 3, downloaded: (25.8 KiB) (26434 B) / 25.8 KiB (26434 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 3, downloaded: (25.8 KiB) (26434 B) / 25.8 KiB (26434 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 2, downloaded: (24.0 KiB) (24576 B) / 25.8 KiB (26432 B), 92.97821%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 2, downloaded: (25.8 KiB) (26432 B) / 25.8 KiB (26432 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Progress chunkIndex = 2, downloaded: (25.8 KiB) (26432 B) / 25.8 KiB (26432 B), 100.0%) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-1]: pipeChunk(2) (https://i.4cdn.org/sci/1592463719XXX.jpg) SUCCESS for chunk 52864..79295
D/Kuroba-dev | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(2) success, url = https://i.4cdn.org/sci/1592463719XXX.jpg, chunk 52864..79295
D/Kuroba-dev | ChunkPersister: [NormalFileCacheV2Thread-1]: mergeChunksIntoCacheFile called (https://i.4cdn.org/sci/1592463719XXX.jpg), chunks count = 4
D/Kuroba-dev | FileCacheV2: [NormalFileCacheV2Thread-1]: Success (downloaded = 103.3 KiB (105730 B), total = 103.3 KiB (105730 B), took 73ms, network class = WIFI, downloads = 1) for request [FileDownloadRequest: url = https://i.4cdn.org/sci/1592463719XXX.jpg, outputFileName = 6d8402b870e7b6eda0a52ffcd551b6b3.cache]
D/Kuroba-dev | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Completed downloading (https://i.4cdn.org/sci/1592463719XXX.jpg)
D/Kuroba-dev | CustomScaleImageView: onReady
D/Kuroba-dev | CustomScaleImageView: onImageLoaded
D/Kuroba-dev | ImageSaveTask: ImageSaveTask.run() destination = /storage/emulated/0/Pictures/Kuroba/1592390537077.jpg
D/Kuroba-dev | FileCacheV2: [ImageSaverThread-0]: File already downloaded, url = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | ImageSaver: imageSaveTaskFinished imageUrl = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=false
D/Kuroba-dev | WatchManager: Setting interval type from FOREGROUND to NONE
D/Kuroba-dev | WakeManager: Unregistered class com.github.adamantcheese.chan.core.manager.WatchManager
W/Kuroba-dev | StartActivity: Workaround for intent mismatch.
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | WatchManager: Setting interval type from NONE to FOREGROUND
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592463719XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592435613XXX.jpg
W/Kuroba-dev | CustomScaleImageView: onImageLoadError
W/Kuroba-dev | CustomScaleImageView: java.io.IOException: Image format not supported
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:126)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:152)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
W/Kuroba-dev | CustomScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Kuroba-dev | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:919)
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592463719XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592435613XXX.jpg
W/Kuroba-dev | CustomScaleImageView: onImageLoadError
W/Kuroba-dev | CustomScaleImageView: java.io.IOException: Image format not supported
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:126)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:152)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
W/Kuroba-dev | CustomScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Kuroba-dev | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:919)
D/Kuroba-dev | ChanThreadLoader: Requested /sci/, 0
D/Kuroba-dev | ThreadPresenter: onChanLoaderData() downloadingState = NotDownloading
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592463719XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592060540XXX.jpg
W/Kuroba-dev | CustomScaleImageView: onImageLoadError
W/Kuroba-dev | CustomScaleImageView: java.io.IOException: Image format not supported
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:126)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:152)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
W/Kuroba-dev | CustomScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Kuroba-dev | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:919)
D/Kuroba-dev | AndroidUtils: Build Signature: 10d4e433
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
D/Kuroba-dev | WatchManager: update() from foreground
D/Kuroba-dev | WatchManager: Current interval is FOREGROUND_INTERVAL_ONLY_WATCHES
D/Kuroba-dev | ChanThreadLoader: Requested /c/, 3683XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 5XXX
D/Kuroba-dev | ChanThreadLoader: Requested /drug/, 4XXX
D/Kuroba-dev | PinWatcher: postlast=75 postnew=78 werenewposts=true quotelast=1 quotenew=1 werenewquotes=false nextload=59s
D/Kuroba-dev | PinWatcher: postlast=31 postnew=31 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=59s
D/Kuroba-dev | PinWatcher: postlast=32 postnew=32 werenewposts=false quotelast=0 quotenew=0 werenewquotes=false nextload=59s
D/Kuroba-dev | WatchManager: updateState watchEnabled=true backgroundEnabled=false foreground=true
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
D/Kuroba-dev | ImageLoaderV2: Falling back to imageLoaderV1 load the image https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592406158XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592463719XXX.jpg
D/Kuroba-dev | FileCacheV2: [main]: File already downloaded, url = https://i.4cdn.org/sci/1592060540XXX.jpg
W/Kuroba-dev | CustomScaleImageView: onImageLoadError
W/Kuroba-dev | CustomScaleImageView: java.io.IOException: Image format not supported
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:126)
W/Kuroba-dev | CustomScaleImageView: 	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:152)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:96)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1559)
W/Kuroba-dev | CustomScaleImageView: 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1534)
W/Kuroba-dev | CustomScaleImageView: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Kuroba-dev | CustomScaleImageView: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Kuroba-dev | CustomScaleImageView: 	at java.lang.Thread.run(Thread.java:919)
D/Kuroba-dev | AndroidUtils: Build Signature: 10d4e433
D/Kuroba-dev | AndroidUtils: waitForLayout requested a re-layout by returning false
```

**Comment by K1rakishou** [comment]
This might be a bug in chunked file downloader but if it really were it then it would have thrown "Bad file md5" error first (If that check still exists).

**Comment by Adamantcheese** [comment]
Likely some sort of corrupt file, pretty much every other JPG works.

**Comment by Adamantcheese** [comment]
I'm going to close this as there isn't really enough information to figure out what could've caused this anymore.
