### ISSUE TITLE
Report "Updates"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#950]
UUID: 13c9679b4d00b683e7cd3f64af06b69a
Build flavor: stable
Version name: v4.13.0
OS info: Android 6.0.1, sdk version: 23
Report description: Fails to check for updates.
Logs:
```
I/Kuroba | WakeManager: Started background alarm with an interval of 15 minutes
I/Kuroba | FilterWatchManager: Processing filter loaders, started at 22:52:41
E/Kuroba | NetUtils: Error parsing JSON: 
E/Kuroba | NetUtils: java.lang.IllegalStateException: Expected a name but was STRING
E/Kuroba | NetUtils: 	at android.util.JsonReader.nextName(JsonReader.java:390)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parseRelease(UpdateApiParser.java:67)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:53)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:44)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.utils.NetUtils$2.onResponse(NetUtils.java:154)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/Kuroba | NetUtils: 	at java.lang.Thread.run(Thread.java:818)
E/Kuroba | UpdateManager: Failed to process stable API call for updating
E/Kuroba | NetUtils: Error parsing JSON: 
E/Kuroba | NetUtils: java.lang.IllegalStateException: Expected a name but was STRING
E/Kuroba | NetUtils: 	at android.util.JsonReader.nextName(JsonReader.java:390)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parseRelease(UpdateApiParser.java:67)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:53)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:44)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.utils.NetUtils$2.onResponse(NetUtils.java:154)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/Kuroba | NetUtils: 	at java.lang.Thread.run(Thread.java:818)
E/Kuroba | UpdateManager: Failed to process stable API call for updating
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
W/Kuroba | WakeManager: Background update broadcast ignored because it was requested too soon
```

**Comment by Adamantcheese** [comment]
There's no problem with the updater, someone is just getting a bad return value from Github's API. Probably something blocking their access to that endpoint.

**Comment by K1rakishou** [comment]
Maybe more logs should be added so it's more obvious what's going on there?

**Comment by K1rakishou** [comment]
Updating
UUID: 2f78f90cab01b91ae970df4fb7ba4315
Build flavor: stable
Version name: v4.13.4
OS info: Android 6.0.1, sdk version: 23
Report description: "Failed to check for updates" error message.
Logs:
```
E/Kuroba | NetUtils: Error parsing JSON: 
E/Kuroba | NetUtils: java.lang.IllegalStateException: Expected a name but was STRING
E/Kuroba | NetUtils: 	at android.util.JsonReader.nextName(JsonReader.java:390)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parseRelease(UpdateApiParser.java:67)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:53)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:44)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.utils.NetUtils$2.onResponse(NetUtils.java:161)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/Kuroba | NetUtils: 	at java.lang.Thread.run(Thread.java:818)
E/Kuroba | UpdateManager: Failed to process stable API call for updating
```

FYI this thing still keeps happening, people are sending reports.

**Comment by Adamantcheese** [comment]
Well I don't know what to do except add more debug logging I guess.
