### ISSUE TITLE
Report "Checking for updates"

### ISSUE THREAD

**Issue by K1rakishou** [Adamantcheese/Kuroba#989]
UUID: c8ff888e5fd653625f4a757020b9b20a
Build flavor: stable
Version name: v4.13.5
OS info: Android 6.0.1, sdk version: 23
Report description: v4.13.5 fails to check for updates, DEV release for some reason has no issues searching for updates. Maybe increase the amount of logging for error / crash reports.
Logs:
```
E/Kuroba | NetUtils: Error parsing JSON: 
E/Kuroba | NetUtils: java.lang.IllegalStateException: Expected a name but was STRING
E/Kuroba | NetUtils: 	at android.util.JsonReader.nextName(JsonReader.java:390)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parseRelease(UpdateApiParser.java:70)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:56)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.core.net.UpdateApiParser.parse(UpdateApiParser.java:44)
E/Kuroba | NetUtils: 	at com.github.adamantcheese.chan.utils.NetUtils$2.onResponse(NetUtils.java:213)
E/Kuroba | NetUtils: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/Kuroba | NetUtils: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/Kuroba | NetUtils: 	at java.lang.Thread.run(Thread.java:818)
E/Kuroba | UpdateManager: Failed to process stable API call for updating
```

**Comment by K1rakishou** [comment]
Actually this one is caused by having no response body, so there is probably nothing to fix on the client side.
